.\" Copyright (c) 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" This code is derived from software contributed to Berkeley by
.\" the American National Standards Committee X3, on Information
.\" Processing Systems.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)isdigit.3	8.1 (Berkeley) 6/4/93
.\" $FreeBSD: src/lib/libc/locale/isdigit.3,v 1.25 2009/09/04 07:44:58 des Exp $
.\"
.Dd May 4, 2007
.Dt ISDIGIT 3
.Os
.Sh NAME
.Nm isdigit, isnumber
.Nd decimal-digit character test
.Sh LIBRARY
.Lb libc
.Sh SYNOPSIS
.In ctype.h
.Ft int
.Fn isdigit "int c"
.Ft int
.Fn isnumber "int c"
.Sh DESCRIPTION
The
.Fn isdigit
function tests for a decimal digit character.
Regardless of locale, this includes the following characters only:
.Pp
.Bl -column \&``0''______ \&``0''______ \&``0''______ \&``0''______ \&``0''______
.It "\&``0''\t``1''\t``2''\t``3''\t``4''"
.It "\&``5''\t``6''\t``7''\t``8''\t``9''"
.El
.Pp
The
.Fn isnumber
function behaves similarly to
.Fn isdigit ,
but may recognize additional characters, depending on the current locale
setting.
.Pp
The value of the argument must be representable as an
.Vt "unsigned char"
or the value of
.Dv EOF .
.Sh RETURN VALUES
The
.Fn isdigit
and
.Fn isnumber
functions return zero if the character tests false and
return non-zero if the character tests true.
.Sh COMPATIBILITY
The
.Bx 4.4
extension of accepting arguments outside of the range of the
.Vt "unsigned char"
type in locales with large character sets is considered obsolete
and may not be supported in future releases.
The
.Fn iswdigit
function should be used instead.
.Sh SEE ALSO
.Xr ctype 3 ,
.Xr isalnum_l 3 ,
.Xr iswdigit 3 ,
.Xr multibyte 3 ,
.Xr ascii 7
.Sh STANDARDS
The
.Fn isdigit
function conforms to
.St -isoC .
.Sh HISTORY
The
.Fn isnumber
function appeared in
.Bx 4.4 .
