#ifndef _COREVIDEO_CVIMAGEBUFFER_H_
#define _COREVIDEO_CVIMAGEBUFFER_H_

#include <sys/cdefs.h>
#include <CoreVideo/CVBuffer.h>

typedef CVBufferRef CVImageBufferRef;

extern const CFStringRef kCVImageBufferPixelAspectRatioKey;
extern const CFStringRef kCVImageBufferGammaLevelKey;
extern const CFStringRef kCVImageBufferYCbCrMatrixKey;
extern const CFStringRef kCVImageBufferColorPrimariesKey;
extern const CFStringRef kCVImageBufferTransferFunctionKey;

extern const CFStringRef kCVImageBufferCGColorSpaceKey;

extern const CFStringRef kCVImageBufferChromaLocation_Bottom;
extern const CFStringRef kCVImageBufferChromaLocation_BottomLeft;
extern const CFStringRef kCVImageBufferChromaLocation_Center;
extern const CFStringRef kCVImageBufferChromaLocation_DV420;
extern const CFStringRef kCVImageBufferChromaLocation_Top;
extern const CFStringRef kCVImageBufferChromaLocation_TopLeft;

extern const CFStringRef kCVImageBufferColorPrimaries_ITU_R_2020;
extern const CFStringRef kCVImageBufferYCbCrMatrix_ITU_R_2020;

extern const CFStringRef kCVImageBufferTransferFunction_ITU_R_2020;
extern const CFStringRef kCVImageBufferTransferFunction_ITU_R_2100_HLG;
extern const CFStringRef kCVImageBufferTransferFunction_Linear;
extern const CFStringRef kCVImageBufferTransferFunction_SMPTE_ST_2084_PQ;
extern const CFStringRef kCVImageBufferTransferFunction_SMPTE_ST_428_1;
extern const CFStringRef kCVImageBufferTransferFunction_SMPTE_C;

extern CFStringRef const kCVImageBufferPixelAspectRatioHorizontalSpacingKey;
extern CFStringRef const kCVImageBufferPixelAspectRatioVerticalSpacingKey;

extern CFStringRef const kCVImageBufferYCbCrMatrix_ITU_R_709_2;
extern CFStringRef const kCVImageBufferYCbCrMatrix_ITU_R_601_4;
extern CFStringRef const kCVImageBufferYCbCrMatrix_SMPTE_240M_1995;
extern CFStringRef const kCVImageBufferColorPrimaries_ITU_R_709_2;
extern CFStringRef const kCVImageBufferColorPrimaries_EBU_3213;
extern CFStringRef const kCVImageBufferColorPrimaries_SMPTE_C;
extern CFStringRef const kCVImageBufferTransferFunction_ITU_R_709_2;
extern CFStringRef const kCVImageBufferTransferFunction_SMPTE_240M_1995;
extern CFStringRef const kCVImageBufferTransferFunction_UseGamma;

#endif // _COREVIDEO_CVIMAGEBUFFER_H_
