
find_path(LIBGNUSTEPGUI_INCLUDE_DIR AppKit/AppKit.h
	PATHS
	/usr/include
	/usr/local/include
	/usr/include/GNUstep
	/usr/local/include/GNUstep
)

find_library(LIBGNUSTEPGUI_LIBRARY
	NAMES libgnustep-gui.so
	PATHS /usr/lib /usr/local/lib
)

if (LIBGNUSTEPGUI_INCLUDE_DIR AND LIBGNUSTEPGUI_LIBRARY)
	set(LIBGNUSTEPGUI_FOUND TRUE)
	set(LIBGNUSTEPGUI_LIBRARIES ${LIBGNUSTEPGUI_LIBRARY})
else (LIBGNUSTEPGUI_INCLUDE_DIR AND LIBGNUSTEPGUI_LIBRARY)
	set(LIBGNUSTEPGUI_FOUND FALSE)
endif (LIBGNUSTEPGUI_INCLUDE_DIR AND LIBGNUSTEPGUI_LIBRARY)

