
find_path(LIBGNUSTEPCOREBASE_INCLUDE_DIR CoreFoundation/CFString.h
	PATHS
	/usr/include
	/usr/local/include
	/usr/include/GNUstep
	/usr/local/include/GNUstep
)

find_library(LIBGNUSTEPCOREBASE_LIBRARY
	NAMES libgnustep-corebase.so
	PATHS /usr/lib /usr/local/lib
)

if (LIBGNUSTEPCOREBASE_INCLUDE_DIR AND LIBGNUSTEPCOREBASE_LIBRARY)
	set(LIBGNUSTEPCOREBASE_FOUND TRUE)
	set(LIBGNUSTEPCOREBASE_LIBRARIES ${LIBGNUSTEPCOREBASE_LIBRARY})
else (LIBGNUSTEPCOREBASE_INCLUDE_DIR AND LIBGNUSTEPCOREBASE_LIBRARY)
	set(LIBGNUSTEPCOREBASE_FOUND FALSE)
endif (LIBGNUSTEPCOREBASE_INCLUDE_DIR AND LIBGNUSTEPCOREBASE_LIBRARY)

