SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR "i686")

SET(CMAKE_C_COMPILER clang)
SET(CMAKE_CXX_COMPILER clang++)

SET(BITS 32)
set(CMAKE_PLATFORM_HAS_INSTALLNAME 1)

if (EXISTS "/etc/debian_version")
	SET (CMAKE_INSTALL_LIBDIR "lib/${CMAKE_LIBRARY_ARCHITECTURE}")
else (EXISTS "/etc/debian_version")
	SET (CMAKE_INSTALL_LIBDIR "lib32")
endif (EXISTS "/etc/debian_version")

