SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR "x86-64")

SET(CMAKE_C_COMPILER clang)
SET(CMAKE_CXX_COMPILER clang++)
SET(BITS 64)
set(CMAKE_PLATFORM_HAS_INSTALLNAME 1) # To fix ninja install

if (EXISTS "/etc/debian_version")
	SET (CMAKE_INSTALL_LIBDIR "lib/${CMAKE_LIBRARY_ARCHITECTURE}")
else (EXISTS "/etc/debian_version")
	SET (CMAKE_INSTALL_LIBDIR "lib64")
endif (EXISTS "/etc/debian_version")

