.\" Copyright (c) 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" This code is derived from software contributed to Berkeley by
.\" the American National Standards Committee X3, on Information
.\" Processing Systems.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)atoi.3	8.1 (Berkeley) 6/4/93
.\" $FreeBSD: src/lib/libc/stdlib/atoi.3,v 1.14 2007/10/19 06:23:39 davidxu Exp $
.\"
.Dd June 4, 1993
.Dt ATOI 3
.Os
.Sh NAME
.Nm atoi ,
.Nm atoi_l
.Nd convert
.Tn ASCII
string to integer
.Sh LIBRARY
.Lb libc
.Sh SYNOPSIS
.In stdlib.h
.Ft int
.Fn atoi "const char *str"
.In xlocale.h
.Ft int
.Fn atoi_l "const char *str" "locale_t loc"
.Sh DESCRIPTION
The
.Fn atoi
function converts the initial portion of the string pointed to by
.Fa str
to
.Vt int
representation.
.Pp
It is equivalent to:
.Bd -literal -offset indent
(int)strtol(str, (char **)NULL, 10);
.Ed
.Pp
While the
.Fn atoi
function uses the current locale, the
.Fn atoi_l
function may be passed a locale directly. See
.Xr xlocale 3
for more information.
.Sh IMPLEMENTATION NOTES
The
.Fn atoi
and
.Fn atoi_l
functions are thread-safe and async-cancel-safe.
.Pp
The
.Fn strtol
and
.Fn strtol_l
functions are recommended instead of 
.Fn atoi
and
.Fn atoi_l
functions, especially in new code.
.Sh ERRORS
The function
.Fn atoi
need not affect the value of
.Va errno
on an error.
.Sh SEE ALSO
.Xr atof 3 ,
.Xr atol 3 ,
.Xr strtod 3 ,
.Xr strtol 3 ,
.Xr strtoul 3 ,
.Xr xlocale 3
.Sh STANDARDS
The
.Fn atoi
function conforms to
.St -p1003.1-90 ,
.St -isoC ,
and
.St -isoC-99 .
