.Dd February 2, 2005
.Dt launchproxy 8 
.Os Darwin
.Sh NAME
.Nm launchproxy
.Nd inetd job emulation helper
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm 
handles the inetd emulation for
.Nm launchd .
This program may be merged into
.Nm launchd
in the future.
.Sh SEE ALSO 
.Xr launchctl 1 ,
.Xr launchd.plist 5 ,
.Xr launchd 8
