/*
 This file is part of Darling.

 Copyright (C) 2019 Lubos Dolezel

 Darling is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Darling is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Darling.  If not, see <http://www.gnu.org/licenses/>.
*/


#ifndef _CloudKit_H_
#define _CloudKit_H_

#import <Foundation/Foundation.h>

#import <CloudKit/APSConnectionDelegate.h>
#import <CloudKit/C2RequestDelegate.h>
#import <CloudKit/CKAssetRepairSchedulerDelegate.h>
#import <CloudKit/CKDCancelling.h>
#import <CloudKit/CKObjectValidating.h>
#import <CloudKit/CKPropertyCoding.h>
#import <CloudKit/CKRecordKeyValueSetting.h>
#import <CloudKit/CKRecordValue.h>
#import <CloudKit/CKSQLiteDelegate.h>
#import <CloudKit/CKSQLiteItem.h>
#import <CloudKit/CKShortDescription.h>
#import <CloudKit/CKSyncEngineDataSource.h>
#import <CloudKit/CKSyncEngineDataSourcePrivate.h>
#import <CloudKit/CKXPCClient.h>
#import <CloudKit/CKXPCDaemon.h>
#import <CloudKit/CKXPCDiscretionaryClient.h>
#import <CloudKit/CKXPCDiscretionaryDaemon.h>
#import <CloudKit/CKXPCSuitableString.h>
#import <CloudKit/PKPushRegistryDelegate.h>
#import <CloudKit/CKFlowControl.h>
#import <CloudKit/CKRecordZoneID.h>
#import <CloudKit/CKRepairAssetsOperation.h>
#import <CloudKit/CKRepairAssetsOperationInfo.h>
#import <CloudKit/CKDPRecordFieldValueEncryptedValue.h>
#import <CloudKit/CKUserNotificationUtilities.h>
#import <CloudKit/CKUploadRequestPersistentStore.h>
#import <CloudKit/CKMarkAssetBrokenOperation.h>
#import <CloudKit/CKMarkAssetBrokenOperationInfo.h>
#import <CloudKit/CKLogFacilityWrapper.h>
#import <CloudKit/CKModifyRecordZonesOperation.h>
#import <CloudKit/CKModifyRecordZonesOperationInfo.h>
#import <CloudKit/CKDiscoverAllContactsOperation.h>
#import <CloudKit/CKContainerSetupInfo.h>
#import <CloudKit/CKContainerOptions.h>
#import <CloudKit/CKAccountInfo.h>
#import <CloudKit/CKContainerXPCProxy.h>
#import <CloudKit/CKContainer.h>
#import <CloudKit/CKSyncEngineBatch.h>
#import <CloudKit/CKArchiveRecordsOperation.h>
#import <CloudKit/CKArchiveRecordsOperationInfo.h>
#import <CloudKit/CKQuery.h>
#import <CloudKit/CKNotificationListener.h>
#import <CloudKit/CKSubscriptionInfo.h>
#import <CloudKit/CKRepairZonePCSOperationInfo.h>
#import <CloudKit/CKRepairZonePCSOperation.h>
#import <CloudKit/CKDPRecordReference.h>
#import <CloudKit/CKException.h>
#import <CloudKit/CKSQLitePool.h>
#import <CloudKit/CKAutoBugCaptureMetadata.h>
#import <CloudKit/CKDCancelToken.h>
#import <CloudKit/CKFetchRecordZonesOperation.h>
#import <CloudKit/CKFetchRecordZonesOperationInfo.h>
#import <CloudKit/CKScheduler.h>
#import <CloudKit/CKDiscoverAllUserIdentitiesOperation.h>
#import <CloudKit/CKZonePCSDiagnosticInformation.h>
#import <CloudKit/CKPCSDiagnosticInformation.h>
#import <CloudKit/CKFetchShareMetadataOperation.h>
#import <CloudKit/CKFetchShareMetadataOperationInfo.h>
#import <CloudKit/CKSyncingClientInfo.h>
#import <CloudKit/CKSyncRequestOperation.h>
#import <CloudKit/CKModifyWebSharingOperation.h>
#import <CloudKit/CKModifyWebSharingOperationInfo.h>
#import <CloudKit/CKContainerID.h>
#import <CloudKit/CKLegacyPredicateValidator.h>
#import <CloudKit/CKSQLite.h>
#import <CloudKit/CKSQLiteError.h>
#import <CloudKit/CKAccountOverrideInfo.h>
#import <CloudKit/CKUserIdentity.h>
#import <CloudKit/CKSyncEngine.h>
#import <CloudKit/CKFetchDatabaseChangesOperation.h>
#import <CloudKit/CKFetchDatabaseChangesOperationInfo.h>
#import <CloudKit/CKFetchDatabaseChangesOperationResult.h>
#import <CloudKit/CKOperationFlowControlInfo.h>
#import <CloudKit/CKOperationFlowControlManager.h>
#import <CloudKit/CKPackageDB.h>
#import <CloudKit/CKPackageSection.h>
#import <CloudKit/CKDPRecordZoneIdentifier.h>
#import <CloudKit/CKApplicationPermissionGroup.h>
#import <CloudKit/CKUploadRequestManager.h>
#import <CloudKit/CKUploadRequestManagerInternals.h>
#import <CloudKit/CKUploadRequestManagerResponseActionThrottlerMetadata.h>
#import <CloudKit/CKUploadRequestManagerResponseActionThrottler.h>
#import <CloudKit/CKMarkNotificationsReadOperation.h>
#import <CloudKit/CKMarkNotificationsReadOperationInfo.h>
#import <CloudKit/CKFetchArchivedRecordsOperation.h>
#import <CloudKit/CKFetchArchivedRecordsOptions.h>
#import <CloudKit/CKFetchArchivedRecordsOperationInfo.h>
#import <CloudKit/CKDPStreamingAssetFooter.h>
#import <CloudKit/CKRecordValueStore.h>
#import <CloudKit/CKEncryptedRecordValueStore.h>
#import <CloudKit/CKRecord.h>
#import <CloudKit/CKContactsSupport.h>
#import <CloudKit/CKFileOpenInfo.h>
#import <CloudKit/CKFileOpenResult.h>
#import <CloudKit/CKFileMetadata.h>
#import <CloudKit/CKAssetTransferOptions.h>
#import <CloudKit/CKAssetReuploadExpectedProperties.h>
#import <CloudKit/CKAssetCopyInfo.h>
#import <CloudKit/CKAssetRereferenceInfo.h>
#import <CloudKit/CKAssetReference.h>
#import <CloudKit/CKAsset.h>
#import <CloudKit/CKSchedulerActivity.h>
#import <CloudKit/CKDiscretionaryOptions.h>
#import <CloudKit/CKDPRecordIdentifier.h>
#import <CloudKit/CKUserIdentityLookupInfo.h>
#import <CloudKit/CKDeviceToDeviceShareInvitationToken.h>
#import <CloudKit/CKShare.h>
#import <CloudKit/CKBehaviorOptions.h>
#import <CloudKit/CKPlaceholderOperation.h>
#import <CloudKit/CKOperation.h>
#import <CloudKit/CKOperationConfiguration.h>
#import <CloudKit/CKOperationInfo.h>
#import <CloudKit/CKOperationResult.h>
#import <CloudKit/CKOperationMMCSRequestOptions.h>
#import <CloudKit/CKDatabaseOperation.h>
#import <CloudKit/CKDatabaseOperationInfo.h>
#import <CloudKit/CKObjCClass.h>
#import <CloudKit/CKAssetRepairScheduler.h>
#import <CloudKit/CKRequestAssetOperation.h>
#import <CloudKit/CKQueryOperation.h>
#import <CloudKit/CKQueryOperationInfo.h>
#import <CloudKit/CKQueryOperationResult.h>
#import <CloudKit/CKQueryCursor.h>
#import <CloudKit/CKUploadRequestManagerStateMachine.h>
#import <CloudKit/CKShareParticipant.h>
#import <CloudKit/CKDiscoveredUserInfo.h>
#import <CloudKit/CKRecordGraphNode.h>
#import <CloudKit/CKRecordGraph.h>
#import <CloudKit/CKFetchNotificationChangesOperation.h>
#import <CloudKit/CKFetchNotificationChangesOperationInfo.h>
#import <CloudKit/CKFetchNotificationChangesOperationResult.h>
#import <CloudKit/CKFetchWebAuthTokenOperation.h>
#import <CloudKit/CKFetchWebAuthTokenOperationResult.h>
#import <CloudKit/CKFetchWebAuthTokenOperationInfo.h>
#import <CloudKit/CKFetchRecordVersionsOperation.h>
#import <CloudKit/CKFetchRecordVersionsOperationInfo.h>
#import <CloudKit/CKInitiateParticipantVettingOperation.h>
#import <CloudKit/CKInitiateParticipantVettingOperationInfo.h>
#import <CloudKit/CKStreamingAssetAppendContext.h>
#import <CloudKit/CKDPDate.h>
#import <CloudKit/CKAggregateZonePCSOperation.h>
#import <CloudKit/CKAggregateZonePCSOperationInfo.h>
#import <CloudKit/CKMetric.h>
#import <CloudKit/CKOperationMetrics.h>
#import <CloudKit/CKPackageItem.h>
#import <CloudKit/CKFetchRecordChangesOperation.h>
#import <CloudKit/CKFetchRecordChangesOperationResult.h>
#import <CloudKit/CKNotificationID.h>
#import <CloudKit/CKNotification.h>
#import <CloudKit/CKQueryNotification.h>
#import <CloudKit/CKRecordZoneNotification.h>
#import <CloudKit/CKDatabaseNotification.h>
#import <CloudKit/CKDatabase.h>
#import <CloudKit/CKAcceptSharesOperation.h>
#import <CloudKit/CKAcceptSharesOperationInfo.h>
#import <CloudKit/CKReference.h>
#import <CloudKit/CKFetchShareParticipantKeyOperation.h>
#import <CloudKit/CKFetchShareParticipantKeyOperationInfo.h>
#import <CloudKit/CKAPSMachServiceConnectionKey.h>
#import <CloudKit/CKAPSMachServiceConnectionDelegate.h>
#import <CloudKit/CKOperationGroup.h>
#import <CloudKit/CKOperationGroupSystemImposedInfoConfiguration.h>
#import <CloudKit/CKOperationGroupSystemImposedInfo.h>
#import <CloudKit/CKPublicKey.h>
#import <CloudKit/CKDPLocationCoordinate.h>
#import <CloudKit/CKDPIdentifier.h>
#import <CloudKit/CKSyncEngineFetchChangesOperation.h>
#import <CloudKit/CKEncryptedData.h>
#import <CloudKit/CKEncryptedString.h>
#import <CloudKit/CKEncryptedLongLong.h>
#import <CloudKit/CKEncryptedDouble.h>
#import <CloudKit/CKEncryptedDate.h>
#import <CloudKit/CKEncryptedReference.h>
#import <CloudKit/CKEncryptedLocation.h>
#import <CloudKit/CKEncryptedStringArray.h>
#import <CloudKit/CKEncryptedDoubleArray.h>
#import <CloudKit/CKEncryptedLongLongArray.h>
#import <CloudKit/CKEncryptedDateArray.h>
#import <CloudKit/CKEncryptedLocationArray.h>
#import <CloudKit/CKEncryptedEmptyArray.h>
#import <CloudKit/CKSQLiteStatementEnumerator.h>
#import <CloudKit/CKSyncEngineModifyRecordBatchesOperation.h>
#import <CloudKit/CKObjCProperty.h>
#import <CloudKit/CKQuerySubscription.h>
#import <CloudKit/CKRecordZoneSubscription.h>
#import <CloudKit/CKDatabaseSubscription.h>
#import <CloudKit/CKSubscription.h>
#import <CloudKit/CKNotificationInfo.h>
#import <CloudKit/CKModifySubscriptionsOperation.h>
#import <CloudKit/CKModifySubscriptionsOperationInfo.h>
#import <CloudKit/CKFetchRecordZoneChangesOperation.h>
#import <CloudKit/CKFetchRecordZoneChangesOptions.h>
#import <CloudKit/CKFetchRecordZoneChangesConfiguration.h>
#import <CloudKit/CKFetchRecordZoneChangesOperationInfo.h>
#import <CloudKit/CKModifyRecordsOperation.h>
#import <CloudKit/CKModifyRecordsOperationInfo.h>
#import <CloudKit/CKAssetDownloadPreauthorization.h>
#import <CloudKit/CKSignatureGenerator.h>
#import <CloudKit/CKSQLiteStatement.h>
#import <CloudKit/CKAssetRepairOperationUtilities.h>
#import <CloudKit/CKUploadRequestConfiguration.h>
#import <CloudKit/CKPublishAssetsOperation.h>
#import <CloudKit/CKPublishAssetsOperationInfo.h>
#import <CloudKit/CKCompleteParticipantVettingOperation.h>
#import <CloudKit/CKCompleteParticipantVettingOperationInfo.h>
#import <CloudKit/CKFetchSubscriptionsOperation.h>
#import <CloudKit/CKFetchSubscriptionsOperationInfo.h>
#import <CloudKit/CKLocationSortDescriptor.h>
#import <CloudKit/CKFetchRecordsAssetInfo.h>
#import <CloudKit/CKFetchRecordsOperation.h>
#import <CloudKit/CKFetchRecordsOperationInfo.h>
#import <CloudKit/CKPredicateValidatorInstance.h>
#import <CloudKit/CKRecursivePredicateValidator.h>
#import <CloudKit/CKAnyPredicateValidator.h>
#import <CloudKit/CKAllPredicateValidator.h>
#import <CloudKit/CKCompoundTypePredicateValidator.h>
#import <CloudKit/CKTruePredicateValidator.h>
#import <CloudKit/CKCompoundSubpredicateValidator.h>
#import <CloudKit/CKFlipFlopPredicateValidator.h>
#import <CloudKit/CKComparisonPredicateValidator.h>
#import <CloudKit/CKComparisonOperatorValidator.h>
#import <CloudKit/CKComparisonModifierValidator.h>
#import <CloudKit/CKComparisonOptionsValidator.h>
#import <CloudKit/CKConstantValueExpressionValidator.h>
#import <CloudKit/CKKeyPathExpressionValidator.h>
#import <CloudKit/CKAggregateExpressionValidator.h>
#import <CloudKit/CKFunctionExpressionValidator.h>
#import <CloudKit/CKEvaluatedObjectExpressionValidator.h>
#import <CloudKit/CKKindOfClassValidator.h>
#import <CloudKit/CKKindOfCollectionClassValidator.h>
#import <CloudKit/CKStringValueValidator.h>
#import <CloudKit/CKCustomBlockValidator.h>
#import <CloudKit/CKTrueValidator.h>
#import <CloudKit/CKNilValidator.h>
#import <CloudKit/CKDeclarativePredicateValidator.h>
#import <CloudKit/CKRequestInfo.h>
#import <CloudKit/CKBlockingAsyncQueue.h>
#import <CloudKit/CKCodeFunctionInvokeOperation.h>
#import <CloudKit/CKCodeFunctionInvokeOperationInfo.h>
#import <CloudKit/CKModifyRecordAccessOperation.h>
#import <CloudKit/CKModifyRecordAccessOperationInfo.h>
#import <CloudKit/CKShareMetadata.h>
#import <CloudKit/CKDiscoverUserInfosOperation.h>
#import <CloudKit/CKPackageDBDelegate.h>
#import <CloudKit/CKPackage.h>
#import <CloudKit/CKArchivedAnchoredPackage.h>
#import <CloudKit/CKObjCType.h>
#import <CloudKit/CKModifyBadgeOperation.h>
#import <CloudKit/CKModifyBadgeOperationInfo.h>
#import <CloudKit/CKUploadRequestMetadata.h>
#import <CloudKit/CKAssetUploadRequestMetadata.h>
#import <CloudKit/CKPackageUploadRequestMetadata.h>
#import <CloudKit/CKPredicateValidator.h>
#import <CloudKit/CKPrettyError.h>
#import <CloudKit/CKInternalError.h>
#import <CloudKit/CKSyncEngineMetadata.h>
#import <CloudKit/CKSyncEngineRecordModification.h>
#import <CloudKit/CKRecordID.h>
#import <CloudKit/CKRecordZone.h>
#import <CloudKit/CKStreamingAsset.h>
#import <CloudKit/CKFetchShareParticipantsOperation.h>
#import <CloudKit/CKFetchShareParticipantsOperationInfo.h>
#import <CloudKit/CKFetchUserQuotaOperation.h>
#import <CloudKit/CKFetchUserQuotaOperationResult.h>
#import <CloudKit/CKFetchWhitelistedBundleIDsOperation.h>
#import <CloudKit/CKFetchWhitelistedBundleIDsOperationResult.h>
#import <CloudKit/CKServerChangeToken.h>
#import <CloudKit/CKEventMetric.h>
#import <CloudKit/CKEventOperationInfo.h>
#import <CloudKit/CKEventOperationGroupInfo.h>
#import <CloudKit/CKEventMetricInfo.h>
#import <CloudKit/CKOperationCallbackManager.h>
#import <CloudKit/CKObject.h>
#import <CloudKit/CKDiscoverUserIdentitiesOperation.h>
#import <CloudKit/CKDiscoverUserIdentitiesOperationInfo.h>

void* CKAbsoluteHostTime(void);
void* CKAcceptablePredicateValueClasses(void);
void* CKAcceptableValueClasses(void);
void* CKAllClientEntitlementKeys(void);
void* CKAppIdentifierFromTeamAppTuple(void);
void* CKAutoBugCaptureReasonToString(void);
void* CKBoolFromCKTernary(void);
void* CKBuildVersion(void);
void* CKCFArrayForEach(void);
void* CKCFDictionaryForEach(void);
void* CKCanRetryForError(void);
void* CKContainerEnvironmentFromString(void);
void* CKContainerEnvironmentString(void);
void* CKContainerIdentifierIsAppleInternal(void);
void* CKCreateDirectoryAtPath(void);
void* CKCreateDirectoryAtPathWithAttributes(void);
void* CKCreateGUID(void);
void* CKCurrentProcessIsDaemon(void);
void* CKCurrentQueueIsMainQueue(void);
void* CKCurrentQueueQualityOfService(void);
void* CKCurrentThreadQualityOfService(void);
void* CKDPDateReadFrom(void);
void* CKDPIdentifierReadFrom(void);
void* CKDPLocationCoordinateReadFrom(void);
void* CKDPRecordFieldValueEncryptedValueReadFrom(void);
void* CKDPRecordIdentifierReadFrom(void);
void* CKDPRecordReferenceReadFrom(void);
void* CKDPRecordZoneIdentifierReadFrom(void);
void* CKDatabaseScopeFromString(void);
void* CKDatabaseScopeString(void);
void* CKDatasAreBothNilOrEqual(void);
void* CKDeviceID(void);
void* CKEarliestStartDateAfterError(void);
void* CKErrorChainFromError(void);
void* CKErrorChainStringFromError(void);
void* CKErrorCodeForInternalErrorCode(void);
void* CKErrorCodeForNSURLErrorCode(void);
void* CKErrorIsCode(void);
void* CKFetchAPSEnvironmentFromServerOrEntitlements(void);
void* CKGetCurrentActivities(void);
void* CKGetGlobalQueue(void);
void* CKGetHomeDir(void);
void* CKGetHomeDirRealPath(void);
void* CKGetRealPath(void);
void* CKHexCharFromBytes(void);
void* CKIndexedArrayKey(void);
void* CKIsPCSError(void);
void* CKIsRunningInCloudD(void);
void* CKIsRunningInTestHost(void);
void* CKIsValidOperationForScope(void);
void* CKLinkCheck0fd6bdf95f2efb6e65813fd4cd0f5d9af656d08a(void);
void* CKLinkCheck5dbf91c3fd1d871f0bcfe60afeb451e3e708d350(void);
void* CKLinkCheck908c3403f5370f9fc0f790c790ce4de0669132c0(void);
void* CKLinkCheck92e3e8f8ec1a906754afb22d87eb36301b4f6760(void);
void* CKMainBundleIsAppleExecutable(void);
void* CKNSIndexSet_enumerateInverseRangesInRange_options_usingBlock(void);
void* CKNSIndexSet_indexSetWithInverseIndexSet(void);
void* CKNSQualityOfServiceFromQoSClass(void);
void* CKOperationGroupTransferSizeForBytes(void);
void* CKOperationLoggableProgressArguments(void);
void* CKOperationProgressCallbackClasses(void);
void* CKPIDIsStillAlive(void);
void* CKProcessIndexedArrayKey(void);
void* CKProductName(void);
void* CKProductType(void);
void* CKProductVersion(void);
void* CKQoSClassFromNSQualityOfService(void);
void* CKQoSIsBackground(void);
void* CKQualityOfServiceOrdering(void);
void* CKRetryAfterSecondsForError(void);
void* CKSDKVersion(void);
void* CKSQLiteJournalSuffixes(void);
void* CKServerEnvironmentFromString(void);
void* CKShareURLSlugForiWorkShareTitle(void);
void* CKSharingContainerSlugForContainerID(void);
void* CKShortRandomID(void);
void* CKShouldUseNewPredicateValidation(void);
void* CKShouldWrapErrorFetchingRecords(void);
void* CKStringForDiscretionaryNetworkBehavior(void);
void* CKStringForNetworkServiceType(void);
void* CKStringForQOS(void);
void* CKStringForTransferSize(void);
void* CKStringForXPCActivityState(void);
void* CKStringFromAccountChangeType(void);
void* CKStringFromAccountStatus(void);
void* CKStringFromApplicationPermissionStatus(void);
void* CKStringFromCKMMCSEncryptionSupport(void);
void* CKStringFromCapabilities(void);
void* CKStringFromDeviceToDeviceEncryptionStatus(void);
void* CKStringFromParticipantAcceptanceStatus(void);
void* CKStringFromParticipantInvitationTokenStatus(void);
void* CKStringFromParticipantPermission(void);
void* CKStringFromParticipantRole(void);
void* CKStringFromPartition(void);
void* CKStringFromServerEnvironment(void);
void* CKStringFromShareParticipantVisibility(void);
void* CKStringWithArray(void);
void* CKStringWithBytes(void);
void* CKStringWithData(void);
void* CKStringWithDate(void);
void* CKStringWithDictionary(void);
void* CKStringWithLimitedArray(void);
void* CKStringWithNibbles(void);
void* CKStringWithObject(void);
void* CKStringWithSet(void);
void* CKStringsAreBothNilOrEqual(void);
void* CKSyncEngineRecordModificationTypeOpposite(void);
void* CKTabIndentAtDepth(void);
void* CKTernaryFromBOOL(void);
void* CKTopLevelUnderlyingErrorCodes(void);
void* CKTriggerAutoBugCaptureWithFormatSignature(void);
void* CKTriggerClientSideAutoBugCaptureWithFormatSignature(void);
void* CKValidSharingURLHostnames(void);
void* CKValidateIndexedArrayKeys(void);
void* CKValidateKeyName(void);
void* CKValidateRecordArrayValue(void);
void* CKValueIsAcceptableClass(void);
void* CKValueIsAcceptablePredicateClass(void);
void* CKWarnForIncorrectServiceIdentity(void);
void* CKWarnForInvalidApplicationIdentifier(void);
void* CKWeakLinkClass(void);
void* CKWeakLinkSymbol(void);
void* CKXPCSuitableError(void);
void* NSTimeIntervalToClosestXPCActivityInterval(void);
void* _CKCheckArgument(void);
void* _CKSimulateCrash(void);
void* ck_call_or_dispatch_async_if_not_key(void);
void* ck_call_or_dispatch_sync_if_not_key(void);
void* ck_log_asl_level_to_type(void);
void* ck_log_facilities_initailize_static(void);
void* ck_log_get_asl_level(void);
void* mmapFileAtPath(void);
void* mmapFileDescriptor(void);
void* setCKIsRunningInCloudD(void);
void* setCKIsRunningInTestHost(void);
void* stringForCKErrorCode(void);

#endif
