/* Automatically generated file, do not edit */
#ifndef _h_fcns_c
#define _h_fcns_c
#define	ED_ARGUMENT_DIGIT             	  0
#define	ED_CLEAR_SCREEN               	  1
#define	ED_COMMAND                    	  2
#define	ED_DELETE_NEXT_CHAR           	  3
#define	ED_DELETE_PREV_CHAR           	  4
#define	ED_DELETE_PREV_WORD           	  5
#define	ED_DIGIT                      	  6
#define	ED_END_OF_FILE                	  7
#define	ED_INSERT                     	  8
#define	ED_KILL_LINE                  	  9
#define	ED_MOVE_TO_BEG                	 10
#define	ED_MOVE_TO_END                	 11
#define	ED_NEWLINE                    	 12
#define	ED_NEXT_CHAR                  	 13
#define	ED_NEXT_HISTORY               	 14
#define	ED_NEXT_LINE                  	 15
#define	ED_PREV_CHAR                  	 16
#define	ED_PREV_HISTORY               	 17
#define	ED_PREV_LINE                  	 18
#define	ED_PREV_WORD                  	 19
#define	ED_QUOTED_INSERT              	 20
#define	ED_REDISPLAY                  	 21
#define	ED_SEARCH_NEXT_HISTORY        	 22
#define	ED_SEARCH_PREV_HISTORY        	 23
#define	ED_SEQUENCE_LEAD_IN           	 24
#define	ED_START_OVER                 	 25
#define	ED_TRANSPOSE_CHARS            	 26
#define	ED_TTY_DSUSP                  	 27
#define	ED_TTY_FLUSH_OUTPUT           	 28
#define	ED_TTY_SIGINT                 	 29
#define	ED_TTY_SIGQUIT                	 30
#define	ED_TTY_SIGTSTP                	 31
#define	ED_TTY_START_OUTPUT           	 32
#define	ED_TTY_STOP_OUTPUT            	 33
#define	ED_UNASSIGNED                 	 34
#define	EM_CAPITOL_CASE               	 35
#define	EM_COPY_PREV_WORD             	 36
#define	EM_COPY_REGION                	 37
#define	EM_DELETE_NEXT_WORD           	 38
#define	EM_DELETE_OR_LIST             	 39
#define	EM_DELETE_PREV_CHAR           	 40
#define	EM_EXCHANGE_MARK              	 41
#define	EM_GOSMACS_TRANSPOSE          	 42
#define	EM_INC_SEARCH_NEXT            	 43
#define	EM_INC_SEARCH_PREV            	 44
#define	EM_KILL_LINE                  	 45
#define	EM_KILL_REGION                	 46
#define	EM_LOWER_CASE                 	 47
#define	EM_META_NEXT                  	 48
#define	EM_NEXT_WORD                  	 49
#define	EM_SET_MARK                   	 50
#define	EM_TOGGLE_OVERWRITE           	 51
#define	EM_UNIVERSAL_ARGUMENT         	 52
#define	EM_UPPER_CASE                 	 53
#define	EM_YANK                       	 54
#define	VI_ADD                        	 55
#define	VI_ADD_AT_EOL                 	 56
#define	VI_ALIAS                      	 57
#define	VI_CHANGE_CASE                	 58
#define	VI_CHANGE_META                	 59
#define	VI_CHANGE_TO_EOL              	 60
#define	VI_COMMAND_MODE               	 61
#define	VI_COMMENT_OUT                	 62
#define	VI_DELETE_META                	 63
#define	VI_DELETE_PREV_CHAR           	 64
#define	VI_END_BIG_WORD               	 65
#define	VI_END_WORD                   	 66
#define	VI_HISTEDIT                   	 67
#define	VI_HISTORY_WORD               	 68
#define	VI_INSERT                     	 69
#define	VI_INSERT_AT_BOL              	 70
#define	VI_KILL_LINE_PREV             	 71
#define	VI_LIST_OR_EOF                	 72
#define	VI_MATCH                      	 73
#define	VI_NEXT_BIG_WORD              	 74
#define	VI_NEXT_CHAR                  	 75
#define	VI_NEXT_WORD                  	 76
#define	VI_PASTE_NEXT                 	 77
#define	VI_PASTE_PREV                 	 78
#define	VI_PREV_BIG_WORD              	 79
#define	VI_PREV_CHAR                  	 80
#define	VI_PREV_WORD                  	 81
#define	VI_REDO                       	 82
#define	VI_REPEAT_NEXT_CHAR           	 83
#define	VI_REPEAT_PREV_CHAR           	 84
#define	VI_REPEAT_SEARCH_NEXT         	 85
#define	VI_REPEAT_SEARCH_PREV         	 86
#define	VI_REPLACE_CHAR               	 87
#define	VI_REPLACE_MODE               	 88
#define	VI_SEARCH_NEXT                	 89
#define	VI_SEARCH_PREV                	 90
#define	VI_SUBSTITUTE_CHAR            	 91
#define	VI_SUBSTITUTE_LINE            	 92
#define	VI_TO_COLUMN                  	 93
#define	VI_TO_HISTORY_LINE            	 94
#define	VI_TO_NEXT_CHAR               	 95
#define	VI_TO_PREV_CHAR               	 96
#define	VI_UNDO                       	 97
#define	VI_UNDO_LINE                  	 98
#define	VI_YANK                       	 99
#define	VI_YANK_END                   	100
#define	VI_ZERO                       	101
#define	EL_NUM_FCNS                   	102
#define	EL_EOF                   	255
typedef el_action_t (*el_func_t)(EditLine *, Int);
protected const el_func_t* func__get(void);
#endif /* _h_fcns_c */
