/* Automatically generated file, do not edit */
#include "config.h"
#include "el.h"
#include "chartype.h"
private const struct el_bindings_t el_func_help[] = {
    { STR("vi-paste-next"),          VI_PASTE_NEXT,                
      STR("Vi paste previous deletion to the right of the cursor") },
    { STR("vi-paste-prev"),          VI_PASTE_PREV,                
      STR("Vi paste previous deletion to the left of the cursor") },
    { STR("vi-prev-big-word"),       VI_PREV_BIG_WORD,             
      STR("Vi move to the previous space delimited word") },
    { STR("vi-prev-word"),           VI_PREV_WORD,                 
      STR("Vi move to the previous word") },
    { STR("vi-next-big-word"),       VI_NEXT_BIG_WORD,             
      STR("Vi move to the next space delimited word") },
    { STR("vi-next-word"),           VI_NEXT_WORD,                 
      STR("Vi move to the next word") },
    { STR("vi-change-case"),         VI_CHANGE_CASE,               
      STR("Vi change case of character under the cursor and advance one character") },
    { STR("vi-change-meta"),         VI_CHANGE_META,               
      STR("Vi change prefix command") },
    { STR("vi-insert-at-bol"),       VI_INSERT_AT_BOL,             
      STR("Vi enter insert mode at the beginning of line") },
    { STR("vi-replace-char"),        VI_REPLACE_CHAR,              
      STR("Vi replace character under the cursor with the next character typed") },
    { STR("vi-replace-mode"),        VI_REPLACE_MODE,              
      STR("Vi enter replace mode") },
    { STR("vi-substitute-char"),     VI_SUBSTITUTE_CHAR,           
      STR("Vi replace character under the cursor and enter insert mode") },
    { STR("vi-substitute-line"),     VI_SUBSTITUTE_LINE,           
      STR("Vi substitute entire line") },
    { STR("vi-change-to-eol"),       VI_CHANGE_TO_EOL,             
      STR("Vi change to end of line") },
    { STR("vi-insert"),              VI_INSERT,                    
      STR("Vi enter insert mode") },
    { STR("vi-add"),                 VI_ADD,                       
      STR("Vi enter insert mode after the cursor") },
    { STR("vi-add-at-eol"),          VI_ADD_AT_EOL,                
      STR("Vi enter insert mode at end of line") },
    { STR("vi-delete-meta"),         VI_DELETE_META,               
      STR("Vi delete prefix command") },
    { STR("vi-end-big-word"),        VI_END_BIG_WORD,              
      STR("Vi move to the end of the current space delimited word") },
    { STR("vi-end-word"),            VI_END_WORD,                  
      STR("Vi move to the end of the current word") },
    { STR("vi-undo"),                VI_UNDO,                      
      STR("Vi undo last change") },
    { STR("vi-command-mode"),        VI_COMMAND_MODE,              
      STR("Vi enter command mode (use alternative key bindings)") },
    { STR("vi-zero"),                VI_ZERO,                      
      STR("Vi move to the beginning of line") },
    { STR("vi-delete-prev-char"),    VI_DELETE_PREV_CHAR,          
      STR("Vi move to previous character (backspace)") },
    { STR("vi-list-or-eof"),         VI_LIST_OR_EOF,               
      STR("Vi list choices for completion or indicate end of file if empty line") },
    { STR("vi-kill-line-prev"),      VI_KILL_LINE_PREV,            
      STR("Vi cut from beginning of line to cursor") },
    { STR("vi-search-prev"),         VI_SEARCH_PREV,               
      STR("Vi search history previous") },
    { STR("vi-search-next"),         VI_SEARCH_NEXT,               
      STR("Vi search history next") },
    { STR("vi-repeat-search-next"),  VI_REPEAT_SEARCH_NEXT,        
      STR("Vi repeat current search in the same search direction") },
    { STR("vi-repeat-search-prev"),  VI_REPEAT_SEARCH_PREV,        
      STR("Vi repeat current search in the opposite search direction") },
    { STR("vi-next-char"),           VI_NEXT_CHAR,                 
      STR("Vi move to the character specified next") },
    { STR("vi-prev-char"),           VI_PREV_CHAR,                 
      STR("Vi move to the character specified previous") },
    { STR("vi-to-next-char"),        VI_TO_NEXT_CHAR,              
      STR("Vi move up to the character specified next") },
    { STR("vi-to-prev-char"),        VI_TO_PREV_CHAR,              
      STR("Vi move up to the character specified previous") },
    { STR("vi-repeat-next-char"),    VI_REPEAT_NEXT_CHAR,          
      STR("Vi repeat current character search in the same search direction") },
    { STR("vi-repeat-prev-char"),    VI_REPEAT_PREV_CHAR,          
      STR("Vi repeat current character search in the opposite search direction") },
    { STR("vi-match"),               VI_MATCH,                     
      STR("Vi go to matching () {} or []") },
    { STR("vi-undo-line"),           VI_UNDO_LINE,                 
      STR("Vi undo all changes to line") },
    { STR("vi-to-column"),           VI_TO_COLUMN,                 
      STR("Vi go to specified column") },
    { STR("vi-yank-end"),            VI_YANK_END,                  
      STR("Vi yank to end of line") },
    { STR("vi-yank"),                VI_YANK,                      
      STR("Vi yank") },
    { STR("vi-comment-out"),         VI_COMMENT_OUT,               
      STR("Vi comment out current command") },
    { STR("vi-alias"),               VI_ALIAS,                     
      STR("Vi include shell alias") },
    { STR("vi-to-history-line"),     VI_TO_HISTORY_LINE,           
      STR("Vi go to specified history file line.") },
    { STR("vi-histedit"),            VI_HISTEDIT,                  
      STR("Vi edit history line with vi") },
    { STR("vi-history-word"),        VI_HISTORY_WORD,              
      STR("Vi append word from previous input line") },
    { STR("vi-redo"),                VI_REDO,                      
      STR("Vi redo last non-motion command") },
    { STR("em-delete-or-list"),      EM_DELETE_OR_LIST,            
      STR("Delete character under cursor or list completions if at end of line") },
    { STR("em-delete-next-word"),    EM_DELETE_NEXT_WORD,          
      STR("Cut from cursor to end of current word") },
    { STR("em-yank"),                EM_YANK,                      
      STR("Paste cut buffer at cursor position") },
    { STR("em-kill-line"),           EM_KILL_LINE,                 
      STR("Cut the entire line and save in cut buffer") },
    { STR("em-kill-region"),         EM_KILL_REGION,               
      STR("Cut area between mark and cursor and save in cut buffer") },
    { STR("em-copy-region"),         EM_COPY_REGION,               
      STR("Copy area between mark and cursor to cut buffer") },
    { STR("em-gosmacs-transpose"),   EM_GOSMACS_TRANSPOSE,         
      STR("Exchange the two characters before the cursor") },
    { STR("em-next-word"),           EM_NEXT_WORD,                 
      STR("Move next to end of current word") },
    { STR("em-upper-case"),          EM_UPPER_CASE,                
      STR("Uppercase the characters from cursor to end of current word") },
    { STR("em-capitol-case"),        EM_CAPITOL_CASE,              
      STR("Capitalize the characters from cursor to end of current word") },
    { STR("em-lower-case"),          EM_LOWER_CASE,                
      STR("Lowercase the characters from cursor to end of current word") },
    { STR("em-set-mark"),            EM_SET_MARK,                  
      STR("Set the mark at cursor") },
    { STR("em-exchange-mark"),       EM_EXCHANGE_MARK,             
      STR("Exchange the cursor and mark") },
    { STR("em-universal-argument"),  EM_UNIVERSAL_ARGUMENT,        
      STR("Universal argument (argument times 4)") },
    { STR("em-meta-next"),           EM_META_NEXT,                 
      STR("Add 8th bit to next character typed") },
    { STR("em-toggle-overwrite"),    EM_TOGGLE_OVERWRITE,          
      STR("Switch from insert to overwrite mode or vice versa") },
    { STR("em-copy-prev-word"),      EM_COPY_PREV_WORD,            
      STR("Copy current word to cursor") },
    { STR("em-inc-search-next"),     EM_INC_SEARCH_NEXT,           
      STR("Emacs incremental next search") },
    { STR("em-inc-search-prev"),     EM_INC_SEARCH_PREV,           
      STR("Emacs incremental reverse search") },
    { STR("em-delete-prev-char"),    EM_DELETE_PREV_CHAR,          
      STR("Delete the character to the left of the cursor") },
    { STR("ed-end-of-file"),         ED_END_OF_FILE,               
      STR("Indicate end of file") },
    { STR("ed-insert"),              ED_INSERT,                    
      STR("Add character to the line") },
    { STR("ed-delete-prev-word"),    ED_DELETE_PREV_WORD,          
      STR("Delete from beginning of current word to cursor") },
    { STR("ed-delete-next-char"),    ED_DELETE_NEXT_CHAR,          
      STR("Delete character under cursor") },
    { STR("ed-kill-line"),           ED_KILL_LINE,                 
      STR("Cut to the end of line") },
    { STR("ed-move-to-end"),         ED_MOVE_TO_END,               
      STR("Move cursor to the end of line") },
    { STR("ed-move-to-beg"),         ED_MOVE_TO_BEG,               
      STR("Move cursor to the beginning of line") },
    { STR("ed-transpose-chars"),     ED_TRANSPOSE_CHARS,           
      STR("Exchange the character to the left of the cursor with the one under it") },
    { STR("ed-next-char"),           ED_NEXT_CHAR,                 
      STR("Move to the right one character") },
    { STR("ed-prev-word"),           ED_PREV_WORD,                 
      STR("Move to the beginning of the current word") },
    { STR("ed-prev-char"),           ED_PREV_CHAR,                 
      STR("Move to the left one character") },
    { STR("ed-quoted-insert"),       ED_QUOTED_INSERT,             
      STR("Add the next character typed verbatim") },
    { STR("ed-digit"),               ED_DIGIT,                     
      STR("Adds to argument or enters a digit") },
    { STR("ed-argument-digit"),      ED_ARGUMENT_DIGIT,            
      STR("Digit that starts argument") },
    { STR("ed-unassigned"),          ED_UNASSIGNED,                
      STR("Indicates unbound character") },
    { STR("ed-tty-sigint"),          ED_TTY_SIGINT,                
      STR("Tty interrupt character") },
    { STR("ed-tty-dsusp"),           ED_TTY_DSUSP,                 
      STR("Tty delayed suspend character") },
    { STR("ed-tty-flush-output"),    ED_TTY_FLUSH_OUTPUT,          
      STR("Tty flush output characters") },
    { STR("ed-tty-sigquit"),         ED_TTY_SIGQUIT,               
      STR("Tty quit character") },
    { STR("ed-tty-sigtstp"),         ED_TTY_SIGTSTP,               
      STR("Tty suspend character") },
    { STR("ed-tty-stop-output"),     ED_TTY_STOP_OUTPUT,           
      STR("Tty disallow output characters") },
    { STR("ed-tty-start-output"),    ED_TTY_START_OUTPUT,          
      STR("Tty allow output characters") },
    { STR("ed-newline"),             ED_NEWLINE,                   
      STR("Execute command") },
    { STR("ed-delete-prev-char"),    ED_DELETE_PREV_CHAR,          
      STR("Delete the character to the left of the cursor") },
    { STR("ed-clear-screen"),        ED_CLEAR_SCREEN,              
      STR("Clear screen leaving current line at the top") },
    { STR("ed-redisplay"),           ED_REDISPLAY,                 
      STR("Redisplay everything") },
    { STR("ed-start-over"),          ED_START_OVER,                
      STR("Erase current line and start from scratch") },
    { STR("ed-sequence-lead-in"),    ED_SEQUENCE_LEAD_IN,          
      STR("First character in a bound sequence") },
    { STR("ed-prev-history"),        ED_PREV_HISTORY,              
      STR("Move to the previous history line") },
    { STR("ed-next-history"),        ED_NEXT_HISTORY,              
      STR("Move to the next history line") },
    { STR("ed-search-prev-history"), ED_SEARCH_PREV_HISTORY,       
      STR("Search previous in history for a line matching the current") },
    { STR("ed-search-next-history"), ED_SEARCH_NEXT_HISTORY,       
      STR("Search next in history for a line matching the current") },
    { STR("ed-prev-line"),           ED_PREV_LINE,                 
      STR("Move up one line") },
    { STR("ed-next-line"),           ED_NEXT_LINE,                 
      STR("Move down one line") },
    { STR("ed-command"),             ED_COMMAND,                   
      STR("Editline extended command") },
};

protected const el_bindings_t* help__get(void){ return el_func_help; }
