/*
 This file is part of Darling.

 Copyright (C) 2019 Lubos Dolezel

 Darling is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Darling is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Darling.  If not, see <http://www.gnu.org/licenses/>.
*/


#ifndef _AddressBook_H_
#define _AddressBook_H_

#import <Foundation/Foundation.h>

#import <AddressBook/ABAccessoryViewProvider.h>
#import <AddressBook/ABActionDelegate.h>
#import <AddressBook/ABActionManagerDelegate.h>
#import <AddressBook/ABBookStateSaving.h>
#import <AddressBook/ABCardCollectionRowView.h>
#import <AddressBook/ABCardCollectionViewDataSource.h>
#import <AddressBook/ABCardCollectionViewDelegate.h>
#import <AddressBook/ABCardCollectionViewPresentation.h>
#import <AddressBook/ABCardCollectionViewPresentationDelegate.h>
#import <AddressBook/ABCardViewActionDataSource.h>
#import <AddressBook/ABCardViewDataSource.h>
#import <AddressBook/ABCardViewDataSourceProvider.h>
#import <AddressBook/ABCardViewImageDataSource.h>
#import <AddressBook/ABCardViewMultiValue.h>
#import <AddressBook/ABCardViewMultiValueConverter.h>
#import <AddressBook/ABCardViewMultiValueTransformer.h>
#import <AddressBook/ABCardViewMutableMultiValue.h>
#import <AddressBook/ABCardViewProperty.h>
#import <AddressBook/ABCollectionAction.h>
#import <AddressBook/ABCollectionItemMessagingAvailabilityHelperDelegate.h>
#import <AddressBook/ABCollectionMultiPropertyAction.h>
#import <AddressBook/ABCommand.h>
#import <AddressBook/ABCommandExecutor.h>
#import <AddressBook/ABCommandVisitor.h>
#import <AddressBook/ABContactSearching.h>
#import <AddressBook/ABDateProvider.h>
#import <AddressBook/ABFaceTimeCommunicationsBridgeDelegate.h>
#import <AddressBook/ABFaceTimeDataSource.h>
#import <AddressBook/ABGroupEntriesFactory.h>
#import <AddressBook/ABGroupHelperFactory.h>
#import <AddressBook/ABGroupListRowView.h>
#import <AddressBook/ABGroupListStyleProvider.h>
#import <AddressBook/ABGroupSelectHelper.h>
#import <AddressBook/ABKeyValueCoding.h>
#import <AddressBook/ABMainWindowGroupListCellView.h>
#import <AddressBook/ABMutableKeyValueCoding.h>
#import <AddressBook/ABNameView.h>
#import <AddressBook/ABNameViewCompanyCheckBoxDelegate.h>
#import <AddressBook/ABNameViewDataSource.h>
#import <AddressBook/ABNoteTextViewDelegate.h>
#import <AddressBook/ABPasteboardData.h>
#import <AddressBook/ABPeoplePickerTableViewDataSource.h>
#import <AddressBook/ABPeoplePickerTableViewDelegate.h>
#import <AddressBook/ABPersonListControllerProtocol.h>
#import <AddressBook/ABPersonListDelegate.h>
#import <AddressBook/ABPersonListHeadlining.h>
#import <AddressBook/ABPersonSearchControllerDelegate.h>
#import <AddressBook/ABPersonViewClientProtocol.h>
#import <AddressBook/ABPersonViewProtocol.h>
#import <AddressBook/ABPopUpButtonDelegate.h>
#import <AddressBook/ABRTTServices.h>
#import <AddressBook/ABRecordContext.h>
#import <AddressBook/ABSaveRequestCommand.h>
#import <AddressBook/ABSearchElementOrderManagerProtocol.h>
#import <AddressBook/ABSearchElementRepresentationBuilder.h>
#import <AddressBook/ABSearchOperationsFactory.h>
#import <AddressBook/ABStopWatchTimeIntervalProvider.h>
#import <AddressBook/ABSuggestedValueDataSource.h>
#import <AddressBook/ABSuggestedValueViewControllerDelegate.h>
#import <AddressBook/ABUndoableCommand.h>
#import <AddressBook/ABUserInterfaceAction.h>
#import <AddressBook/AsyncABPersonViewProtocol.h>
#import <AddressBook/CNCollectionViewTouchBarDelegate.h>
#import <AddressBook/CNContactCardViewControllerDelegate.h>
#import <AddressBook/CNContactPickerDelegate.h>
#import <AddressBook/CNFoundationUserDefaults.h>
#import <AddressBook/CNPrivateContactPickerDelegate.h>
#import <AddressBook/CNUISaveRequestCommand.h>
#import <AddressBook/NSAccessibilityButton.h>
#import <AddressBook/NSAccessibilityElement.h>
#import <AddressBook/NSAccessibilityStaticText.h>
#import <AddressBook/NSControlTextEditingDelegate.h>
#import <AddressBook/NSImmediateActionAnimationController.h>
#import <AddressBook/NSMenuDelegate.h>
#import <AddressBook/NSOutlineViewDataSource.h>
#import <AddressBook/NSOutlineViewDelegate.h>
#import <AddressBook/NSPopoverDelegate.h>
#import <AddressBook/NSRemoteViewDelegate.h>
#import <AddressBook/NSSearchFieldDelegate.h>
#import <AddressBook/NSSharingServiceDelegate.h>
#import <AddressBook/NSSharingServicePickerDelegate.h>
#import <AddressBook/NSTableViewDataSource.h>
#import <AddressBook/NSTableViewDelegate.h>
#import <AddressBook/NSTextDelegate.h>
#import <AddressBook/NSTextFieldDelegate.h>
#import <AddressBook/NSTextViewDelegate.h>
#import <AddressBook/NSWindowDelegate.h>
#import <AddressBook/NSWindowRestoration.h>
#import <AddressBook/TKTonePickerViewControllerDelegate.h>
#import <AddressBook/_SGSuggestionsServiceMetricsProtocol.h>
#import <AddressBook/ABAPIAdapter.h>
#import <AddressBook/ABAbstractGroupEntriesFactory.h>
#import <AddressBook/ABAbstractGroupListAction.h>
#import <AddressBook/ABAccountBrowsingGroupEntry.h>
#import <AddressBook/ABAccountGroupEntries.h>
#import <AddressBook/ABAccountGroupEntriesBuilder.h>
#import <AddressBook/ABAccountHeaderGroupEntry.h>
#import <AddressBook/CNUISaveNonCuratedValueOntoExistingContactCommand.h>
#import <AddressBook/CNUISaveNonCuratedContactCommand.h>
#import <AddressBook/ABUserActivityScore.h>
#import <AddressBook/ABActionAddSuggestedValue.h>
#import <AddressBook/ABUserActivityRestoration.h>
#import <AddressBook/ABActionAddressCopyMailingLabel.h>
#import <AddressBook/ABActionAddressCopyMapURL.h>
#import <AddressBook/ABActionAddressGetDirections.h>
#import <AddressBook/CNUIContactNameOrder.h>
#import <AddressBook/_CNUIDefaultContactNameOrder.h>
#import <AddressBook/_CNUINamelessContactNameOrder.h>
#import <AddressBook/_CNUIGivenNameFirstNameOrder.h>
#import <AddressBook/_CNUIFamilyNameFirstNameOrder.h>
#import <AddressBook/ABActionAddressMapsHelper.h>
#import <AddressBook/ABActionAddressShowMap.h>
#import <AddressBook/ABActionAutovalidator.h>
#import <AddressBook/ABActionAutovalidatorCache.h>
#import <AddressBook/ABActionAutovalidatorCacheEntry.h>
#import <AddressBook/ABActionAutovalidatorCacheMenuEntry.h>
#import <AddressBook/ABActionAutovalidatorCacheSimpleEntry.h>
#import <AddressBook/ABActionBeginChat.h>
#import <AddressBook/ABActionDispatcher.h>
#import <AddressBook/ABCardCollectionRowSeparatorView.h>
#import <AddressBook/ABActionEmailSearchSpotlight.h>
#import <AddressBook/ABActionEmailSendMessage.h>
#import <AddressBook/ABActionEmailSendUpdate.h>
#import <AddressBook/ABActionIgnoreSuggestedValue.h>
#import <AddressBook/ABActionLinkedSetPreferredCard.h>
#import <AddressBook/ABActionManager.h>
#import <AddressBook/ABActionMenuItemFactory.h>
#import <AddressBook/ABActionPhoneDial.h>
#import <AddressBook/ABActionPhoneLargeType.h>
#import <AddressBook/ABActionRelatedShowCard.h>
#import <AddressBook/ABActionSocialProfile.h>
#import <AddressBook/ABActionSocialProfileSendMessage.h>
#import <AddressBook/ABActionSocialProfileViewPhotos.h>
#import <AddressBook/ABActionSocialProfileViewProfile.h>
#import <AddressBook/ABActionURLsOpenURL.h>
#import <AddressBook/ABAddSuggestedValueTask.h>
#import <AddressBook/CNUISaveNonCuratedValueOntoContactCommand.h>
#import <AddressBook/ABAddressBookAPIAdapter.h>
#import <AddressBook/ABAddressFieldBuilder.h>
#import <AddressBook/ABAddressFieldValuePopulator.h>
#import <AddressBook/ABAggregateSearchOperationsFactory.h>
#import <AddressBook/ABAlert.h>
#import <AddressBook/ABAlertToneCollectionViewItem.h>
#import <AddressBook/ABAllSmartGroup.h>
#import <AddressBook/ABAlternateBirthdayCollectionViewItem.h>
#import <AddressBook/ABAppDeprecations.h>
#import <AddressBook/ABAppearance.h>
#import <AddressBook/ABAuthenticationInfo.h>
#import <AddressBook/ABBestEntryFinder.h>
#import <AddressBook/ABMutableBidirectionalDictionary.h>
#import <AddressBook/ABBidirectionalDictionary.h>
#import <AddressBook/ABDeprecatedObject.h>
#import <AddressBook/ABSearchController.h>
#import <AddressBook/ABCardViewerController.h>
#import <AddressBook/CNUIAddressBookToContactsConversions.h>
#import <AddressBook/ABBindingsLabelTransformer.h>
#import <AddressBook/ABBindingsURLTransformer.h>
#import <AddressBook/ABAttributedStringTransformer.h>
#import <AddressBook/ABGroupListTransformer.h>
#import <AddressBook/ABPeopleListTransformer.h>
#import <AddressBook/ABDateComponentsValueTransformer.h>
#import <AddressBook/ABBirthdayCollectionViewItem.h>
#import <AddressBook/ABBirthdayConversionUIAction.h>
#import <AddressBook/ABBookAggregateUndoableCommand.h>
#import <AddressBook/_ABBookUndoableCommandAdapter.h>
#import <AddressBook/ABBookAggregateUndoableCommandBuilder.h>
#import <AddressBook/ABBookCreateGroupCommand.h>
#import <AddressBook/ABBookCreateGroupWithMembersCommand.h>
#import <AddressBook/ABBookCreateSmartGroupCommand.h>
#import <AddressBook/ABBookEditSmartGroupCommand.h>
#import <AddressBook/ABBookGroupAddMembersCommand.h>
#import <AddressBook/ABBookGroupAddRecordsCommand.h>
#import <AddressBook/ABBookGroupAddSubgroupsCommand.h>
#import <AddressBook/ABBookGroupCopyCommand.h>
#import <AddressBook/ABCollectionViewSeparatorItem.h>
#import <AddressBook/ABBookGroupCutCommand.h>
#import <AddressBook/ABBookGroupDeleteCommand.h>
#import <AddressBook/ABBookGroupImportCommand.h>
#import <AddressBook/ABBookPastePeopleCommand.h>
#import <AddressBook/ABBookRenameGroupCommand.h>
#import <AddressBook/ABBookSearchField.h>
#import <AddressBook/ABBookSearchFieldCell.h>
#import <AddressBook/CNUISetImageCommand.h>
#import <AddressBook/CNUISetMultipleImagesCommand.h>
#import <AddressBook/ABBrowsingGroupEntry.h>
#import <AddressBook/ABBrowsingSearchConfiguration.h>
#import <AddressBook/CNUIRejectSugggestedValueCommand.h>
#import <AddressBook/ABBuddyStatus.h>
#import <AddressBook/ABBuddyStatusImageCell.h>
#import <AddressBook/ABButtonCell.h>
#import <AddressBook/ABCNAddressDetector.h>
#import <AddressBook/CNContactLabelSanitizer.h>
#import <AddressBook/ABCNContactPhotoStore.h>
#import <AddressBook/ABCNContactThumbnailPhotoStore.h>
#import <AddressBook/ABCNContactUncroppedPhotoStore.h>
#import <AddressBook/ABCNContactRemotePhotoStore.h>
#import <AddressBook/CNUISaveNonCuratedValueOntoReadOnlyContactCommand.h>
#import <AddressBook/ABCNDDScanner.h>
#import <AddressBook/ABNameViewCompanyCheckBox.h>
#import <AddressBook/CNUISaveNonCuratedContactCommandFactory.h>
#import <AddressBook/ABCNPhoneDialer.h>
#import <AddressBook/ABCNPhoneNumberDetector.h>
#import <AddressBook/ABCardCollectionStackViewController.h>
#import <AddressBook/CNUIContactRelationsValueTransformer.h>
#import <AddressBook/ABCallbackCardAction.h>
#import <AddressBook/ABPersonListAttributedName.h>
#import <AddressBook/ABCardActionProvider.h>
#import <AddressBook/ABCardCollectionLinkedPeopleRowView.h>
#import <AddressBook/ABCardCollectionMessagingRowView.h>
#import <AddressBook/ABCardCollectionNoteRowView.h>
#import <AddressBook/ABCardCollectionPostalAddressRowView.h>
#import <AddressBook/ABCardCollectionPreferredNameRowView.h>
#import <AddressBook/ABCardCollectionRowLayout.h>
#import <AddressBook/ABCardCollectionRowScope.h>
#import <AddressBook/ABCardCollectionRowView.h>
#import <AddressBook/ABCardCollectionURLRowView.h>
#import <AddressBook/ABSuggestionsTracing.h>
#import <AddressBook/ABCardCollectionView.h>
#import <AddressBook/ABCardCollectionViewController.h>
#import <AddressBook/ABCardViewCNLabeledValueConverter.h>
#import <AddressBook/ABCardViewAKSingleValueConverter.h>
#import <AddressBook/ABCardViewAlertTonesProperty.h>
#import <AddressBook/ABCardViewAlternateBirthdayProperty.h>
#import <AddressBook/ABCardViewBirthdayProperty.h>
#import <AddressBook/ABCardViewDateProperty.h>
#import <AddressBook/ABCardViewDictionaryTransformer.h>
#import <AddressBook/ABCardViewEditDisplayStyleCommand.h>
#import <AddressBook/ABCardViewEditPropertyCommand.h>
#import <AddressBook/ABCardViewEmailProperty.h>
#import <AddressBook/ABCardViewHelpers.h>
#import <AddressBook/ABCardViewImage.h>
#import <AddressBook/ABCardViewImageResult.h>
#import <AddressBook/ABCardViewInstantMessageProperty.h>
#import <AddressBook/ABCardViewInstantMessageServiceGenerator.h>
#import <AddressBook/ABCardViewLabelGenerator.h>
#import <AddressBook/ABCardViewLinkedPeopleProperty.h>
#import <AddressBook/ABCardViewLinkedPerson.h>
#import <AddressBook/ABCardViewLinkedPersonValueTransformer.h>
#import <AddressBook/ABCardViewMaidenNameProperty.h>
#import <AddressBook/ABCardViewMetrics.h>
#import <AddressBook/ABCardViewMultiValue.h>
#import <AddressBook/ABCardViewMultiValueAccountNameTransformer.h>
#import <AddressBook/ABCardViewMultiValueConverterBuilder.h>
#import <AddressBook/ABCardViewMultiValueEntry.h>
#import <AddressBook/ABCardViewMultiValuePrivateFieldTransformer.h>
#import <AddressBook/ABCardViewMultiValueReadOnlyTransformer.h>
#import <AddressBook/ABCardViewMutableMultiValue.h>
#import <AddressBook/ABCardViewNoteProperty.h>
#import <AddressBook/ABCardViewNotificationHandler.h>
#import <AddressBook/ABCardViewPersonMapper.h>
#import <AddressBook/ABCardViewPhoneProperty.h>
#import <AddressBook/ABCardViewPostalAddressFormatter.h>
#import <AddressBook/ABCardViewPostalAddressProperty.h>
#import <AddressBook/ABCardViewPreferredForNameProperty.h>
#import <AddressBook/ABCardViewPreferredForNameValueTransformer.h>
#import <AddressBook/ABCardViewProperty.h>
#import <AddressBook/ABCardViewPropertyProvider.h>
#import <AddressBook/ABCardViewSaveHelper.h>
#import <AddressBook/ABCardViewSeparator.h>
#import <AddressBook/ABUserActivityScoring.h>
#import <AddressBook/ABCardViewSingleValueProperty.h>
#import <AddressBook/ABCardViewSocialProfileProperty.h>
#import <AddressBook/ABCardViewStyleInternalProvider.h>
#import <AddressBook/ABCardViewStyle.h>
#import <AddressBook/ABCardViewStyleProvider.h>
#import <AddressBook/ABDefaultCardViewStyleProvider.h>
#import <AddressBook/ABCardViewTransformingMultiValueConverter.h>
#import <AddressBook/ABCardViewURLProperty.h>
#import <AddressBook/ABCardViewUndoableDataSource.h>
#import <AddressBook/ABCertificatePanelController.h>
#import <AddressBook/ABChangePropertiesCommand.h>
#import <AddressBook/ABChangePropertyCommand.h>
#import <AddressBook/ABChoosingForwarder.h>
#import <AddressBook/ABCleanGroupEntryListCellView.h>
#import <AddressBook/ABCleanGroupHeaderEntryListCellView.h>
#import <AddressBook/ABCleanGroupListRowView.h>
#import <AddressBook/ABClickableImageView.h>
#import <AddressBook/ABClickableTextView.h>
#import <AddressBook/ABCollectionAbstractAction.h>
#import <AddressBook/ABCollectionDialAction.h>
#import <AddressBook/ABCollectionFaceTimeRowView.h>
#import <AddressBook/ABCollectionItemMessagingAvailabilityHelper.h>
#import <AddressBook/ABCollectionMessageAction.h>
#import <AddressBook/ABCollectionOpenURLAction.h>
#import <AddressBook/ABCollectionReviewSuggestionAction.h>
#import <AddressBook/ABCollectionRowViewEditModeFactory.h>
#import <AddressBook/ABCollectionRowViewFactory.h>
#import <AddressBook/ABAccessibleTextFieldCell.h>
#import <AddressBook/ABCollectionSendMailAction.h>
#import <AddressBook/ABCollectionShowMapAction.h>
#import <AddressBook/ABCollectionTTYAction.h>
#import <AddressBook/ABCollectionViewImageButton.h>
#import <AddressBook/ABCollectionViewItem.h>
#import <AddressBook/ABCollectionViewItemFactory.h>
#import <AddressBook/ABColor.h>
#import <AddressBook/ABCommandExecutionPolicy.h>
#import <AddressBook/ABAddressBookCommandExecutionPolicy.h>
#import <AddressBook/ABCommandHookExecutionPolicy.h>
#import <AddressBook/ABCommandExecutor.h>
#import <AddressBook/ABCommunicationButtonsController.h>
#import <AddressBook/ABConstraintDescription.h>
#import <AddressBook/ABConstraintsBuilder.h>
#import <AddressBook/ABContactDeletionTracing.h>
#import <AddressBook/ABContactFetcher.h>
#import <AddressBook/ABContactPickerDelegateWrapper.h>
#import <AddressBook/ABContactPickerFactory.h>
#import <AddressBook/ABAttributedString.h>
#import <AddressBook/ABCopyOnWriteSet.h>
#import <AddressBook/ABCountTableEntry.h>
#import <AddressBook/ABCreatePersonCommand.h>
#import <AddressBook/ABCustomLabelController.h>
#import <AddressBook/ABDAVQuery.h>
#import <AddressBook/ABDataSourceOperation.h>
#import <AddressBook/ABDateCollectionViewItem.h>
#import <AddressBook/ABDateComponentsFormatter.h>
#import <AddressBook/ABDateFormatter.h>
#import <AddressBook/ABDateProvider.h>
#import <AddressBook/ABDefaultGroupEntriesFactory.h>
#import <AddressBook/ABDelegateCardAction.h>
#import <AddressBook/ABDeleteGroupSheet.h>
#import <AddressBook/ABDeleteRecordsCommandBuilder.h>
#import <AddressBook/ABDirectoriesHeaderGroupEntry.h>
#import <AddressBook/ABDSuggestionLogPairBuilder.h>
#import <AddressBook/ABDistributionListController.h>
#import <AddressBook/ABDistributionKeyValueCell.h>
#import <AddressBook/ABDistributionListPeoplePickerView.h>
#import <AddressBook/ABDistributionListPeoplePickerController.h>
#import <AddressBook/ABDropDownMenuUIAction.h>
#import <AddressBook/ABEditButton.h>
#import <AddressBook/ABEditSmartGroupCommand.h>
#import <AddressBook/ABEmailCertificateController.h>
#import <AddressBook/ABEmailCertificateSearchOperation.h>
#import <AddressBook/ABEmailCollectionViewItem.h>
#import <AddressBook/ABEvent.h>
#import <AddressBook/ABExchangeSetup.h>
#import <AddressBook/ABFaceTimeActionsCollectionViewItem.h>
#import <AddressBook/ABFaceTimeCommunicationsBridge.h>
#import <AddressBook/ABFakeSuggestedData.h>
#import <AddressBook/ABFont.h>
#import <AddressBook/CNUIDeleteCommandHelper.h>
#import <AddressBook/CNUIPhoneNumerValueTransformer.h>
#import <AddressBook/ABTelURLHelper.h>
#import <AddressBook/ABGroupActionScope.h>
#import <AddressBook/ABGroupBrowsingContext.h>
#import <AddressBook/ABGroupBrowsingGroupEntry.h>
#import <AddressBook/ABGroupCommand.h>
#import <AddressBook/ABGroupCopyPasteboardData.h>
#import <AddressBook/ABPhoneFormatter.h>
#import <AddressBook/ABGroupDragPasteboardData.h>
#import <AddressBook/ABGroupDragScope.h>
#import <AddressBook/ABGroupDragSource.h>
#import <AddressBook/ABGroupDropDestination.h>
#import <AddressBook/ABGroupDropPasteboardData.h>
#import <AddressBook/ABGroupDropPasteboardDataCategorizer.h>
#import <AddressBook/ABGroupDropScope.h>
#import <AddressBook/ABGroupDropSource.h>
#import <AddressBook/ABGroupEntriesAnalyzer.h>
#import <AddressBook/ABGroupEntriesBuilder.h>
#import <AddressBook/ABGroupEntriesList.h>
#import <AddressBook/ABGroupEntriesResult.h>
#import <AddressBook/ABGroupEntry.h>
#import <AddressBook/ABGroupImportFilesScope.h>
#import <AddressBook/ABGroupListAccessoryViewProvider.h>
#import <AddressBook/ABGroupListActionDispatcher.h>
#import <AddressBook/ABGroupListActions.h>
#import <AddressBook/ABGroupListCellViewStyle.h>
#import <AddressBook/ABGroupListController.h>
#import <AddressBook/ABGroupListCreateGroupUIAction.h>
#import <AddressBook/ABGroupListCreateSmartGroupUIAction.h>
#import <AddressBook/ABGroupListNotificationHandler.h>
#import <AddressBook/ABGroupListResponder.h>
#import <AddressBook/ABGroupListStyleProvider.h>
#import <AddressBook/ABGroupListView.h>
#import <AddressBook/ABGroupPastePasteboardData.h>
#import <AddressBook/ABGroupSearchingContext.h>
#import <AddressBook/ABHeaderGroupEntry.h>
#import <AddressBook/ABImmediateActionGestureAdapter.h>
#import <AddressBook/ABTemplatePreferencesSaving.h>
#import <AddressBook/ABRectObject.h>
#import <AddressBook/ABPackedImage.h>
#import <AddressBook/ABMutablePackedImage.h>
#import <AddressBook/ABImportRecordFactory.h>
#import <AddressBook/ABInstantMessageCollectionViewItem.h>
#import <AddressBook/_ABGeocodingMapsLauncher.h>
#import <AddressBook/ABKeystrokeForwarder.h>
#import <AddressBook/ABKeystrokeForwardingEntry.h>
#import <AddressBook/ABLabelPopUpButton.h>
#import <AddressBook/ABLargeTypeView.h>
#import <AddressBook/ABLargeTypeWindow.h>
#import <AddressBook/ABLastImportBrowsingGroupEntry.h>
#import <AddressBook/ABLastImportGroup.h>
#import <AddressBook/ABLazyGroup.h>
#import <AddressBook/ABLinkTextField.h>
#import <AddressBook/ABLinkedPersonCollectionViewItem.h>
#import <AddressBook/ABMainListOutlineView.h>
#import <AddressBook/CNUIRejectNonCuratedValueCommandFactory.h>
#import <AddressBook/ABMeCommand.h>
#import <AddressBook/ABPostalAddressFormatSubmenuGenerator.h>
#import <AddressBook/CNUIRejectNonCuratedValueCommand.h>
#import <AddressBook/ABMiniGridView.h>
#import <AddressBook/ABMonogramFactory.h>
#import <AddressBook/ABMonogramImageLoading.h>
#import <AddressBook/ABMonogramImageTask.h>
#import <AddressBook/ABMonogramInitialsTask.h>
#import <AddressBook/_ABMonogramOptions.h>
#import <AddressBook/ABMonogramOptions.h>
#import <AddressBook/ABMonogramPhotoTask.h>
#import <AddressBook/ABMonogramSilhouetteTask.h>
#import <AddressBook/ABNameView.h>
#import <AddressBook/ABNewGroupCommand.h>
#import <AddressBook/ABNicknameFormatter.h>
#import <AddressBook/ABNoSelectionTableView.h>
#import <AddressBook/ABNoWindowDragTextField.h>
#import <AddressBook/ABNoteCollectionViewItem.h>
#import <AddressBook/ABNoteTextView.h>
#import <AddressBook/ABObjectDeathWatcher.h>
#import <AddressBook/ABNamedImageWrapper.h>
#import <AddressBook/ABOnBlueButton.h>
#import <AddressBook/ABOverlayView.h>
#import <AddressBook/ABPasswordPanelController.h>
#import <AddressBook/ABPastePeopleCommand.h>
#import <AddressBook/ABPasteboardWriteCommand.h>
#import <AddressBook/ABPeoplePickerBrowsingSelectHelper.h>
#import <AddressBook/ABPeoplePickerController.h>
#import <AddressBook/ABPeoplePickerExternalNotificationWatcher.h>
#import <AddressBook/ABPeoplePickerGroupEntriesFactory.h>
#import <AddressBook/ABPeoplePickerGroupHelperFactory.h>
#import <AddressBook/ABUserActivitySerialization.h>
#import <AddressBook/ABPeoplePickerGroupListController.h>
#import <AddressBook/ABPeoplePickerGroupListStyleProvider.h>
#import <AddressBook/ABPeoplePickerGroupListView.h>
#import <AddressBook/ABPeoplePickerLocalNotificationWatcher.h>
#import <AddressBook/ABPeoplePickerProperty.h>
#import <AddressBook/ABPeoplePickerScope.h>
#import <AddressBook/ABPeoplePickerSearchingSelectHelper.h>
#import <AddressBook/ABPeoplePickerSubrowObjectBuilder.h>
#import <AddressBook/ABPeoplePickerTableView.h>
#import <AddressBook/ABPeoplePickerTableColumn.h>
#import <AddressBook/ABPeoplePickerTableRow.h>
#import <AddressBook/ABPeoplePickerSubrowObject.h>
#import <AddressBook/ABPeoplePickerSubrowGroupElement.h>
#import <AddressBook/ABPeoplePickerNameCell.h>
#import <AddressBook/ABPeoplePickerPropertyCell.h>
#import <AddressBook/ABPeoplePickerView.h>
#import <AddressBook/ABPeriodicTask.h>
#import <AddressBook/ABPeriodicUITask.h>
#import <AddressBook/ABPersonContactConverter.h>
#import <AddressBook/ABPersonEntriesFetcher.h>
#import <AddressBook/ABPersonEntriesList.h>
#import <AddressBook/ABPersonEntry.h>
#import <AddressBook/ABPersonEntryFactory.h>
#import <AddressBook/ABPersonInitials.h>
#import <AddressBook/ABPersonListController.h>
#import <AddressBook/ABPersonListControllerDelegateWrapper.h>
#import <AddressBook/ABPersonListControllerTracing.h>
#import <AddressBook/ABPersonListDragExportHelper.h>
#import <AddressBook/ABPersonListHeadliner.h>
#import <AddressBook/ABPersonListMenuHelper.h>
#import <AddressBook/ABPersonListRowView.h>
#import <AddressBook/ABPersonListSearchController.h>
#import <AddressBook/ABPersonListSearchHelper.h>
#import <AddressBook/ABPersonListSharingHelper.h>
#import <AddressBook/ABPersonListUIReflector.h>
#import <AddressBook/ABPersonPicker.h>
#import <AddressBook/CNUISaveNonCuratedValueOntoNonExistingContactCommand.h>
#import <AddressBook/ABPersonSearchConfiguration.h>
#import <AddressBook/ABPersonView.h>
#import <AddressBook/ABPersonViewAPIAdapter.h>
#import <AddressBook/ABPersonViewNotificationWatcher.h>
#import <AddressBook/CNUISaveNonCuratedValueCommandFactory.h>
#import <AddressBook/ABPersonViewStyleProvider.h>
#import <AddressBook/ABPhoneCollectionViewItem.h>
#import <AddressBook/ABPopUpButton.h>
#import <AddressBook/ABPopUpButtonCell.h>
#import <AddressBook/ABPopupTableHeaderCell.h>
#import <AddressBook/ABPopupTableHeaderView.h>
#import <AddressBook/ABPostalAddressCollectionViewItem.h>
#import <AddressBook/ABPreferredNameCollectionViewItem.h>
#import <AddressBook/ABPropertyHeaderCell.h>
#import <AddressBook/ABCardViewRelatedNamesProperty.h>
#import <AddressBook/ABQuerySearchConfiguration.h>
#import <AddressBook/ABRecordContext.h>
#import <AddressBook/_ABURLMapsLauncher.h>
#import <AddressBook/CNUIRejectDonatedValueCommand.h>
#import <AddressBook/ABMapsLauncher.h>
#import <AddressBook/ABRemotePersonView.h>
#import <AddressBook/ABRemoveMembersCommand.h>
#import <AddressBook/ABRemoveMembersCommandBuilder.h>
#import <AddressBook/ABRemovesEmptyCardViewData.h>
#import <AddressBook/ABRenameGroupCommand.h>
#import <AddressBook/ABRolloverButton.h>
#import <AddressBook/ABMapsLaunchRequest.h>
#import <AddressBook/ABSearchElementOrderManager.h>
#import <AddressBook/ABSearchElementSetView.h>
#import <AddressBook/ABSearchElementUIController.h>
#import <AddressBook/ABSearchElementView.h>
#import <AddressBook/ABSearchHighlightFormatter.h>
#import <AddressBook/ABSearchingGroupEntry.h>
#import <AddressBook/ABSectionGroupEntry.h>
#import <AddressBook/ABSectionTableEntry.h>
#import <AddressBook/ABShadowTextField.h>
#import <AddressBook/ABShadowTextFieldCell.h>
#import <AddressBook/ABShadowTextView.h>
#import <AddressBook/ABShadowTextViewMultipleValuePasteHelper.h>
#import <AddressBook/ABFlippedStackView.h>
#import <AddressBook/ABShadowTextViewPostalAddressValuePasteHelper.h>
#import <AddressBook/ABShowAsCommand.h>
#import <AddressBook/ABSimpleLinkTextField.h>
#import <AddressBook/ABSmartGroupBrowsingGroupEntry.h>
#import <AddressBook/ABSmartGroupsHeaderGroupEntry.h>
#import <AddressBook/ABSocialProfileCollectionViewItem.h>
#import <AddressBook/ABSourceSyncPeriodicTaskScheduler.h>
#import <AddressBook/ABSpaceFormatter.h>
#import <AddressBook/ABDefaultStopWatchTimeIntervalProvider.h>
#import <AddressBook/ABStopWatch.h>
#import <AddressBook/CNUISaveSuggestedMeContactCommand.h>
#import <AddressBook/ABSuggestedEntriesFetcher.h>
#import <AddressBook/ABSuggestedValueSnippet.h>
#import <AddressBook/ABSuggestedValueViewController.h>
#import <AddressBook/ABSuggestedValueViewControllerSnippetHelper.h>
#import <AddressBook/ABRTTServices.h>
#import <AddressBook/ABTableEntry.h>
#import <AddressBook/ABTableHeaderView.h>
#import <AddressBook/ABTemplateViewStyleProvider.h>
#import <AddressBook/ABTextContainer.h>
#import <AddressBook/ABTextStorage.h>
#import <AddressBook/ABThrottledTrackingAreaMonitor.h>
#import <AddressBook/ABTrackingArea.h>
#import <AddressBook/ABTypesetter.h>
#import <AddressBook/ABURLCollectionViewItem.h>
#import <AddressBook/ABUndoableCommandVisitor.h>
#import <AddressBook/ABExecuteUndoableCommandVisitor.h>
#import <AddressBook/ABExecuteUndoUndoableCommandVisitor.h>
#import <AddressBook/ABExecuteRedoUndoableCommandVisitor.h>
#import <AddressBook/ABUnlinkPeopleCommand.h>
#import <AddressBook/ABUserDefaultsCNAdapter.h>
#import <AddressBook/ABVCardFilenameExpander.h>
#import <AddressBook/ABView.h>
#import <AddressBook/ABWhiteView.h>
#import <AddressBook/ABWidthLimitingStackView.h>
#import <AddressBook/ABWindowController.h>
#import <AddressBook/ABXMLParseNode.h>
#import <AddressBook/CNUISaveSuggestedContactCommand.h>
#import <AddressBook/CNUIAddContactCommand.h>
#import <AddressBook/CNUIAggregateUndoableCommand.h>
#import <AddressBook/CNUIAggregateUndoableCommandBuilder.h>
#import <AddressBook/AKCardViewDataSource.h>
#import <AddressBook/AKCardViewDataSourceFactory.h>
#import <AddressBook/AKCardViewImageDataSource.h>
#import <AddressBook/CNUIDeleteContactCommand.h>
#import <AddressBook/CNUICommandContactHelper.h>
#import <AddressBook/CNUIEditContactCommand.h>
#import <AddressBook/AKInstantMessageAddressValueTransformer.h>
#import <AddressBook/CNUISetMeCardCommand.h>
#import <AddressBook/AKSocialProfileValueTransformer.h>
#import <AddressBook/CNUIUndoableCommand.h>
#import <AddressBook/CNCollectionUserActionItem.h>
#import <AddressBook/PHXTableView.h>
#import <AddressBook/ABCardCollectionTableRowView.h>
#import <AddressBook/ABCardCollectionTableViewController.h>
#import <AddressBook/_ABPersonView.h>

void* ABAddressBookLocalizedString(void);
void* ABDeleteRecordsCommandNameForRecords(void);
void* ABEmailCertificateCopyMatchingUnexpired(void);
void* ABEmailCertificateHasMatchingUnexpired(void);
void* ABIsParagraphSeparator(void);
void* ABPickerAddProperty(void);
void* ABPickerChangeAttributes(void);
void* ABPickerClearSearchField(void);
void* ABPickerCopyColumnTitle(void);
void* ABPickerCopyDisplayedProperty(void);
void* ABPickerCopyProperties(void);
void* ABPickerCopySelectedGroups(void);
void* ABPickerCopySelectedIdentifiers(void);
void* ABPickerCopySelectedRecords(void);
void* ABPickerCopySelectedValues(void);
void* ABPickerCreate(void);
void* ABPickerDeselectAll(void);
void* ABPickerDeselectGroup(void);
void* ABPickerDeselectIdentifier(void);
void* ABPickerDeselectRecord(void);
void* ABPickerEditInAddressBook(void);
void* ABPickerGetAttributes(void);
void* ABPickerGetDelegate(void);
void* ABPickerGetFrame(void);
void* ABPickerIsVisible(void);
void* ABPickerRemoveProperty(void);
void* ABPickerSelectGroup(void);
void* ABPickerSelectIdentifier(void);
void* ABPickerSelectInAddressBook(void);
void* ABPickerSelectRecord(void);
void* ABPickerSetColumnTitle(void);
void* ABPickerSetDelegate(void);
void* ABPickerSetDisplayedProperty(void);
void* ABPickerSetFrame(void);
void* ABPickerSetVisibility(void);
void* _ABClipRangeToLength(void);
void* _ABEmailCertificateCopyAllMatching(void);
void* _ABEmailCertificateHasExpired(void);
void* addChild(void);
void* createStructure(void);
void* endStructure(void);
void* handleError(void);
void* resolveExternalEntity(void);

#endif
