.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)sigpause.2	8.1 (Berkeley) 6/2/93
.\" $FreeBSD: src/lib/libc/compat-43/sigpause.2,v 1.5.2.5 2001/12/14 18:33:49 ru Exp $
.\"
.Dd June 2, 1993
.Dt SIGPAUSE 2
.Os
.Sh NAME
.Nm sigpause
.Nd atomically release blocked signals and wait for interrupt
.Sh LIBRARY
.Lb libc
.Sh SYNOPSIS
.In signal.h
.Ft int
.Fn sigpause "int sig"
.Sh DESCRIPTION
.Sy This interface is made obsolete by
.Xr sigsuspend 2 .
.Pp
.Fn Sigpause
assigns
.Fa sig
to the set of masked signals
and then waits for a signal to arrive;
on return the set of masked signals is restored.
.Fa Sig
is usually 0, indicating that no
signals are to be blocked.
.Fn Sigpause
always terminates by being interrupted, returning -1 with
.Va errno
set to
.Er EINTR .
.Sh COMPATIBILITY
.Fn sigpause
now takes a signal value and not a mask.
This often appears as a hang in sigpause$UNIX2003
or with
.Fn sigpause
returning with
.Va errno
set to EINVAL.
Use
.Fn sigsuspend
with signal masks.
.Sh SEE ALSO
.Xr kill 2 ,
.Xr sigaction 2 ,
.Xr sigblock 2 ,
.Xr sigprocmask 2 ,
.Xr sigsuspend 2 ,
.Xr sigvec 2
.Sh HISTORY
The
.Fn sigpause
function call appeared in
.Bx 4.2
and has been deprecated.
