/*
 This file is part of Darling.

 Copyright (C) 2019 Lubos Dolezel

 Darling is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Darling is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Darling.  If not, see <http://www.gnu.org/licenses/>.
*/


#ifndef _CoreUI_H_
#define _CoreUI_H_

#import <Foundation/Foundation.h>

#import <CoreUI/CUIStructuredThemeStorage.h>
#import <CoreUI/CUIStructuredThemeStorage2.h>
#import <CoreUI/CUIThemeGradientDrawing.h>
#import <CoreUI/CUIThemeImageSource.h>
#import <CoreUI/MDLMeshBuffer.h>
#import <CoreUI/TXRDataSourceProvider.h>
#import <CoreUI/_CUIThemeSVGRendition.h>
#import <CoreUI/CUINamedModel.h>
#import <CoreUI/CUINamedVectorGlyph.h>
#import <CoreUI/CUIMeshBuffer.h>
#import <CoreUI/CUINamedImageAtlas.h>
#import <CoreUI/CUINamedColor.h>
#import <CoreUI/_CUIThemeTextStyleRendition.h>
#import <CoreUI/CUIRuntimeStatistics.h>
#import <CoreUI/CUINamedImageDescription.h>
#import <CoreUI/_CUIThemeModelMeshRendition.h>
#import <CoreUI/CUIShapeEffectPreset.h>
#import <CoreUI/CUINamedRecognitionImage.h>
#import <CoreUI/CUIMutableCatalog.h>
#import <CoreUI/CUINamedRecognitionGroup.h>
#import <CoreUI/CUINamedData.h>
#import <CoreUI/CUINamedVectorImage.h>
#import <CoreUI/CUINamedVectorPDFImage.h>
#import <CoreUI/CUINamedVectorSVGImage.h>
#import <CoreUI/CUIShapeEffectStack.h>
#import <CoreUI/CUIPSDLayerEnumerator.h>
#import <CoreUI/CUIScaleClampFilterLocal.h>
#import <CoreUI/CUIInnerGlowFilterLocal.h>
#import <CoreUI/CUIInnerShadowFilterLocal.h>
#import <CoreUI/CUIOuterGlowFilterLocal.h>
#import <CoreUI/CUIInnerGlowOrShadowFilterLocal.h>
#import <CoreUI/CUIOuterGlowOrShadowFilterLocal.h>
#import <CoreUI/CUISmoothEmbossFilterLocal.h>
#import <CoreUI/CUIOuterBevelEmbossFilterLocal.h>
#import <CoreUI/CUIInnerBevelEmbossFilterLocal.h>
#import <CoreUI/CUIOuterShadowFilterLocal.h>
#import <CoreUI/CUISmallBlurLocal.h>
#import <CoreUI/CUIShapeEffectBlur1Local.h>
#import <CoreUI/CUIHueSaturationFilterLocal.h>
#import <CoreUI/CUITextEffectStack.h>
#import <CoreUI/CUIPerformanceLogManager.h>
#import <CoreUI/CUIPerformanceMeasurement.h>
#import <CoreUI/CoreUI.h>
#import <CoreUI/_CUIThemeMultisizeImageSetRendition.h>
#import <CoreUI/CUIPSLayerEffectsPreset.h>
#import <CoreUI/CUITextStyle.h>
#import <CoreUI/CUIPattern.h>
#import <CoreUI/CSIGenerator.h>
#import <CoreUI/CSIBitmapWrapper.h>
#import <CoreUI/CUIPSDGradient.h>
#import <CoreUI/CUIPSDGradientStop.h>
#import <CoreUI/CUIPSDGradientColorStop.h>
#import <CoreUI/CUIPSDGradientDoubleColorStop.h>
#import <CoreUI/CUIPSDGradientOpacityStop.h>
#import <CoreUI/CUIPSDGradientDoubleOpacityStop.h>
#import <CoreUI/_CUIPSDStopAndMidpointPair.h>
#import <CoreUI/CUIPSDGradientEvaluator.h>
#import <CoreUI/_CUIPSDSublayerInfo.h>
#import <CoreUI/CUIPSDImageRef.h>
#import <CoreUI/CUIPSDLayerBaseRef.h>
#import <CoreUI/CUIPSDLayerRef.h>
#import <CoreUI/CUIPSDLayerGroupRef.h>
#import <CoreUI/CUIPSDLayerMaskRef.h>
#import <CoreUI/CUIImage.h>
#import <CoreUI/CUIColor.h>
#import <CoreUI/CUINamedRecognitionObject.h>
#import <CoreUI/CUIRenditionLayerReference.h>
#import <CoreUI/CUIMutableThemeRendition.h>
#import <CoreUI/_CUINineImagePieces.h>
#import <CoreUI/_CUIThemeFacetCacheKey.h>
#import <CoreUI/CUIThemeFacet.h>
#import <CoreUI/CUIThemeGradient.h>
#import <CoreUI/_CUIThemePDFRendition.h>
#import <CoreUI/CUIMaskedFacetLayer.h>
#import <CoreUI/CUICustomFontCacheKey.h>
#import <CoreUI/CUICustomFontCacheValue.h>
#import <CoreUI/CUICommonAssetStorage.h>
#import <CoreUI/CUIMutableCommonAssetStorage.h>
#import <CoreUI/CUIRenditionKey.h>
#import <CoreUI/CUIRenditionMetrics.h>
#import <CoreUI/CUISharedArtCatalog.h>
#import <CoreUI/CUIRenditionSliceInformation.h>
#import <CoreUI/_CUIThemeColorRendition.h>
#import <CoreUI/CUIMutableStructuredThemeStore.h>
#import <CoreUI/_CUIExternalLinkRendition.h>
#import <CoreUI/CUINamedLayerStack.h>
#import <CoreUI/CUINamedLayerImage.h>
#import <CoreUI/_CUIKeyTestOrganizer.h>
#import <CoreUI/CUIStructuredThemeStore.h>
#import <CoreUI/CUISystemStore.h>
#import <CoreUI/CUINamedLookup.h>
#import <CoreUI/CSIATECHelper.h>
#import <CoreUI/CSIHelper.h>
#import <CoreUI/_CSIRenditionBlockData.h>
#import <CoreUI/_CUIMultisizeImageSetSizeAndIndex.h>
#import <CoreUI/_CUIRawPixelRendition.h>
#import <CoreUI/_CUIRawDataRendition.h>
#import <CoreUI/_CUILayerStackRendition.h>
#import <CoreUI/_CUIRecognitionObjectRendition.h>
#import <CoreUI/_CUIThinningPlaceholderRendition.h>
#import <CoreUI/_CUIThemeTextureRendition.h>
#import <CoreUI/CSITextureHelper.h>
#import <CoreUI/_CUIThemeTextureImageRendition.h>
#import <CoreUI/_CUIInternalLinkRendition.h>
#import <CoreUI/_CUINameContentRendition.h>
#import <CoreUI/_CUIThemePixelRendition.h>
#import <CoreUI/CUIThemeRendition.h>
#import <CoreUI/_SchemaRenditionTuple.h>
#import <CoreUI/CUIThemeSchema.h>
#import <CoreUI/_CUIMacOSThemeSchema.h>
#import <CoreUI/_CUIiPhoneOSThemeSchema.h>
#import <CoreUI/CUIThemeSchemaRendition.h>
#import <CoreUI/CUIThemeSchemaEffectRendition.h>
#import <CoreUI/CUIWindowFrameLayer.h>
#import <CoreUI/CUITexturedWindowFrameLayer.h>
#import <CoreUI/CUIThemeDataEffectPreset.h>
#import <CoreUI/CUIThemeSchemaRenditionGroup.h>
#import <CoreUI/CUIThemeSchemaPSDLayer.h>
#import <CoreUI/CUIThemeSchemaPSDRenditionLayer.h>
#import <CoreUI/CUIThemeSchemaPSDLayerGroup.h>
#import <CoreUI/CUINamedImage.h>
#import <CoreUI/CUINamedMultisizeImageSet.h>
#import <CoreUI/CUIPSDLayoutMetricsChannel.h>
#import <CoreUI/CUIPSDLayer.h>
#import <CoreUI/CUIPSDImageLayer.h>
#import <CoreUI/CUIPSDGradientLayer.h>
#import <CoreUI/CUIPSDLayerGroupStart.h>
#import <CoreUI/CUIPSDLayerGroupEnd.h>
#import <CoreUI/CUIMutablePSDImageRef.h>
#import <CoreUI/_CUISubrangeData.h>
#import <CoreUI/CUIThemeSchemaLayer.h>
#import <CoreUI/CUIStyleEffectConfiguration.h>
#import <CoreUI/CUINamedExternalLink.h>
#import <CoreUI/_CUIThemeEffectRendition.h>
#import <CoreUI/CUIPSDLayerEffects.h>
#import <CoreUI/CUIPSDLayerEffectComponent.h>
#import <CoreUI/CUIPSDLayerEffectDropShadow.h>
#import <CoreUI/CUIPSDLayerEffectInnerShadow.h>
#import <CoreUI/CUIPSDLayerEffectInnerGlow.h>
#import <CoreUI/CUIPSDLayerEffectOuterGlow.h>
#import <CoreUI/CUIPSDLayerEffectColorOverlay.h>
#import <CoreUI/CUIPSDLayerEffectGradientOverlay.h>
#import <CoreUI/CUIPSDLayerEffectBevelEmboss.h>
#import <CoreUI/_CUIThemeModelSubmeshRendition.h>
#import <CoreUI/CUICatalog.h>
#import <CoreUI/CUISystemCatalog.h>
#import <CoreUI/CUIBackgroundStyleEffectConfiguration.h>
#import <CoreUI/_CUIThemeGradientRendition.h>
#import <CoreUI/_CUTextureLink.h>
#import <CoreUI/CUINamedTexture.h>
#import <CoreUI/_CUIThemeModelAssetRendition.h>
#import <CoreUI/CUINamedRenditionInfo.h>
#import <CoreUI/CUINamedMultisizeImage.h>
#import <CoreUI/CUILayoutInformation.h>

void* CSIEqualMetrics(void);
void* CUIBlendModeDescriptionFromCGBlendMode(void);
void* CUIBlendModeLSRDescriptionFromCGBlendMode(void);
void* CUICFArrayCreateWithCGRects(void);
void* CUICFDictionaryGetCGRect(void);
void* CUICFDictionarySetCFArrayOfCGRects(void);
void* CUICFDictionarySetCGRect(void);
void* CUICFDictionarySetSegmentSeparatorTypes(void);
void* CUICFDictionarySetSegmentType(void);
void* CUICGBlendModeFromLSRDescription(void);
void* CUICGImageGetAlphaInfo(void);
void* CUICalcNonAlphaAreaOfImage(void);
void* CUICalculateExtrusionMaskOfImage(void);
void* CUIColorCreateFromColorWithSystemEffectOptions(void);
void* CUIColorHistogramARGBIntersection(void);
void* CUIColorHistogramARGBIsMonochrome(void);
void* CUICompareRenditionKey(void);
void* CUIComputeImageColorHistogramARGB(void);
void* CUIConvertCGImageFormat(void);
void* CUIConvertCompressionTypeToString(void);
void* CUIConvertDeepImageTo8(void);
void* CUIConvertImageToPixelFormat(void);
void* CUIConvertPixelFormatToString(void);
void* CUICopyCustomColor(void);
void* CUICopyCustomColorWithOptions(void);
void* CUICopyCustomFontDescriptor(void);
void* CUICopyMeasurements(void);
void* CUICreateLayerContents(void);
void* CUICreateMenuPath(void);
void* CUICreateOrUpdateLayer(void);
void* CUICreateRenderer(void);
void* CUICurrentPlatform(void);
void* CUIDeallocateRGBAImageBuffer(void);
void* CUIDefaultThemeRenditionKeyFormat(void);
void* CUIDraw(void);
void* CUIDrawExtrudedImageInContext(void);
void* CUIDrawStyledGlyphsAtPositions(void);
void* CUIDrawStyledGlyphsWithAdvances(void);
void* CUIEdgeInsetsEqualToEdgeInsets(void);
void* CUIEdgeInsetsFromCGRect(void);
void* CUIEdgeInsetsInsetRect(void);
void* CUIEdgeInsetsMake(void);
void* CUIEdgeInsetsOutsetRect(void);
void* CUIEdgeInsetsToCGRect(void);
void* CUIEdgeInsetsValid(void);
void* CUIEffectBevelStyleDescription(void);
void* CUIEffectBlendModeDescription(void);
void* CUIEqualRenditionKeys(void);
void* CUIEqualRenditionKeysIgnoringAttribute(void);
void* CUIExists(void);
void* CUIFillCARKeyArrayForRenditionKey(void);
void* CUIFillRenditionKeyForCARKeyArray(void);
void* CUIGetChannelDataForImage(void);
void* CUIGetCustomFontSize(void);
void* CUIGetDebugValue(void);
void* CUIGetDeviceArtworkDisplayGamut(void);
void* CUIGetFormatForFeatureSetAndPixelFormat(void);
void* CUIGetRGBAImageBuffer(void);
void* CUIHitTest(void);
void* CUIImageCompressedWithColorQuantization(void);
void* CUIImageIsMonochrome(void);
void* CUIImageIsWideGamut(void);
void* CUIKeyFormatToArrayString(void);
void* CUILogLogToStderr(void);
void* CUIMaxDimensionForVectorGlyph(void);
void* CUIMaxScaleForTargetPlatform(void);
void* CUIMinDimensionForVectorGlyph(void);
void* CUIMinScaleForTargetPlatform(void);
void* CUIParseDeploymentTarget(void);
void* CUIPlaceHolderRendition(void);
void* CUIPlatformNameForPlatform(void);
void* CUIPointSizeForDimensionForVectorGlyph(void);
void* CUIRendererCopyProperties(void);
void* CUIRendererSetProperties(void);
void* CUIRenditionKeyCopy(void);
void* CUIRenditionKeyFormatRemoveAttribute(void);
void* CUIRenditionKeyHasIdentifier(void);
void* CUIRenditionKeySetValueForAttribute(void);
void* CUIRenditionKeyStandardize(void);
void* CUIRenditionKeyTokenCount(void);
void* CUIRenditionKeyValueForAttribute(void);
void* CUISetCustomColorInContext(void);
void* CUISetDebugValue(void);
void* CUISetUpContext(void);
void* CUISystemThemeRenditionKeyFormat(void);
void* CUIThemeInfoVersion(void);
void* CUIUncompressQuantizedImageData(void);
void* _CUILog(void);
void* _LookupStructuredThemeProvider(void);
void* _RegisterThemeProvider(void);

#endif
