/*
 This file is part of Darling.

 Copyright (C) 2017 Lubos Dolezel

 Darling is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Darling is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Darling.  If not, see <http://www.gnu.org/licenses/>.
*/


#ifndef _Contacts_H_
#define _Contacts_H_

#import <Foundation/Foundation.h>

#import <Contacts/CNAbstractPropertyDescription.h>
#import <Contacts/CNCDContactPredicate.h>
#import <Contacts/CNCDContainerPredicate.h>
#import <Contacts/CNCDContainerScopedContactPredicate.h>
#import <Contacts/CNCDContainerScopedGroupPredicate.h>
#import <Contacts/CNCDGroupPredicate.h>
#import <Contacts/CNCancelable.h>
#import <Contacts/CNChangeNotificationReceiver.h>
#import <Contacts/CNChangeNotifierWrapper.h>
#import <Contacts/CNContactAugmentation.h>
#import <Contacts/CNContactCoreDataMultiValueProperty.h>
#import <Contacts/CNContactCoreDataProperty.h>
#import <Contacts/CNContactsLogger.h>
#import <Contacts/CNContactsLoggerProvider.h>
#import <Contacts/CNDataMapper.h>
#import <Contacts/CNDonatedContactsPredicate.h>
#import <Contacts/CNEncodedFetchCursor.h>
#import <Contacts/CNIdentifierProvider.h>
#import <Contacts/CNKeyDescriptor.h>
#import <Contacts/CNKeyDescriptor_Private.h>
#import <Contacts/CNLDAPPredicateRemapping.h>
#import <Contacts/CNLDAPServices.h>
#import <Contacts/CNLaunchServicesAdapter.h>
#import <Contacts/CNObjectValidation.h>
#import <Contacts/CNRecordCoreDataPredicateMapping.h>
#import <Contacts/CNRegulatoryLogger.h>
#import <Contacts/CNSpotlightIndexingLogger.h>
#import <Contacts/CNSuggested.h>
#import <Contacts/CNSuggestedContactPredicate.h>
#import <Contacts/CNVCardNameDataSource.h>
#import <Contacts/CNVCardParsedResultBuilder.h>
#import <Contacts/CNVCardParsedResultBuilderFactory.h>
#import <Contacts/CNVCardPerson.h>
#import <Contacts/CNXPCDataMapperService.h>
#import <Contacts/NSItemProviderReading.h>
#import <Contacts/NSItemProviderWriting.h>
#import <Contacts/NSPredicateVisitor.h>
#import <Contacts/ProgressiveResultsCancellationProtocol.h>
#import <Contacts/ProgressiveResultsHandlerProtocol.h>
#import <Contacts/CNContactVCardWritingAdapter.h>
#import <Contacts/CNChangeHistoryGroupChange.h>
#import <Contacts/CNContactSuggestionMatch.h>
#import <Contacts/CNContactVCardParsedResultBuilder.h>
#import <Contacts/CNContactVCardParsedResultBuilderFactory.h>
#import <Contacts/CNMultiValueDiff.h>
#import <Contacts/CNContainerPropertyDescription.h>
#import <Contacts/CNContainerIdentifierDescription.h>
#import <Contacts/CNContainerNameDescription.h>
#import <Contacts/CNContainerTypeDescription.h>
#import <Contacts/CNContainerEnabledDescription.h>
#import <Contacts/CNAggregateContactStore.h>
#import <Contacts/CNDateComponentsEquivalence.h>
#import <Contacts/CNTCC.h>
#import <Contacts/CNCDSmartGroupFetcher.h>
#import <Contacts/CNPredicate.h>
#import <Contacts/CNContactChangeRequest.h>
#import <Contacts/CNLabeledValue.h>
#import <Contacts/CNCDSubgroupsInGroupPredicate.h>
#import <Contacts/CNLDAPPostalAddressTransform.h>
#import <Contacts/CNFullTextSearchContactPredicate.h>
#import <Contacts/CNLDAPConnection.h>
#import <Contacts/CNCalculatesMultiValueDiff.h>
#import <Contacts/CNCDMeContactFetcher.h>
#import <Contacts/CNCDGroupsWithIdentifiersPredicate.h>
#import <Contacts/CNChangeHistoryFetchRequest.h>
#import <Contacts/CNXPCDataMapper.h>
#import <Contacts/CNXPCDataMapperProgressiveHandler.h>
#import <Contacts/CNInternalIdentifierDescription.h>
#import <Contacts/CNAccountIdentifierDescription.h>
#import <Contacts/CNNamePrefixDescription.h>
#import <Contacts/CNGivenNameDescription.h>
#import <Contacts/CNMiddleNameDescription.h>
#import <Contacts/CNFamilyNameDescription.h>
#import <Contacts/CNNameSuffixDescription.h>
#import <Contacts/CNPreviousFamilyNameDescription.h>
#import <Contacts/CNNicknameNameDescription.h>
#import <Contacts/CNPhoneticGivenNameDescription.h>
#import <Contacts/CNPhoneticMiddleNameDescription.h>
#import <Contacts/CNPhoneticFamilyNameDescription.h>
#import <Contacts/CNPhoneticOrganizationNameDescription.h>
#import <Contacts/CNSortingGivenNameDescription.h>
#import <Contacts/CNSortingFamilyNameDescription.h>
#import <Contacts/CNOrganizationNameDescription.h>
#import <Contacts/CNDepartmentDescription.h>
#import <Contacts/CNJobTitleDescription.h>
#import <Contacts/CNBirthdayDescription.h>
#import <Contacts/CNNonGregorianBirthdayDescription.h>
#import <Contacts/CNCreationDateDescription.h>
#import <Contacts/CNModificationDateDescription.h>
#import <Contacts/CNNoteDescription.h>
#import <Contacts/CNSearchIndexDescription.h>
#import <Contacts/CNImageDataDescription.h>
#import <Contacts/CNCropRectDescription.h>
#import <Contacts/CNThumbnailImageDataDescription.h>
#import <Contacts/CNImageDataAvailableDescription.h>
#import <Contacts/CNLinkIdentifierDescription.h>
#import <Contacts/CNPreferredForNameDescription.h>
#import <Contacts/CNPreferredForImageDescription.h>
#import <Contacts/CNPreferredLikenessSourceDescription.h>
#import <Contacts/CNPreferredApplePersonaIdentifierDescription.h>
#import <Contacts/CNContactTypeDescription.h>
#import <Contacts/CNDisplayNameOrderDescription.h>
#import <Contacts/CNPhoneNumbersDescription.h>
#import <Contacts/CNEmailAddressesDescription.h>
#import <Contacts/CNUrlAddressesDescription.h>
#import <Contacts/CNCalendarURIsDescription.h>
#import <Contacts/CNDatesDescription.h>
#import <Contacts/CNContactRelationsDescription.h>
#import <Contacts/CNInstantMessageAddressesDescription.h>
#import <Contacts/CNSocialProfilesDescription.h>
#import <Contacts/CNPostalAddressesDescription.h>
#import <Contacts/CNPhonemeDataDescription.h>
#import <Contacts/CNAbstractActivityAlertDescription.h>
#import <Contacts/CNCallAlertDescription.h>
#import <Contacts/CNTextAlertDescription.h>
#import <Contacts/CNMapsDataDescription.h>
#import <Contacts/CNMockSpotlightIndexingLogger.h>
#import <Contacts/CNAccount.h>
#import <Contacts/CNSuggestedContactIdentifierPredicate.h>
#import <Contacts/CNMeContactsPredicate.h>
#import <Contacts/CNLDAPFetchRequest.h>
#import <Contacts/CNLDAPSearchBase.h>
#import <Contacts/CNContactsLoggerProvider.h>
#import <Contacts/CNCalculatesContactDiff.h>
#import <Contacts/CNSocialProfileContactPredicate.h>
#import <Contacts/CNActivityAlert.h>
#import <Contacts/CNMutableInstantMessageAddress.h>
#import <Contacts/CNLDAPQueryFilter.h>
#import <Contacts/CNCDContactsMatchingPredicate.h>
#import <Contacts/CNContactsUserDefaults.h>
#import <Contacts/CNCoreDataPropertyMapping.h>
#import <Contacts/CNUnifiedContacts.h>
#import <Contacts/CNCDContactWithNamePredicate.h>
#import <Contacts/CNMockLoggerProvider.h>
#import <Contacts/CNContactsLogging.h>
#import <Contacts/CNCDContactSaveExecutor.h>
#import <Contacts/CNEmailAddressContactPredicate.h>
#import <Contacts/CNLaunchServicesRemoteAdapter.h>
#import <Contacts/CNCDContainerFetcher.h>
#import <Contacts/CNCDGroupNamePredicateCreationHelper.h>
#import <Contacts/CNContactUpdate.h>
#import <Contacts/CNLDAPPropertyDescription.h>
#import <Contacts/_CNLDAPAccumulatingPropertyDescription.h>
#import <Contacts/CNChangeHistoryContactChange.h>
#import <Contacts/CNMultiValueSingleUpdate.h>
#import <Contacts/CNLDAPServices.h>
#import <Contacts/CNContainerPermissions.h>
#import <Contacts/CNContactsEnvironment.h>
#import <Contacts/CNSecureCodingClassSets.h>
#import <Contacts/CNContainerIdentifiersPredicate.h>
#import <Contacts/CNMultiValueAddUpdate.h>
#import <Contacts/CNTestSmartFetcher.h>
#import <Contacts/CNPerContactPropertyKeyDescriptor.h>
#import <Contacts/CNMutablePostalAddress.h>
#import <Contacts/CNInstantMessageAddress.h>
#import <Contacts/CNCDContactsInContainerPredicate.h>
#import <Contacts/CNMultiValueUpdate.h>
#import <Contacts/CNContactStore.h>
#import <Contacts/CNMutableContact.h>
#import <Contacts/CNContactMatchSummarizer.h>
#import <Contacts/CNCDGroupMembershipSaveExecutor.h>
#import <Contacts/CNMutableSocialProfile.h>
#import <Contacts/CNContactsUserDefaultsX.h>
#import <Contacts/CNMultiValueRemoveUpdate.h>
#import <Contacts/CNContactKeyVector.h>
#import <Contacts/CNMutableContactKeyVector.h>
#import <Contacts/CNCDContactFetchRequestDescription.h>
#import <Contacts/CNCDContactFetchRequestBuilder.h>
#import <Contacts/CNGroup.h>
#import <Contacts/CNContactFormatter.h>
#import <Contacts/CNReputationStore.h>
#import <Contacts/CNContactNameOrderImpl.h>
#import <Contacts/CNGivenNameFirstNameOrder.h>
#import <Contacts/CNFamilyNameFirstNameOrder.h>
#import <Contacts/CNContactWithNamePredicate.h>
#import <Contacts/CNReputationFutureBuilder.h>
#import <Contacts/CNABRemoteObjectsConverter.h>
#import <Contacts/CNContactRelation.h>
#import <Contacts/CNContainer.h>
#import <Contacts/CNContactSearchIndexFormatter.h>
#import <Contacts/CNDataMapperContactStore.h>
#import <Contacts/CNValueOrigin.h>
#import <Contacts/CNChangesNotifierProxy.h>
#import <Contacts/CNChangesNotifier.h>
#import <Contacts/CNChangeNotifierDarwinWrapper.h>
#import <Contacts/CNChangeNotifierDistributedCenterWrapper.h>
#import <Contacts/CNCDCustomPropertySaveExecutor.h>
#import <Contacts/CNContactNameSorting.h>
#import <Contacts/CNPhoneDialer.h>
#import <Contacts/CNSaveResponse.h>
#import <Contacts/CNMutableSaveResponse.h>
#import <Contacts/CNChangeHistoryResult.h>
#import <Contacts/CNSuggestedSaveRequest.h>
#import <Contacts/CNDonatedContactSanitizer.h>
#import <Contacts/CNCDContactsInGroupPredicate.h>
#import <Contacts/CN.h>
#import <Contacts/CNPostalAddressFormatter.h>
#import <Contacts/CNCDGroupPredicate.h>
#import <Contacts/CNSmartPropertyFetcher.h>
#import <Contacts/_CNSpotlightIndexingLogger.h>
#import <Contacts/CNTCCServices.h>
#import <Contacts/CNPostalAddressContactPredicate.h>
#import <Contacts/CNMultiValuePropertyDescription.h>
#import <Contacts/CNCompoundMultiValuePropertyDescription.h>
#import <Contacts/CNPhoneNumberContactPredicate.h>
#import <Contacts/CNDraggingContact.h>
#import <Contacts/CNReputationHandle.h>
#import <Contacts/_CNReputationGenericHandle.h>
#import <Contacts/_CNReputationEmailAddressHandle.h>
#import <Contacts/_CNReputationPhoneNumberHandle.h>
#import <Contacts/CNContactProperty.h>
#import <Contacts/CNUuidIdentifierProvider.h>
#import <Contacts/CNLabelValuePair.h>
#import <Contacts/CNReputationLogger.h>
#import <Contacts/CNContactChangesObserverProxy.h>
#import <Contacts/CNContactChangesFetcher.h>
#import <Contacts/CNContactChangesNotifier.h>
#import <Contacts/CNContact.h>
#import <Contacts/CNPermissivePolicy.h>
#import <Contacts/CNFromABCDConversions.h>
#import <Contacts/CNCDCustomPropertyValueFetcher.h>
#import <Contacts/CNCDGroupFetcher.h>
#import <Contacts/CNContactFormatterSmartFetcher.h>
#import <Contacts/CNSocialProfile.h>
#import <Contacts/CNReputationContactsAdapter.h>
#import <Contacts/CNContactMatchInfo.h>
#import <Contacts/CNMutableContainer.h>
#import <Contacts/CNMutableActivityAlert.h>
#import <Contacts/CNCDGroupsInContainerPredicate.h>
#import <Contacts/CNSuggestedContactStore.h>
#import <Contacts/CNContainerOfContactPredicate.h>
#import <Contacts/CNReputationCoreRecentsAdapter.h>
#import <Contacts/CNCDAllContactsPredicate.h>
#import <Contacts/CNLinkedContactsPredicate.h>
#import <Contacts/CNAggregateKeyDescriptor.h>
#import <Contacts/CNContactDiff.h>
#import <Contacts/CNCDSaveContext.h>
#import <Contacts/CNPropertyDescription.h>
#import <Contacts/CNContactKeyValueUpdate.h>
#import <Contacts/CNAuthorization.h>
#import <Contacts/CNPostalAddressFormattingSpecification.h>
#import <Contacts/CNContactFetchRequest.h>
#import <Contacts/CNLDAPPredicateRemapper.h>
#import <Contacts/CNMutableGroup.h>
#import <Contacts/CNVCardConstantsMapping.h>
#import <Contacts/CNCDAccessAuthorization.h>
#import <Contacts/CNInstantMessageAddressContactPredicate.h>
#import <Contacts/CNContactsWithIdentifiersPredicate.h>
#import <Contacts/CNPostalAddress.h>
#import <Contacts/_CNContactMatchingFetchRequestInfos.h>
#import <Contacts/CNErrorFactory.h>
#import <Contacts/CNMockContactsLogger.h>
#import <Contacts/CNPolicy.h>
#import <Contacts/CNReputationResult.h>
#import <Contacts/CNContactVCardSerialization.h>
#import <Contacts/CNCDRecordSaveCache.h>
#import <Contacts/CNMultiValueReplaceUpdate.h>
#import <Contacts/CNLDAPPredicateRemapping.h>
#import <Contacts/CNChangeHistoryAnchor.h>
#import <Contacts/CNDonationMapper.h>
#import <Contacts/CNCDSaveRequestExecutor.h>
#import <Contacts/CNCountryInformation.h>
#import <Contacts/CNContactMultiValueDiffUpdate.h>
#import <Contacts/CNCDInfoSaveExecutor.h>
#import <Contacts/_CNContactsLogger.h>
#import <Contacts/CNDate.h>
#import <Contacts/CNPhoneNumber.h>
#import <Contacts/CNCDAllGroupsPredicate.h>
#import <Contacts/CNMultiValueReorderUpdate.h>
#import <Contacts/CNSaveRequest.h>
#import <Contacts/CNContainerOfGroupPredicate.h>
#import <Contacts/CNLDAPTransforms.h>
#import <Contacts/CNCDAllContainersPredicate.h>
#import <Contacts/CNPredicateValidator.h>
#import <Contacts/CNCDContactsLinkedToContactPredicate.h>
#import <Contacts/_CNRegulatoryLogger.h>
#import <Contacts/CNAddressFormats.h>
#import <Contacts/CNCDGroupSaveExecutor.h>
#import <Contacts/CNDictionaryPolicy.h>
#import <Contacts/CNCDInfoFetcher.h>
#import <Contacts/CNCDContactFetcher.h>
#import <Contacts/CNCoreDataMapperX.h>

void* CNLinkedOnOrAfter(void);
void* CNLinkedOnOrAfterSimulateLinkedBefore(void);

#endif
