/* Fake DTrace probes */

#define MAGMALLOC_MADVFREEREGION(...)
#define MAGMALLOC_DEALLOCREGION(...)
#define MAGMALLOC_RECIRCREGION(...)
#define MAGMALLOC_DEPOTREGION(...)
#define MAGMALLOC_ALLOCREGION(...)
#define MAGMALLOC_PRESSURERELIEF(...)

