/* Fake DTrace probes */

#define MAGMALLOC_MADVFREEREGION(...)
#define MAGMALLOC_DEALLOCREGION(...)
#define MAGMALLOC_RECIRCREGION(...)
#define MAGMALLOC_DEPOTREGION(...)
#define MAGMALLOC_ALLOCREGION(...)
#define MAGMALLOC_PRESSURERELIEF(...)
#define MAGMALLOC_MALLOCERRORBREAK(...)
#define MAGMALLOC_PRESSURERELIEFBEGIN(...)
#define MAGMALLOC_PRESSURERELIEFEND(...)
