section text

global __error
extern __errno_location
__error:
	jmp __errno_location WRT ..plt

global _ZNSt13basic_filebufIwSt11char_traitsIwEE7seekoffExSt12_Ios_SeekdirSt13_Ios_Openmode
extern _ZNSt13basic_filebufIwSt11char_traitsIwEE7seekoffElSt12_Ios_SeekdirSt13_Ios_Openmode
_ZNSt13basic_filebufIwSt11char_traitsIwEE7seekoffExSt12_Ios_SeekdirSt13_Ios_Openmode:
	jmp _ZNSt13basic_filebufIwSt11char_traitsIwEE7seekoffElSt12_Ios_SeekdirSt13_Ios_Openmode WRT ..plt

global _ZNSt13basic_filebufIcSt11char_traitsIcEE7seekoffExSt12_Ios_SeekdirSt13_Ios_Openmode
extern _ZNSt13basic_filebufIcSt11char_traitsIcEE7seekoffElSt12_Ios_SeekdirSt13_Ios_Openmode
_ZNSt13basic_filebufIcSt11char_traitsIcEE7seekoffExSt12_Ios_SeekdirSt13_Ios_Openmode:
	jmp _ZNSt13basic_filebufIcSt11char_traitsIcEE7seekoffElSt12_Ios_SeekdirSt13_Ios_Openmode WRT ..plt

global _ZNSi5seekgExSt12_Ios_Seekdir
extern _ZNSi5seekgElSt12_Ios_Seekdir
_ZNSi5seekgExSt12_Ios_Seekdir:
	jmp _ZNSi5seekgElSt12_Ios_Seekdir WRT ..plt

global _ZNSt13basic_istreamIwSt11char_traitsIwEE5seekgExSt12_Ios_Seekdir
extern _ZNSt13basic_istreamIwSt11char_traitsIwEE5seekgElSt12_Ios_Seekdir
_ZNSt13basic_istreamIwSt11char_traitsIwEE5seekgExSt12_Ios_Seekdir:
	jmp _ZNSt13basic_istreamIwSt11char_traitsIwEE5seekgElSt12_Ios_Seekdir WRT ..plt

global _ZNSo5seekpExSt12_Ios_Seekdir
extern _ZNSo5seekpElSt12_Ios_Seekdir
_ZNSo5seekpExSt12_Ios_Seekdir:
	jmp _ZNSo5seekpElSt12_Ios_Seekdir WRT ..plt

global _ZNSt13basic_ostreamIwSt11char_traitsIwEE5seekpExSt12_Ios_Seekdir
extern _ZNSt13basic_ostreamIwSt11char_traitsIwEE5seekpElSt12_Ios_Seekdir
_ZNSt13basic_ostreamIwSt11char_traitsIwEE5seekpExSt12_Ios_Seekdir:
	jmp _ZNSt13basic_ostreamIwSt11char_traitsIwEE5seekpElSt12_Ios_Seekdir WRT ..plt

global _ZNSt15basic_stringbufIcSt11char_traitsIcESaIcEE7seekoffExSt12_Ios_SeekdirSt13_Ios_Openmode
extern _ZNSt15basic_stringbufIcSt11char_traitsIcESaIcEE7seekoffElSt12_Ios_SeekdirSt13_Ios_Openmode
_ZNSt15basic_stringbufIcSt11char_traitsIcESaIcEE7seekoffExSt12_Ios_SeekdirSt13_Ios_Openmode:
	jmp _ZNSt15basic_stringbufIcSt11char_traitsIcESaIcEE7seekoffElSt12_Ios_SeekdirSt13_Ios_Openmode WRT ..plt

global _ZNSt15basic_stringbufIwSt11char_traitsIwESaIwEE7seekoffExSt12_Ios_SeekdirSt13_Ios_Openmode
extern _ZNSt15basic_stringbufIwSt11char_traitsIwESaIwEE7seekoffElSt12_Ios_SeekdirSt13_Ios_Openmode
_ZNSt15basic_stringbufIwSt11char_traitsIwESaIwEE7seekoffExSt12_Ios_SeekdirSt13_Ios_Openmode:
	jmp _ZNSt15basic_stringbufIwSt11char_traitsIwESaIwEE7seekoffElSt12_Ios_SeekdirSt13_Ios_Openmode WRT ..plt

global _ZNSt15basic_streambufIcSt11char_traitsIcEE7seekoffExSt12_Ios_SeekdirSt13_Ios_Openmode
extern _ZNSt15basic_streambufIcSt11char_traitsIcEE7seekoffElSt12_Ios_SeekdirSt13_Ios_Openmode
_ZNSt15basic_streambufIcSt11char_traitsIcEE7seekoffExSt12_Ios_SeekdirSt13_Ios_Openmode:
	jmp _ZNSt15basic_streambufIcSt11char_traitsIcEE7seekoffElSt12_Ios_SeekdirSt13_Ios_Openmode WRT ..plt

global _ZNSt15basic_streambufIcSt11char_traitsIcEE10pubseekoffExSt12_Ios_SeekdirSt13_Ios_Openmode
extern _ZNSt15basic_streambufIcSt11char_traitsIcEE10pubseekoffElSt12_Ios_SeekdirSt13_Ios_Openmode
_ZNSt15basic_streambufIcSt11char_traitsIcEE10pubseekoffExSt12_Ios_SeekdirSt13_Ios_Openmode:
	jmp _ZNSt15basic_streambufIcSt11char_traitsIcEE10pubseekoffElSt12_Ios_SeekdirSt13_Ios_Openmode WRT ..plt

global _ZNSt15basic_streambufIwSt11char_traitsIwEE7seekoffExSt12_Ios_SeekdirSt13_Ios_Openmode
extern _ZNSt15basic_streambufIwSt11char_traitsIwEE7seekoffElSt12_Ios_SeekdirSt13_Ios_Openmode
_ZNSt15basic_streambufIwSt11char_traitsIwEE7seekoffExSt12_Ios_SeekdirSt13_Ios_Openmode:
	jmp _ZNSt15basic_streambufIwSt11char_traitsIwEE7seekoffElSt12_Ios_SeekdirSt13_Ios_Openmode WRT ..plt

global _ZNSt15basic_streambufIwSt11char_traitsIwEE10pubseekoffExSt12_Ios_SeekdirSt13_Ios_Openmode
extern _ZNSt15basic_streambufIwSt11char_traitsIwEE10pubseekoffElSt12_Ios_SeekdirSt13_Ios_Openmode
_ZNSt15basic_streambufIwSt11char_traitsIwEE10pubseekoffExSt12_Ios_SeekdirSt13_Ios_Openmode:
	jmp _ZNSt15basic_streambufIwSt11char_traitsIwEE10pubseekoffElSt12_Ios_SeekdirSt13_Ios_Openmode WRT ..plt

global _ZNSt12strstreambuf7seekoffExSt12_Ios_SeekdirSt13_Ios_Openmode
extern _ZNSt12strstreambuf7seekoffElSt12_Ios_SeekdirSt13_Ios_Openmode
_ZNSt12strstreambuf7seekoffExSt12_Ios_SeekdirSt13_Ios_Openmode:
	jmp _ZNSt12strstreambuf7seekoffElSt12_Ios_SeekdirSt13_Ios_Openmode WRT ..plt

global opendir$INODE64
extern opendir
opendir$INODE64:
	jmp opendir WRT ..plt

global CC_MD5_Init
extern MD5_Init
CC_MD5_Init:
	jmp MD5_Init WRT ..plt

global CC_MD5_Update
extern MD5_Update
CC_MD5_Update:
	jmp MD5_Update WRT ..plt

global CC_MD5_Final
extern MD5_Final
CC_MD5_Final:
	jmp MD5_Final WRT ..plt

global CC_MD5
extern MD5
CC_MD5:
	jmp MD5 WRT ..plt

global __darwin_atexit
extern __cxa_atexit
__darwin_atexit:
	jmp __cxa_atexit WRT ..plt

global __darwin_select$1050
extern __darwin_select
__darwin_select$1050:
	jmp __darwin_select WRT ..plt

global __darwin_warn
extern __darwin__warn
__darwin_warn:
	jmp __darwin__warn WRT ..plt

global __darwin_err
extern __darwin__err
__darwin_err:
	jmp __darwin__err WRT ..plt

global __darwin_opendir$INODE64
extern __darwin_opendir
__darwin_opendir$INODE64:
	jmp __darwin_opendir WRT ..plt

global __darwin_rewinddir$INODE64
extern rewinddir
__darwin_rewinddir$INODE64:
	jmp rewinddir WRT ..plt

global __darwin_rewinddir
extern rewinddir
__darwin_rewinddir:
	jmp rewinddir WRT ..plt

global __darwin_telldir$INODE64
extern telldir
__darwin_telldir$INODE64:
	jmp telldir WRT ..plt

global __darwin_curl_mfprintf
extern __darwin_fprintf
__darwin_curl_mfprintf:
	jmp __darwin_fprintf WRT ..plt

global __darwin_curl_mvfprintf
extern __darwin_vfprintf
__darwin_curl_mvfprintf:
	jmp __darwin_vfprintf WRT ..plt

global realpath$DARWIN_EXTSN
extern __darwin_realpath
realpath$DARWIN_EXTSN:
	jmp __darwin_realpath WRT ..plt

global libintl_gettext
extern gettext
libintl_gettext:
	jmp gettext WRT ..plt

global libintl_dgettext
extern dgettext
libintl_dgettext:
	jmp dgettext WRT ..plt

global libintl_ngettext
extern ngettext
libintl_ngettext:
	jmp ngettext WRT ..plt

global libintl_dngettext
extern dngettext
libintl_dngettext:
	jmp dngettext WRT ..plt

global libintl_dcngettext
extern dcngettext
libintl_dcngettext:
	jmp dcngettext WRT ..plt

global libintl_textdomain
extern textdomain
libintl_textdomain:
	jmp textdomain WRT ..plt

global libintl_bindtextdomain
extern bindtextdomain
libintl_bindtextdomain:
	jmp bindtextdomain WRT ..plt

global libintl_bind_textdomain_codeset
extern bind_textdomain_codeset
libintl_bind_textdomain_codeset:
	jmp bind_textdomain_codeset WRT ..plt

global libintl_setlocale
extern setlocale
libintl_setlocale:
	jmp setlocale WRT ..plt

