.\" Copyright (C) 2000 Jason Evans <jasone@FreeBSD.org>.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice(s), this list of conditions and the following disclaimer as
.\"    the first lines of this file unmodified other than the possible
.\"    addition of one or more copyright notices.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice(s), this list of conditions and the following disclaimer in
.\"    the documentation and/or other materials provided with the
.\"    distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER(S) ``AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDER(S) BE
.\" LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
.\" WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
.\" OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
.\" EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\" $FreeBSD: src/lib/libc_r/man/pthread_schedparam.3,v 1.2.2.4 2001/08/17 15:42:52 ru Exp $
.Dd May 1, 2000
.Dt PTHREAD_SCHEDPARAM 3
.Os
.Sh NAME
.Nm pthread_getschedparam ,
.Nm pthread_setschedparam
.Nd thread scheduling parameter manipulation
.Sh SYNOPSIS
.Fd #include <pthread.h>
.Ft int
.Fo pthread_getschedparam
.Fa "pthread_t thread"
.Fa "int *restrict policy"
.Fa "struct sched_param *restrict param"
.Fc
.Ft int
.Fo pthread_setschedparam
.Fa "pthread_t thread"
.Fa "int policy"
.Fa "const struct sched_param *param"
.Fc
.Sh DESCRIPTION
The
.Fn pthread_getschedparam
and
.Fn pthread_setschedparam
functions get and set the scheduling parameters of individual threads.
The scheduling policy for a thread can either be
.Dv SCHED_FIFO
(first in, first out) or
.Dv SCHED_RR
(round-robin).
The thread priority (accessed via
.Va param->sched_priority )
must be at least
.Dv PTHREAD_MIN_PRIORITY
and no more than
.Dv PTHREAD_MAX_PRIORITY .
.Sh RETURN VALUES
If successful, these functions return 0.
Otherwise, an error number is returned to indicate the error.
.Sh ERRORS
.Fn pthread_getschedparam
will fail if:
.Bl -tag -width Er
.It Bq Er ESRCH
Non-existent thread
.Va thread .
.El
.Pp
.Fn pthread_setschedparam
will fail if:
.Bl -tag -width Er
.It Bq Er EINVAL
Invalid value for
.Va policy .
.It Bq Er ENOTSUP
Invalid value for scheduling parameters.
.It Bq Er ESRCH
Non-existent thread
.Va thread .
.El
.Sh STANDARDS
.Fn pthread_setschedparam
and
.Fn pthread_getschedparam
conform to
.St -susv2
