.Dd April 17, 2006
.Dt DLERROR 3
.Sh NAME
.Nm dlerror
.Nd get diagnostic information
.Sh SYNOPSIS
.In dlfcn.h
.Ft const char*
.Fn dlerror "void"
.Sh DESCRIPTION
.Fn dlerror
returns a null-terminated character string describing the last error that
occurred on this thread during a call to
.Fn dlopen ,
.Fn dlopen_preflight ,
.Fn dlsym ,
or
.Fn dlclose .
If no such error has occurred,
.Fn dlerror
returns a null pointer.
At each call to
.Fn dlerror ,
the error indication is reset.  Thus in the case of two calls
to
.Fn dlerror ,
where the second call follows the first immediately, the second call
will always return a null pointer.
.Sh SEE ALSO
.Xr dlopen 3
.Xr dlopen_preflight 3
.Xr dlclose 3
.Xr dlsym 3
.Xr dyld 3
