#ifndef XPC_LAUNCHD_H
#define XPC_LAUNCHD_H

typedef int xpc_service_type_t;
typedef int xpc_jetsam_band_t;
typedef char event_name_t[100];

enum {
	XPC_JETSAM_BAND_SUSPENDED,
	XPC_JETSAM_BAND_BACKGROUND_OPPORTUNISTIC,
	XPC_JETSAM_BAND_BACKGROUND,
	XPC_JETSAM_BAND_MAIL,
	XPC_JETSAM_BAND_PHONE,
	XPC_JETSAM_BAND_UI_SUPPORT,
	XPC_JETSAM_BAND_FOREGROUND_SUPPORT,
	XPC_JETSAM_BAND_FOREGROUND,
	XPC_JETSAM_BAND_AUDIO,
	XPC_JETSAM_BAND_ACCESSORY,
	XPC_JETSAM_BAND_CRITICAL,
	XPC_JETSAM_BAND_TELEPHONY,
};

enum {
	JETSAM_PRIORITY_IDLE,
	JETSAM_PRIORITY_BACKGROUND_OPPORTUNISTIC,
	JETSAM_PRIORITY_BACKGROUND,
	JETSAM_PRIORITY_MAIL,
	JETSAM_PRIORITY_PHONE,
	JETSAM_PRIORITY_UI_SUPPORT,
	JETSAM_PRIORITY_FOREGROUND_SUPPORT,
	JETSAM_PRIORITY_FOREGROUND,
	JETSAM_PRIORITY_AUDIO_AND_ACCESSORY,
	JETSAM_PRIORITY_CRITICAL,
	JETSAM_PRIORITY_TELEPHONY,
};

#define XPC_SERVICE_ENV_ATTACHED "XPC_SERVICE_ENV_ATTACHED"
#define XPC_SERVICE_RENDEZVOUS_TOKEN "XPC_SERVICE_RENDEZVOUS_TOKEN"

#define XPC_EVENT_ROUTINE_KEY_STREAM "STREAM"
#define XPC_EVENT_ROUTINE_KEY_TOKEN "TOKEN"
#define XPC_EVENT_ROUTINE_KEY_NAME "NAME"
#define XPC_EVENT_ROUTINE_KEY_ENTITLEMENTS "ENTITLEMENTS"
#define XPC_EVENT_ROUTINE_KEY_EVENT "EVENT"
#define XPC_EVENT_ROUTINE_KEY_FLAGS "FLAGS"

#define XPC_EVENT_FLAG_ENTITLEMENTS 1

#define EXNOMEM 12
#define EXINVAL 22

#endif

