/*
 * This file is statically generated by running:
 *   cc -arch i386 -D_LIBC_NO_FEATURE_VERIFICATION -DRUNEOFF32 -o rune32 locale/FreeBSD/rune.c
 */

#define SIZEOF32_RUNEENTRY 16
#define SIZEOF32_RUNELOCALE 3164
int off32[] = {
	40,
	44,
	3124,
	3128,
	3132,
	3136,
	3140,
	3144,
	3148,
	3160,
	3164,
};
