/*
 This file is part of Darling.

 Copyright (C) 2019 Lubos Dolezel

 Darling is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Darling is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Darling.  If not, see <http://www.gnu.org/licenses/>.
*/


#ifndef _MapKit_H_
#define _MapKit_H_

#import <Foundation/Foundation.h>

#import <MapKit/CAAnimationDelegate.h>
#import <MapKit/CALayerDelegate.h>
#import <MapKit/CLLocationManagerDelegate.h>
#import <MapKit/GEOEncyclopedicInfo.h>
#import <MapKit/GEOLogContextDelegate.h>
#import <MapKit/GEOMapItem.h>
#import <MapKit/GEOResourceManifestTileGroupObserver.h>
#import <MapKit/GEOTransitArtworkDataSource.h>
#import <MapKit/GEOTransitIconDataSource.h>
#import <MapKit/GEOTransitLabelItem.h>
#import <MapKit/GEOTransitShieldDataSource.h>
#import <MapKit/GEOURLSerializable.h>
#import <MapKit/GEOUsageKeypressEventProtocol.h>
#import <MapKit/MKActionRowItemViewDelegate.h>
#import <MapKit/MKActivityItemSocialSource.h>
#import <MapKit/MKActivityItemSource.h>
#import <MapKit/MKAnnotation.h>
#import <MapKit/MKAnnotationContainerViewDelegate.h>
#import <MapKit/MKAnnotationManagerDelegate.h>
#import <MapKit/MKAnnotationMarkerContainer.h>
#import <MapKit/MKAnnotationModel.h>
#import <MapKit/MKAnnotationPrivate.h>
#import <MapKit/MKAnnotationRepresentation.h>
#import <MapKit/MKAnnotationSelector.h>
#import <MapKit/MKArtworkImageSource.h>
#import <MapKit/MKAutocompleteAnalyticsProvider.h>
#import <MapKit/MKAutocompleteAnalyticsState.h>
#import <MapKit/MKCustomFeatureAnnotation.h>
#import <MapKit/MKDynamicTransitUIContainer.h>
#import <MapKit/MKETAProviderDelegate.h>
#import <MapKit/MKETAProviderObserver.h>
#import <MapKit/MKInactiveTransitLine.h>
#import <MapKit/MKInfoCardTheme.h>
#import <MapKit/MKInfoCardThemeListener.h>
#import <MapKit/MKLocatableObject.h>
#import <MapKit/MKLocationManagerObserver.h>
#import <MapKit/MKLocationManagerOperation.h>
#import <MapKit/MKLocationProvider.h>
#import <MapKit/MKLocationProviderDelegate.h>
#import <MapKit/MKMapGestureControllerDelegate.h>
#import <MapKit/MKMapItemProviderRatingSnippet.h>
#import <MapKit/MKMapServiceCategoriesTicket.h>
#import <MapKit/MKMapServiceProblemReportTicket.h>
#import <MapKit/MKMapServiceSearchFieldPlaceholderTicket.h>
#import <MapKit/MKMapServiceSearchTicket.h>
#import <MapKit/MKMapServiceTicket.h>
#import <MapKit/MKMapServiceTransitLineTicket.h>
#import <MapKit/MKMapServiceWalletMerchantTicket.h>
#import <MapKit/MKModuleViewControllerProtocol.h>
#import <MapKit/MKMouseOverLabelRecognizerDelegate.h>
#import <MapKit/MKMouseOverLabelTarget.h>
#import <MapKit/MKMultiLineLabelContainer.h>
#import <MapKit/MKMultilineText.h>
#import <MapKit/MKOfflineModeViewController.h>
#import <MapKit/MKOrientable.h>
#import <MapKit/MKOverlay.h>
#import <MapKit/MKOverlayContainerViewDelegate.h>
#import <MapKit/MKPlaceActionManagerProtocol.h>
#import <MapKit/MKPlaceAttributionCellButtonDelegate.h>
#import <MapKit/MKPlaceAttributionCellDelegate.h>
#import <MapKit/MKPlaceCardActionControllerDelegate.h>
#import <MapKit/MKPlaceCardActionSectionViewDelegate.h>
#import <MapKit/MKPlaceCardEncyclopedicControllerDelegate.h>
#import <MapKit/MKPlaceCardHeaderViewControllerDelegate.h>
#import <MapKit/MKPlaceCardPhotosControllerDelegate.h>
#import <MapKit/MKPlaceCardReviewsControllerDelegate.h>
#import <MapKit/MKPlaceEncyclopedicRowViewItem.h>
#import <MapKit/MKPlaceHeaderButtonsViewControllerDelegate.h>
#import <MapKit/MKPlaceSectionViewDelegate.h>
#import <MapKit/MKPlaceServiceHoursViewControllerProtocol.h>
#import <MapKit/MKQuickRouteConfigurableView.h>
#import <MapKit/MKQuickRouteManagerDelegate.h>
#import <MapKit/MKQuickRouteTransportTypeFinding.h>
#import <MapKit/MKRotationFilterDelegate.h>
#import <MapKit/MKStackingViewControllerDelegate.h>
#import <MapKit/MKStackingViewControllerFixedHeightAware.h>
#import <MapKit/MKStackingViewControllerSizableView.h>
#import <MapKit/MKTransitAttributionViewControllerDelegate.h>
#import <MapKit/MKTransitDeparturesCellDelegate.h>
#import <MapKit/MKTransitDepaturesViewControllerDelegate.h>
#import <MapKit/MKTransitLineMarker.h>
#import <MapKit/NSAccessibilityButton.h>
#import <MapKit/NSAccessibilityElement.h>
#import <MapKit/NSControlTextEditingDelegate.h>
#import <MapKit/NSGestureRecognizerDelegate.h>
#import <MapKit/NSSharingServiceDelegate.h>
#import <MapKit/NSSharingServicePickerDelegate.h>
#import <MapKit/NSTableViewDataSource.h>
#import <MapKit/NSTableViewDelegate.h>
#import <MapKit/VKAnnotation.h>
#import <MapKit/VKCustomFeatureAnnotation.h>
#import <MapKit/VKCustomFeatureDataSource.h>
#import <MapKit/VKMapViewDelegate.h>
#import <MapKit/VKPuckAnimatorTarget.h>
#import <MapKit/VKRouteMatchedAnnotationPresentation.h>
#import <MapKit/VKTrackableAnnotationPresentation.h>
#import <MapKit/_MKAnimationStackViewDelegate.h>
#import <MapKit/_MKBalloonCalloutViewConfiguring.h>
#import <MapKit/_MKCalloutAccessoryView.h>
#import <MapKit/_MKClickableTableViewDelegate.h>
#import <MapKit/_MKInfoCardAnalyticsDelegate.h>
#import <MapKit/_MKInfoCardChildViewControllerAnalyticsDelegate.h>
#import <MapKit/_MKInfoCardController.h>
#import <MapKit/_MKKVOProxyDelegate.h>
#import <MapKit/_MKMapViewSuspendedEffectsToken.h>
#import <MapKit/_MKPinAnnotationViewDelegate.h>
#import <MapKit/_MKPlaceActionButtonControllerProtocol.h>
#import <MapKit/_MKPlaceItem.h>
#import <MapKit/_MKStackViewDelegate.h>
#import <MapKit/_MKTransitConnectionCellDelegate.h>
#import <MapKit/_MKWiFiObserverDelegate.h>
#import <MapKit/_MXExtensionBaseMapService.h>
#import <MapKit/_MXExtensionContextType.h>
#import <MapKit/_MXExtensionHostContextType.h>
#import <MapKit/_MXExtensionHostViewControlling.h>
#import <MapKit/_MXExtensionInternalServiceProtocol.h>
#import <MapKit/_MXExtensionInternalStreamingServiceProtocol.h>
#import <MapKit/_MXExtensionLookupPolicy.h>
#import <MapKit/_MXExtensionRequestDispatching.h>
#import <MapKit/_MXExtensionRequestHandling.h>
#import <MapKit/_MXExtensionResponseObserver.h>
#import <MapKit/_MXExtensionStreamingRequestDispatching.h>
#import <MapKit/_MXExtensionStreamingRequestHandling.h>
#import <MapKit/_MXExtensionURLHandling.h>
#import <MapKit/_MXExtensionVendorContextType.h>
#import <MapKit/_MXExtensionVendorViewControlling.h>
#import <MapKit/_MXExtensionViewControlling.h>
#import <MapKit/MKMouseOverLabelRecognizer.h>
#import <MapKit/MKURLParser.h>
#import <MapKit/MKPlaceSectionHeaderView.h>
#import <MapKit/MKMapGestureController.h>
#import <MapKit/_MKConditionalPanGestureRecognizer.h>
#import <MapKit/_MKDirectionalPanGestureRecognizer.h>
#import <MapKit/_MKMouseDownGestureRecognizer.h>
#import <MapKit/_MKMagnificationGestureRecognizer.h>
#import <MapKit/_MKRotationGestureRecognizer.h>
#import <MapKit/_MKDirectionalArrowRecognizer.h>
#import <MapKit/MKMapSnapshotCreator.h>
#import <MapKit/MKArtworkImageView.h>
#import <MapKit/MKLocationManager.h>
#import <MapKit/MKLocationManagerSingleUpdater.h>
#import <MapKit/_MKWiFiObserver.h>
#import <MapKit/MKThrottledGate.h>
#import <MapKit/MKPlaceHoursViewController.h>
#import <MapKit/MKPlaceHoursDayRow.h>
#import <MapKit/MKPlaceMessageHoursViewController.h>
#import <MapKit/MKRotationFilter.h>
#import <MapKit/_MXExtensionVendorContext.h>
#import <MapKit/_MKPinAnnotationViewImageCache.h>
#import <MapKit/_MKPinAnnotationViewImageCacheKey.h>
#import <MapKit/MKTransitIncidentSummaryCell.h>
#import <MapKit/MKPlaceTextCell.h>
#import <MapKit/_GEOTransitLineMarker.h>
#import <MapKit/MKTransitDeparturesViewController.h>
#import <MapKit/MKImageTextAttachment.h>
#import <MapKit/MKBlurBackedControlProxy.h>
#import <MapKit/MKBlurBackedControlView.h>
#import <MapKit/MKToVKOverlayAdaptor.h>
#import <MapKit/_MKStackView.h>
#import <MapKit/MKUserLocationAnnotationViewProxy.h>
#import <MapKit/_MKTableViewController.h>
#import <MapKit/_MKClickableTableView.h>
#import <MapKit/_MKClickableTableViewController.h>
#import <MapKit/_MKTableViewControllerRootView.h>
#import <MapKit/_MKMapItemPlaceItem.h>
#import <MapKit/_MKContactPlaceItem.h>
#import <MapKit/MKTransitInfoLabelView.h>
#import <MapKit/MKDirectionsResponse.h>
#import <MapKit/MKRoute.h>
#import <MapKit/MKRouteStep.h>
#import <MapKit/MKRoutePolyline.h>
#import <MapKit/MKRouteStepPolyline.h>
#import <MapKit/MKETAResponse.h>
#import <MapKit/MKCustomSeparatorTableViewCell.h>
#import <MapKit/MKPhotoSmallAttributionView.h>
#import <MapKit/MKPhotoBigAttributionView.h>
#import <MapKit/MKPlacePhotosViewController.h>
#import <MapKit/_MXSerialQueue.h>
#import <MapKit/MKMapItemMetadata.h>
#import <MapKit/MKOrientationContext.h>
#import <MapKit/MKAnnotationContainerView.h>
#import <MapKit/_MXExtensionRideSharingSearchRequest.h>
#import <MapKit/_MXExtensionRideSharingSearchResponse.h>
#import <MapKit/_MXExtensionRideSharingRide.h>
#import <MapKit/MKMapItemPhoto.h>
#import <MapKit/_MKTransitInactiveLine.h>
#import <MapKit/MKTransitInactiveLinesSectionController.h>
#import <MapKit/_MKMapItemAttribution.h>
#import <MapKit/_MKMapItemPlaceAttribution.h>
#import <MapKit/_MKMapItemPhotosAttribution.h>
#import <MapKit/_MKMapItemReviewsAttribution.h>
#import <MapKit/MKTransitIncidentStringProvider.h>
#import <MapKit/MKPlaceInfoContactRowView.h>
#import <MapKit/MKPlaceInfoPhoneNumberView.h>
#import <MapKit/MKPlaceInfoURLRowView.h>
#import <MapKit/MKPlaceInfoEmailRowView.h>
#import <MapKit/MKPlaceInfoPostalAddressRowView.h>
#import <MapKit/MKPlaceInfoBusinessMessageRowView.h>
#import <MapKit/MKAccessiblePlatterView.h>
#import <MapKit/_MKMultiPartLabelCacheKey.h>
#import <MapKit/_MKTokenAttributedString.h>
#import <MapKit/_MKLineHeaderModel.h>
#import <MapKit/_MKDataHeaderModel.h>
#import <MapKit/MKUserLocationView.h>
#import <MapKit/MKModernUserLocationView.h>
#import <MapKit/_MKGemUserLocationView.h>
#import <MapKit/MKPlaceReviewsViewController.h>
#import <MapKit/MKImageView.h>
#import <MapKit/MKZoomSegmentedControl.h>
#import <MapKit/_MXExtensionRequestDispatcher.h>
#import <MapKit/MKAttributedStringBlendingConfiguration.h>
#import <MapKit/MKMapSnapshotFeatureAnnotation.h>
#import <MapKit/MKCompassView.h>
#import <MapKit/MKTransitItemIncidentCell.h>
#import <MapKit/MKEmptyTextAttachment.h>
#import <MapKit/MKResizedArtworkDataSourceCache.h>
#import <MapKit/MKTransitDeparturesSectionHeaderView.h>
#import <MapKit/_MKPlaceViewController.h>
#import <MapKit/MKMouseOverActionView.h>
#import <MapKit/MKBlurBackingView.h>
#import <MapKit/MKTrailingAlignedButtonCell.h>
#import <MapKit/MKTrailingAlignedButton.h>
#import <MapKit/_MKRightImageButton.h>
#import <MapKit/_MKBalloonContainerView.h>
#import <MapKit/_MKBalloonCalloutView.h>
#import <MapKit/MKTrafficSupport.h>
#import <MapKit/MKPlaceHeaderButton.h>
#import <MapKit/MKResizableImage.h>
#import <MapKit/MKLocalSearchCompletion.h>
#import <MapKit/MKLocalSearchCompleter.h>
#import <MapKit/MKLabelMarker.h>
#import <MapKit/MKSmallCalloutView.h>
#import <MapKit/_MKSmallCalloutPassthroughButton.h>
#import <MapKit/_MKSmallCalloutContainerView.h>
#import <MapKit/_MKCalloutAccessoryWrapperView.h>
#import <MapKit/_MKCalloutDetailWrapperView.h>
#import <MapKit/MKMultiPartAttributedString.h>
#import <MapKit/MKTransitItemIncidentsController.h>
#import <MapKit/MKTransitArtwork.h>
#import <MapKit/MKTransitShield.h>
#import <MapKit/MKTransitIcon.h>
#import <MapKit/_NSImageRepAdaptiveToScale.h>
#import <MapKit/_NSImageAdaptiveToScale.h>
#import <MapKit/MKThreadContext.h>
#import <MapKit/MKQuadTrie.h>
#import <MapKit/MKTransitLoadingTableViewCell.h>
#import <MapKit/_MXExtensionContext.h>
#import <MapKit/MKMultiPartLabel.h>
#import <MapKit/MKCoreLocationProvider.h>
#import <MapKit/MKLinkTextField.h>
#import <MapKit/MKInfoCardDetailView.h>
#import <MapKit/MKVibrancyAwareLabelView.h>
#import <MapKit/_MKSortedDepartureCollection.h>
#import <MapKit/MKTransitDeparturesSectionController.h>
#import <MapKit/MKPlaceReservationRowView.h>
#import <MapKit/MKCALayerCompletionDelegate.h>
#import <MapKit/MKLayer.h>
#import <MapKit/MKURLSerializer.h>
#import <MapKit/MKPlaceCardFooterActionsViewController.h>
#import <MapKit/_MKSpatialColliderPairSet.h>
#import <MapKit/MKSpatialCollider.h>
#import <MapKit/_MXExtensionLookupPolicy.h>
#import <MapKit/_MXExtensionManager.h>
#import <MapKit/MKLocalSearchKeypressMetrics.h>
#import <MapKit/MKInfoCardThemeManager.h>
#import <MapKit/_MKLocalizedHoursBuilder.h>
#import <MapKit/MKImageAttachmentCell.h>
#import <MapKit/MKSystemController.h>
#import <MapKit/_MKPlaceReservationInfo.h>
#import <MapKit/_MKLocationShifter.h>
#import <MapKit/MKURLHandler.h>
#import <MapKit/GEOEncyclopedicInfoUserLocation.h>
#import <MapKit/MKPlaceEncyclopedicTextItem.h>
#import <MapKit/MKPlaceEncyclopedicFactoidView.h>
#import <MapKit/MKPlaceEncyclopedicRowView.h>
#import <MapKit/MKPlaceEncyclopedicViewController.h>
#import <MapKit/MKIconManager.h>
#import <MapKit/_MKIconDiskCache.h>
#import <MapKit/MKMapAttribution.h>
#import <MapKit/MKMapAttributionImage.h>
#import <MapKit/_MKDistanceDetailProvider.h>
#import <MapKit/_MKMapItemUserRatingSnippetReview.h>
#import <MapKit/_MKMapItemUserRatingSnippetTip.h>
#import <MapKit/MKMapItem.h>
#import <MapKit/MKMapView.h>
#import <MapKit/_MKAnnotationDragGestureRecognizer.h>
#import <MapKit/_MKMapViewSuspendedEffectsToken.h>
#import <MapKit/MKPlaceSectionRowView.h>
#import <MapKit/MKMapItemIdentifier.h>
#import <MapKit/MKBlurBackingLayer.h>
#import <MapKit/_MXExtensionHostContext.h>
#import <MapKit/MKEmptyTextAttachmentCell.h>
#import <MapKit/MKPlaceSectionViewController.h>
#import <MapKit/MKPointAnnotation.h>
#import <MapKit/_MKPlaceInlineMapCustomFeature.h>
#import <MapKit/MKPlaceInlineMapViewController.h>
#import <MapKit/_MKPlaceInlineMapContentView.h>
#import <MapKit/MKPlacePoisInlineMapViewController.h>
#import <MapKit/_MKPlacePoisInlineMapContentView.h>
#import <MapKit/MKTransitAttributionViewController.h>
#import <MapKit/MKPlacemark.h>
#import <MapKit/MKActionRowItemButton.h>
#import <MapKit/MKActionRowItemView.h>
#import <MapKit/MKPlaceCardActionsRowViewController.h>
#import <MapKit/_MXExtensionBaseMapRequest.h>
#import <MapKit/_MXExtensionBaseMapFeature.h>
#import <MapKit/_MXExtensionBaseMapNamedImage.h>
#import <MapKit/_MXExtensionBaseMapResponse.h>
#import <MapKit/_MXExtensionBaseMapServiceRequestDispatcher.h>
#import <MapKit/MKTransitLineIncidentsViewController.h>
#import <MapKit/MKTransitDeparturesCell.h>
#import <MapKit/MKMapCamera.h>
#import <MapKit/_MKLeadingAlignedButtonCell.h>
#import <MapKit/_MKLeadingAlignedButton.h>
#import <MapKit/_MKLabelMarkerItem.h>
#import <MapKit/MKSearchCompletion.h>
#import <MapKit/MKAnnotationManager.h>
#import <MapKit/MKClusterAnnotation.h>
#import <MapKit/MKURLBuilder.h>
#import <MapKit/MKTableViewCell.h>
#import <MapKit/_MKUILabel.h>
#import <MapKit/MKUILabelNoAutoFontSmoothingBackground.h>
#import <MapKit/_MKJunctionElement.h>
#import <MapKit/MKJunction.h>
#import <MapKit/MKLocalSearch.h>
#import <MapKit/MKTransitMessageCell.h>
#import <MapKit/MKTransitSystemCell.h>
#import <MapKit/MKLocalSearchRequest.h>
#import <MapKit/_MKLocalSearchMerchantParameters.h>
#import <MapKit/_MKLocalSearchExternalTransitLookupParameters.h>
#import <MapKit/MKWalletRAPReport.h>
#import <MapKit/MKCalloutView.h>
#import <MapKit/_MKCalloutContentView.h>
#import <MapKit/MKStandardCalloutView.h>
#import <MapKit/MKAccessibilityItem.h>
#import <MapKit/_MKPlatterImageViewNoAutoLayout.h>
#import <MapKit/MKPlatterView.h>
#import <MapKit/_MKLabelMarkerView.h>
#import <MapKit/_MKBalloonLabelMarkerView.h>
#import <MapKit/MKInfoCardReportAProblemController.h>
#import <MapKit/MKAutocompleteAnalyticsProvider.h>
#import <MapKit/MKAutocompleteAnalyticsState.h>
#import <MapKit/MKServerFormattedStringParameters.h>
#import <MapKit/MKServerFormattedString.h>
#import <MapKit/MKTransitAttributionSummaryCell.h>
#import <MapKit/MKLocalSearchResponse.h>
#import <MapKit/MKAttributedStringVibrancySplitter.h>
#import <MapKit/MKCircle.h>
#import <MapKit/_MKRouteETA.h>
#import <MapKit/_MKRouteETAFetcher.h>
#import <MapKit/_MKQuickRouteManager.h>
#import <MapKit/MKAllRouteETAsManager.h>
#import <MapKit/MKPlaceInfoRow.h>
#import <MapKit/MKPlaceInfoViewController.h>
#import <MapKit/MKPlaceUnfinishedViewController.h>
#import <MapKit/MKPolyline.h>
#import <MapKit/MKShape.h>
#import <MapKit/MKPinAnnotationView.h>
#import <MapKit/_MKStackingViewControllerHeaderView.h>
#import <MapKit/MKMultiPoint.h>
#import <MapKit/MKAttributeUtils.h>
#import <MapKit/MKPolygon.h>
#import <MapKit/MKWalletMerchantLookupRequest.h>
#import <MapKit/MKWalletMerchantStylingInfo.h>
#import <MapKit/MKWalletMerchantResponse.h>
#import <MapKit/_mkMapServiceWalletMerchantTicket.h>
#import <MapKit/MKPlaceBusinessInfoViewController.h>
#import <MapKit/_MKPlaceBusinessInfoRow.h>
#import <MapKit/_MKPlaceBusinessInfoItem.h>
#import <MapKit/MKPlaceTextBlockCell.h>
#import <MapKit/MKGeodesicPolyline.h>
#import <MapKit/MKCircleRenderer.h>
#import <MapKit/MKArtworkDataSourceCache.h>
#import <MapKit/MKETAProvider.h>
#import <MapKit/_MKUIViewController.h>
#import <MapKit/_MKUIViewControllerRootView.h>
#import <MapKit/_MKUIViewControllerClickableRootView.h>
#import <MapKit/MKStackingViewController.h>
#import <MapKit/_MKStackingPlaceholderView.h>
#import <MapKit/_MKStackingContentView.h>
#import <MapKit/MKPlaceReservationViewController.h>
#import <MapKit/_MXExtensionHostViewController.h>
#import <MapKit/NVMapScaleSegment.h>
#import <MapKit/MKScaleView.h>
#import <MapKit/MKPlaceHeaderButtonsViewController.h>
#import <MapKit/_MKMultiPartLabelMetrics.h>
#import <MapKit/MKTransitDepartureServiceGapFormatter.h>
#import <MapKit/MKTransitDepartureServiceGapFormatterResult.h>
#import <MapKit/MKOverlayPathRenderer.h>
#import <MapKit/MKOverlayRenderer.h>
#import <MapKit/_MKCustomFeatureStore.h>
#import <MapKit/_MKTransitConnectionCell.h>
#import <MapKit/MKViewWithHairline.h>
#import <MapKit/MKPolygonRenderer.h>
#import <MapKit/MKPolylineRenderer.h>
#import <MapKit/MKTransitArtworkManager.h>
#import <MapKit/MKDirectionsRequest.h>
#import <MapKit/MKThemeMultiPartLabel.h>
#import <MapKit/MKSeparator.h>
#import <MapKit/MKButtonWithTargetArgument.h>
#import <MapKit/MKPlaceSectionItemView.h>
#import <MapKit/MKPlaceSectionView.h>
#import <MapKit/MKServiceHoursRow.h>
#import <MapKit/MKPlaceServiceHoursViewController.h>
#import <MapKit/NVAttributeAttachmentCell.h>
#import <MapKit/MKAttributeLabelModel.h>
#import <MapKit/_MXVersion.h>
#import <MapKit/_MKKVOProxy.h>
#import <MapKit/MKDistanceFormatter.h>
#import <MapKit/_MKMultiPartStringComponent.h>
#import <MapKit/MKDirections.h>
#import <MapKit/MKPlaceActivityProvider.h>
#import <MapKit/MKPlaceTextActivityProvider.h>
#import <MapKit/MKPlaceURLActivityProvider.h>
#import <MapKit/MKPlaceMapItemActivityProvider.h>
#import <MapKit/MKPlaceLocVCardActivityProvider.h>
#import <MapKit/MKRouteActivityProvider.h>
#import <MapKit/MKRouteTextActivityProvider.h>
#import <MapKit/MKRouteURLActivityProvider.h>
#import <MapKit/MKMapItemMetadataRequest.h>
#import <MapKit/MKMapItemMetadataImageRequest.h>
#import <MapKit/MKMapItemMetadataRequester.h>
#import <MapKit/MKPlaceAttributionCellButton.h>
#import <MapKit/MKPlaceAttributionLabel.h>
#import <MapKit/MKPlaceAttributionCell.h>
#import <MapKit/MKPlaceAttributionViewController.h>
#import <MapKit/MKLayoutCardViewController.h>
#import <MapKit/_MXExtensionRequestReceipt.h>
#import <MapKit/_MXExtensionService.h>
#import <MapKit/MKPlaceCardHeaderViewController.h>
#import <MapKit/MKSharingController.h>
#import <MapKit/MKTileOverlay.h>
#import <MapKit/MKTileOverlayTile.h>
#import <MapKit/MKTileOverlayRequester.h>
#import <MapKit/MKTileOverlayRequesterOp.h>
#import <MapKit/_MKScaleViewTransitionDelegate.h>
#import <MapKit/_MKTicket.h>
#import <MapKit/_MKSearchTicket.h>
#import <MapKit/_MKProblemReportTicket.h>
#import <MapKit/_MKCategoriesTicket.h>
#import <MapKit/_MKSearchFieldPlaceholderTicket.h>
#import <MapKit/_MKTransitLineTicket.h>
#import <MapKit/MKMapService.h>
#import <MapKit/MKAnnotationViewInternal.h>
#import <MapKit/MKAnnotationView.h>
#import <MapKit/_MKAnnotationViewAnchor.h>
#import <MapKit/_MKAnnotationViewCustomFeatureAnnotation.h>
#import <MapKit/MKStarRatingView.h>
#import <MapKit/MKStarRatingAndLabelView.h>
#import <MapKit/MKTransitIncidentsViewController.h>
#import <MapKit/_MKPlaceActionButtonController.h>
#import <MapKit/_MXExtension.h>
#import <MapKit/_MXExtensionVendorViewController.h>
#import <MapKit/MKCalloutLayer.h>
#import <MapKit/MKCalloutShadowView.h>
#import <MapKit/MKAttributionLabel.h>
#import <MapKit/MKTileOverlayRenderer.h>
#import <MapKit/MKOverlayContainerView.h>
#import <MapKit/MKTransitSectionController.h>
#import <MapKit/MKPlaceReviewAvatarGenerator.h>
#import <MapKit/MKPlaceReviewsViewCell.h>
#import <MapKit/_MKEnvironmentLabel.h>
#import <MapKit/MKSizedTransitArtwork.h>
#import <MapKit/_MKAppImageManagerContainer.h>
#import <MapKit/MKAppImageManager.h>
#import <MapKit/MKMapSnapshotOptions.h>
#import <MapKit/_MKResizingLayer.h>
#import <MapKit/_MKCalloutLayer.h>
#import <MapKit/_MXExtensionInternalServiceRequestDispatcher.h>
#import <MapKit/_MXExtensionInternalStreamingServiceRequestDispatcher.h>
#import <MapKit/MKIncidentTextView.h>
#import <MapKit/MKTransitIncidentDetailCell.h>
#import <MapKit/_MKResultView.h>
#import <MapKit/MKPlaceTopBarViewController.h>
#import <MapKit/MKPlaceHoursView.h>
#import <MapKit/MKPlaceServiceHoursView.h>
#import <MapKit/MKPlaceCompleteHoursView.h>
#import <MapKit/MKPlaceHoursViewHelper.h>
#import <MapKit/MKMapSnapshot.h>
#import <MapKit/MKPlaceCardActionItem.h>
#import <MapKit/MKPlaceActionManager.h>
#import <MapKit/MKTransitLineItemViewController.h>
#import <MapKit/MKUserLocationAnnotation.h>
#import <MapKit/MKUserLocationInternal.h>
#import <MapKit/MKUserLocation.h>
#import <MapKit/MKMapSnapshotter.h>
#import <MapKit/MKTransitItemController.h>
#import <MapKit/MKPlaceCardActionSectionView.h>
#import <MapKit/MKPlaceCardActionsViewController.h>
#import <MapKit/MKCompassLayer.h>
#import <MapKit/_MXBundleBlacklistEntry.h>
#import <MapKit/_MXExtensionMatchingMerger.h>
#import <MapKit/_MXExtensionDispatchCenter.h>
#import <MapKit/_MXExtensionContainingAppProxy.h>
#import <MapKit/_MXExtensionServiceCenter.h>
#import <MapKit/_MXAssetStorage.h>
#import <MapKit/_MXExtensionProvider.h>
#import <MapKit/_MKFakeNil.h>
#import <MapKit/MKTransitSectionPagingFilter.h>

void* GEOGetMKIconManagerLog(void);
void* ImageForShieldDataSourceTypeShouldBeFlipped(void);
void* MKAddressDictionaryFromCLPlacemark(void);
void* MKAddressDictionaryFromContactsDictionary(void);
void* MKAddressDictionaryFromPostalAddress(void);
void* MKAddressStringForAddressDictionary(void);
void* MKAnnotationViewIntersectionArea(void);
void* MKAnnotationViewsIntersectionArea(void);
void* MKApplicationLayoutDirectionIsRightToLeft(void);
void* MKArrowAppendArrowheadToPathAndReturnMetrics(void);
void* MKArrowAppendArrowheadToPathAndReturnMetricsWithStemAdjustment(void);
void* MKArrowAppendCurveToPath(void);
void* MKArrowAppendCurveToPathWithOptions(void);
void* MKArrowAppendCurveToPathWithOptionsAndRadius(void);
void* MKArrowAppendExitRoadLeftToPathInRect(void);
void* MKArrowAppendExitRoadRightToPathInRect(void);
void* MKArrowAppendFinalSegmentToPath(void);
void* MKArrowAppendInitialSegmentToPath(void);
void* MKArrowAppendLeftTurnToPathInRect(void);
void* MKArrowAppendMergeLeftToPathInRect(void);
void* MKArrowAppendMergeRightToPathInRect(void);
void* MKArrowAppendRightAngleCurveToPath(void);
void* MKArrowAppendRightTurnToPathInRect(void);
void* MKArrowAppendSegmentToPath(void);
void* MKArrowAppendStraightArrowToPathInRect(void);
void* MKArrowAppendUTurnCurveToPath(void);
void* MKArrowAppendUTurnToPathInRect(void);
void* MKArrowCreateBezierPathsForArrivalWithSize(void);
void* MKArrowCreateBezierPathsForArrivalWithSizeAndReturnCenter(void);
void* MKArrowCreateBezierPathsForEitherProceedToRouteOrArrivalWithSizeAndReturnCenter(void);
void* MKArrowCreateBezierPathsForProceedToRouteWithSize(void);
void* MKArrowCreateBezierPathsForProceedToRouteWithSizeAndReturnCenter(void);
void* MKBearingFromCoordinateToCoordinate(void);
void* MKCalculateDistance(void);
void* MKCenterWithLayerPosition(void);
void* MKClosestMapPointInLineSegmentFromMapPoint(void);
void* MKCompassPointFromLocationDirection(void);
void* MKCoordinateForMapPoint(void);
void* MKCoordinateForTilePoint(void);
void* MKCoordinateRegionForMapRect(void);
void* MKCoordinateRegionMakeWithDistance(void);
void* MKCoordinateRegionMakeWithZoomLevel(void);
void* MKCoordinatesForRegion(void);
void* MKCurrentTransitConnectionFailureDiagnosis(void);
void* MKDefaultCoordinateRegion(void);
void* MKDefaultGuidanceManeuverMetrics(void);
void* MKDirectionBetween(void);
void* MKGetCenterForIntegralFrame(void);
void* MKGetMKDefaultLog(void);
void* MKGetNextOrientation(void);
void* MKGuidanceManeuverArrowMetricsApplyScale(void);
void* MKGuidanceManeuverArrowMetricsEqualToArrowMetrics(void);
void* MKIntegerHash(void);
void* MKIntegralAnchorAdustedCenterForViewInView(void);
void* MKIntegralCenterForLayer(void);
void* MKIntegralCenterForLayerWithScale(void);
void* MKIntegralCenterForView(void);
void* MKIntegralCenterForViewWithScale(void);
void* MKIntegralPoint(void);
void* MKIsHostedInSiri(void);
void* MKKeyForTransitArtwork(void);
void* MKLayerPositionWithAnchoredPosition(void);
void* MKLayerPositionWithCenter(void);
void* MKLayerTreeDescription(void);
void* MKLineIntersectsOriginCircle(void);
void* MKLocalSearchMetricsStatusForError(void);
void* MKLocalSearchMetricsStatusToKeypressStatus(void);
void* MKLocalizedAbbreviationForCompassPoint(void);
void* MKLocalizedStringForUnknownLocation(void);
void* MKLongHash(void);
void* MKMapItemIdentifierFromGEOPBTransitLine(void);
void* MKMapItemIdentifierFromGEOTransitLine(void);
void* MKMapItemIdentifiersArrayFromGEOMapItemIdentifiersArray(void);
void* MKMapItemIdentifiersArrayToGEOMapItemIdentifiersArray(void);
void* MKMapItemIdentifiersToGEOMapItemIdentifier(void);
void* MKMapPointForCoordinate(void);
void* MKMapPointsPerMeterAtLatitude(void);
void* MKMapRectBoundingMapPoints(void);
void* MKMapRectContainsPoint(void);
void* MKMapRectContainsRect(void);
void* MKMapRectContainsRectWrappingMeridian(void);
void* MKMapRectDivide(void);
void* MKMapRectForCoordinateRegion(void);
void* MKMapRectInset(void);
void* MKMapRectIntersection(void);
void* MKMapRectIntersectsMapRectWrappingMeridian(void);
void* MKMapRectIntersectsRect(void);
void* MKMapRectMakeWithRadialDistance(void);
void* MKMapRectOffset(void);
void* MKMapRectRemainder(void);
void* MKMapRectSpans180thMeridian(void);
void* MKMapRectUnion(void);
void* MKMappedABCNDictionary(void);
void* MKMetersBetweenMapPoints(void);
void* MKMetersPerMapPointAtLatitude(void);
void* MKNormalizedPointForLayer(void);
void* MKPrepareMultiLineLabelContainerForWidth(void);
void* MKRectToLineSegments(void);
void* MKRectWithPoints(void);
void* MKRoadWidthAtZoomScale(void);
void* MKTilePointForCoordinate(void);
void* MKTmpUserTrip(void);
void* MKTransitArtworkImageConstrainedToWidth(void);
void* MKTransitIncidentIcon(void);
void* MKTripRecording(void);
void* MKUnNormalizedPointForLayer(void);
void* MKZoomScaleForZoomLevelF(void);
void* _MKIsRunningInExtension(void);
void* _MKLinkedOnOrAfterReleaseSet(void);
void* _MKMapRectThatFits(void);
void* _MKPlaceCardButtonsAreFullWidth(void);
void* _MKPlaceCardFormattedStringForTimeInterval(void);
void* _MKPlaceCardUseSmallerFont(void);
void* _MKRAPIsAvailable(void);
void* _MKSiriLanguageIsRTLFn(void);
void* _MKTransitIncidentImage(void);
void* _Z10_splitNodeP14MKQuadTrieNodeP10MKQuadTrie(void);
void* _Z16MKMapRectLEQSize9MKMapRect9MKMapSize(void);
void* _Z16_depthFirstApplyP14MKQuadTrieNodeU13block_pointerF28MKQuadTrieTraversalDirectiveS0_E(void);
void* _Z17__depthFirstApplyP14MKQuadTrieNodeU13block_pointerF28MKQuadTrieTraversalDirectiveS0_E(void);
void* _Z18MKQuadTrieNodeFreeP14MKQuadTrieNode(void);
void* _Z18MKQuadTrieNodeMake9MKMapRect(void);
void* _Z18_breadthFirstApplyP14MKQuadTrieNodeU13block_pointerF28MKQuadTrieTraversalDirectiveS0_E(void);
void* _Z21_insertionNodeForItemPU23objcproto12MKAnnotation11objc_objectP14MKQuadTrieNode(void);
void* _Z24MKStringFromQuadTrieNodeP14MKQuadTrieNode(void);
void* _Z7_insertPU23objcproto12MKAnnotation11objc_objectP14MKQuadTrieNodeP10MKQuadTrie(void);
void* _Z7_removePU23objcproto12MKAnnotation11objc_objectP14MKQuadTrieNode(void);
void* _Z9_containsPU23objcproto12MKAnnotation11objc_objectP14MKQuadTrieNode(void);
void* _ZN3URS22shareSectionsForRoutesERKNSt3__16vectorIU8__strongP16GEOComposedRouteNS0_9allocatorIS4_EEEE(void);
void* _notifyCenterOffsetChanged(void);
void* _performOnMainThreadIfPossible(void);
void* _scaleForMapRect(void);
void* mt_log_mapkit_usemap(void);
void* mt_log_maps_bookmarked(void);
void* mt_log_maps_gesture(void);
void* mt_log_maps_mode_switch(void);
void* mt_log_maps_mode_time(void);
void* mt_log_maps_opened(void);
void* mt_log_maps_printed(void);
void* mt_log_maps_reportproblem(void);
void* mt_log_maps_shared_to(void);
void* mt_log_maps_usemapkitmap(void);
void* mt_log_usedirections(void);
void* mt_signature_for_map_type(void);

#endif
