#ifndef NCU_KEYS_H
#define NCU_KEYS_H 1

/* This file was generated by MAKE_KEYS */

#if BROKEN_LINKER
static
#endif
const struct tinfo_fkeys _nc_tinfo_fkeys[] = {
	{ 0, 0} };

#endif /* NCU_KEYS_H */
