#ifndef LSSHAREDFILE_H
#define LSSHAREDFILE_H
#include <CoreFoundation/CFString.h>

extern const CFStringRef kLSSharedFileListFavoriteItems;
extern const CFStringRef kLSSharedFileListFavoriteVolumes;
extern const CFStringRef kLSSharedFileListGlobalLoginItems;
// extern const LSSharedFileListRef kLSSharedFileListItemBeforeFirst;
extern const CFStringRef kLSSharedFileListItemHidden;
// extern const LSSharedFileListItemRef kLSSharedFileListItemLast;
extern const CFStringRef kLSSharedFileListLoginItemHidden;
extern const CFStringRef kLSSharedFileListRecentApplicationItems;
extern const CFStringRef kLSSharedFileListRecentDocumentItems;
extern const CFStringRef kLSSharedFileListRecentItemsMaxAmount;
extern const CFStringRef kLSSharedFileListRecentServerItems;
extern const CFStringRef kLSSharedFileListSessionLoginItems;
extern const CFStringRef kLSSharedFileListVolumesComputerVisible;
extern const CFStringRef kLSSharedFileListVolumesIDiskVisible;
extern const CFStringRef kLSSharedFileListVolumesNetworkVisible;

#endif
