/*
 * IDENTIFICATION:
 * stub generated Tue Aug  4 16:44:59 2015
 * with a MiG generated by 1.0
 * OPTIONS: 
 */

/* Module mach_host */

#define	__MIG_check__Request__mach_host_subsystem__ 1

#include "mach_hostServer.h"

#ifndef	mig_internal
#define	mig_internal	static __inline__
#endif	/* mig_internal */

#ifndef	mig_external
#define mig_external
#endif	/* mig_external */

#if	!defined(__MigTypeCheck) && defined(TypeCheck)
#define	__MigTypeCheck		TypeCheck	/* Legacy setting */
#endif	/* !defined(__MigTypeCheck) */

#if	!defined(__MigKernelSpecificCode) && defined(_MIG_KERNEL_SPECIFIC_CODE_)
#define	__MigKernelSpecificCode	_MIG_KERNEL_SPECIFIC_CODE_	/* Legacy setting */
#endif	/* !defined(__MigKernelSpecificCode) */

#ifndef	LimitCheck
#define	LimitCheck 0
#endif	/* LimitCheck */

#ifndef	min
#define	min(a,b)  ( ((a) < (b))? (a): (b) )
#endif	/* min */

#if !defined(_WALIGN_)
#define _WALIGN_(x) (((x) + 7) & ~7)
#endif /* !defined(_WALIGN_) */

#if !defined(_WALIGNSZ_)
#define _WALIGNSZ_(x) _WALIGN_(sizeof(x))
#endif /* !defined(_WALIGNSZ_) */

#ifndef	UseStaticTemplates
#define	UseStaticTemplates	0
#endif	/* UseStaticTemplates */

#ifndef	__DeclareRcvRpc
#define	__DeclareRcvRpc(_NUM_, _NAME_)
#endif	/* __DeclareRcvRpc */

#ifndef	__BeforeRcvRpc
#define	__BeforeRcvRpc(_NUM_, _NAME_)
#endif	/* __BeforeRcvRpc */

#ifndef	__AfterRcvRpc
#define	__AfterRcvRpc(_NUM_, _NAME_)
#endif	/* __AfterRcvRpc */

#ifndef	__DeclareRcvSimple
#define	__DeclareRcvSimple(_NUM_, _NAME_)
#endif	/* __DeclareRcvSimple */

#ifndef	__BeforeRcvSimple
#define	__BeforeRcvSimple(_NUM_, _NAME_)
#endif	/* __BeforeRcvSimple */

#ifndef	__AfterRcvSimple
#define	__AfterRcvSimple(_NUM_, _NAME_)
#endif	/* __AfterRcvSimple */

#define novalue void

#define msgh_request_port	msgh_local_port
#define MACH_MSGH_BITS_REQUEST(bits)	MACH_MSGH_BITS_LOCAL(bits)
#define msgh_reply_port		msgh_remote_port
#define MACH_MSGH_BITS_REPLY(bits)	MACH_MSGH_BITS_REMOTE(bits)

#define MIG_RETURN_ERROR(X, code)	{\
				((mig_reply_error_t *)X)->RetCode = code;\
				((mig_reply_error_t *)X)->NDR = NDR_record;\
				return;\
				}

/* Forward Declarations */


mig_internal novalue _Xhost_info
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xhost_kernel_version
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _X_host_page_size
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xmach_memory_object_memory_entry
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xhost_processor_info
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xhost_get_io_master
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xhost_get_clock_service
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xkmod_get_info
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xhost_zone_info
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xhost_virtual_physical_table_info
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xprocessor_set_default
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xprocessor_set_create
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xmach_memory_object_memory_entry_64
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xhost_statistics
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xhost_request_notification
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xhost_lockgroup_info
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xhost_statistics64
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xmach_zone_info
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xmach_zone_force_gc
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xhost_create_mach_voucher
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xhost_register_mach_voucher_attr_manager
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xhost_register_well_known_mach_voucher_attr_manager
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);


#if ( __MigTypeCheck )
#if __MIG_check__Request__mach_host_subsystem__
#if !defined(__MIG_check__Request__host_info_t__defined)
#define __MIG_check__Request__host_info_t__defined

mig_internal kern_return_t __MIG_check__Request__host_info_t(__attribute__((__unused__)) __Request__host_info_t *In0P)
{

	typedef __Request__host_info_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__host_info_t__defined) */
#endif /* __MIG_check__Request__mach_host_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine host_info */
mig_internal novalue _Xhost_info
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(8)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		host_flavor_t flavor;
		mach_msg_type_number_t host_info_outCnt;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__host_info_t __Request;
	typedef __Reply__host_info_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__host_info_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__host_info_t__defined */

	__DeclareRcvRpc(200, "host_info")
	__BeforeRcvRpc(200, "host_info")

#if	defined(__MIG_check__Request__host_info_t__defined)
	check_result = __MIG_check__Request__host_info_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__host_info_t__defined) */

	OutP->host_info_outCnt = 68;
	if (In0P->host_info_outCnt < OutP->host_info_outCnt)
		OutP->host_info_outCnt = In0P->host_info_outCnt;

	OutP->RetCode = host_info(In0P->Head.msgh_request_port, In0P->flavor, OutP->host_info_out, &OutP->host_info_outCnt);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}

	OutP->NDR = NDR_record;

	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply) - 272) + (_WALIGN_((4 * OutP->host_info_outCnt + 7) & ~7));

	__AfterRcvRpc(200, "host_info")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__mach_host_subsystem__
#if !defined(__MIG_check__Request__host_kernel_version_t__defined)
#define __MIG_check__Request__host_kernel_version_t__defined

mig_internal kern_return_t __MIG_check__Request__host_kernel_version_t(__attribute__((__unused__)) __Request__host_kernel_version_t *In0P)
{

	typedef __Request__host_kernel_version_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__host_kernel_version_t__defined) */
#endif /* __MIG_check__Request__mach_host_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine host_kernel_version */
mig_internal novalue _Xhost_kernel_version
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(8)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__host_kernel_version_t __Request;
	typedef __Reply__host_kernel_version_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__host_kernel_version_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__host_kernel_version_t__defined */

	__DeclareRcvRpc(201, "host_kernel_version")
	__BeforeRcvRpc(201, "host_kernel_version")

#if	defined(__MIG_check__Request__host_kernel_version_t__defined)
	check_result = __MIG_check__Request__host_kernel_version_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__host_kernel_version_t__defined) */

	OutP->RetCode = host_kernel_version(In0P->Head.msgh_request_port, OutP->kernel_version);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}

	OutP->NDR = NDR_record;

#ifdef __LP64__
	{
		size_t strLength = strlen(OutP->kernel_version) + 1;
		if (strLength > 0xffffffff)
			MIG_RETURN_ERROR(OutP, MIG_BAD_ARGUMENTS);
		OutP->kernel_versionCnt = (mach_msg_type_number_t) strLength;
	}
#else
	OutP->kernel_versionCnt = (mach_msg_type_number_t) strlen(OutP->kernel_version) + 1;
#endif /* __LP64__ */
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply) - 512) + (_WALIGN_((OutP->kernel_versionCnt + 7) & ~7));

	__AfterRcvRpc(201, "host_kernel_version")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__mach_host_subsystem__
#if !defined(__MIG_check__Request___host_page_size_t__defined)
#define __MIG_check__Request___host_page_size_t__defined

mig_internal kern_return_t __MIG_check__Request___host_page_size_t(__attribute__((__unused__)) __Request___host_page_size_t *In0P)
{

	typedef __Request___host_page_size_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request___host_page_size_t__defined) */
#endif /* __MIG_check__Request__mach_host_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine _host_page_size */
mig_internal novalue _X_host_page_size
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(8)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request___host_page_size_t __Request;
	typedef __Reply___host_page_size_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request___host_page_size_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request___host_page_size_t__defined */

	__DeclareRcvRpc(202, "_host_page_size")
	__BeforeRcvRpc(202, "_host_page_size")

#if	defined(__MIG_check__Request___host_page_size_t__defined)
	check_result = __MIG_check__Request___host_page_size_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request___host_page_size_t__defined) */

	OutP->RetCode = _host_page_size(In0P->Head.msgh_request_port, &OutP->out_page_size);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}

	OutP->NDR = NDR_record;


	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	__AfterRcvRpc(202, "_host_page_size")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__mach_host_subsystem__
#if !defined(__MIG_check__Request__mach_memory_object_memory_entry_t__defined)
#define __MIG_check__Request__mach_memory_object_memory_entry_t__defined

mig_internal kern_return_t __MIG_check__Request__mach_memory_object_memory_entry_t(__attribute__((__unused__)) __Request__mach_memory_object_memory_entry_t *In0P)
{

	typedef __Request__mach_memory_object_memory_entry_t __Request;
#if	__MigTypeCheck
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 1) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->pager.type != MACH_MSG_PORT_DESCRIPTOR ||
	    In0P->pager.disposition != 17)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__mach_memory_object_memory_entry_t__defined) */
#endif /* __MIG_check__Request__mach_host_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine mach_memory_object_memory_entry */
mig_internal novalue _Xmach_memory_object_memory_entry
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(8)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t pager;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		boolean_t internal;
		vm_size_t size;
		vm_prot_t permission;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__mach_memory_object_memory_entry_t __Request;
	typedef __Reply__mach_memory_object_memory_entry_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__mach_memory_object_memory_entry_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__mach_memory_object_memory_entry_t__defined */

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t entry_handleTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		17,
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(203, "mach_memory_object_memory_entry")
	__BeforeRcvRpc(203, "mach_memory_object_memory_entry")

#if	defined(__MIG_check__Request__mach_memory_object_memory_entry_t__defined)
	check_result = __MIG_check__Request__mach_memory_object_memory_entry_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__mach_memory_object_memory_entry_t__defined) */

#if	UseStaticTemplates
	OutP->entry_handle = entry_handleTemplate;
#else	/* UseStaticTemplates */
	OutP->entry_handle.disposition = 17;
	OutP->entry_handle.type = MACH_MSG_PORT_DESCRIPTOR;
#endif	/* UseStaticTemplates */


	RetCode = mach_memory_object_memory_entry(In0P->Head.msgh_request_port, In0P->internal, In0P->size, In0P->permission, In0P->pager.name, &OutP->entry_handle.name);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}

	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(203, "mach_memory_object_memory_entry")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__mach_host_subsystem__
#if !defined(__MIG_check__Request__host_processor_info_t__defined)
#define __MIG_check__Request__host_processor_info_t__defined

mig_internal kern_return_t __MIG_check__Request__host_processor_info_t(__attribute__((__unused__)) __Request__host_processor_info_t *In0P)
{

	typedef __Request__host_processor_info_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__host_processor_info_t__defined) */
#endif /* __MIG_check__Request__mach_host_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine host_processor_info */
mig_internal novalue _Xhost_processor_info
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(8)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		processor_flavor_t flavor;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__host_processor_info_t __Request;
	typedef __Reply__host_processor_info_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__host_processor_info_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__host_processor_info_t__defined */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t out_processor_infoTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		FALSE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(204, "host_processor_info")
	__BeforeRcvRpc(204, "host_processor_info")

#if	defined(__MIG_check__Request__host_processor_info_t__defined)
	check_result = __MIG_check__Request__host_processor_info_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__host_processor_info_t__defined) */

#if	UseStaticTemplates
	OutP->out_processor_info = out_processor_infoTemplate;
#else	/* UseStaticTemplates */
	OutP->out_processor_info.deallocate =  FALSE;
	OutP->out_processor_info.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->out_processor_info.type = MACH_MSG_OOL_DESCRIPTOR;
#endif	/* UseStaticTemplates */


	RetCode = host_processor_info(In0P->Head.msgh_request_port, In0P->flavor, &OutP->out_processor_count, (processor_info_array_t *)&(OutP->out_processor_info.address), &OutP->out_processor_infoCnt);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}
	OutP->out_processor_info.size = OutP->out_processor_infoCnt * 4;


	OutP->NDR = NDR_record;


	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(204, "host_processor_info")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__mach_host_subsystem__
#if !defined(__MIG_check__Request__host_get_io_master_t__defined)
#define __MIG_check__Request__host_get_io_master_t__defined

mig_internal kern_return_t __MIG_check__Request__host_get_io_master_t(__attribute__((__unused__)) __Request__host_get_io_master_t *In0P)
{

	typedef __Request__host_get_io_master_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__host_get_io_master_t__defined) */
#endif /* __MIG_check__Request__mach_host_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine host_get_io_master */
mig_internal novalue _Xhost_get_io_master
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(8)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__host_get_io_master_t __Request;
	typedef __Reply__host_get_io_master_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__host_get_io_master_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__host_get_io_master_t__defined */

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t io_masterTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		19,
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(205, "host_get_io_master")
	__BeforeRcvRpc(205, "host_get_io_master")

#if	defined(__MIG_check__Request__host_get_io_master_t__defined)
	check_result = __MIG_check__Request__host_get_io_master_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__host_get_io_master_t__defined) */

#if	UseStaticTemplates
	OutP->io_master = io_masterTemplate;
#else	/* UseStaticTemplates */
	OutP->io_master.disposition = 19;
	OutP->io_master.type = MACH_MSG_PORT_DESCRIPTOR;
#endif	/* UseStaticTemplates */


	RetCode = host_get_io_master(In0P->Head.msgh_request_port, &OutP->io_master.name);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}

	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(205, "host_get_io_master")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__mach_host_subsystem__
#if !defined(__MIG_check__Request__host_get_clock_service_t__defined)
#define __MIG_check__Request__host_get_clock_service_t__defined

mig_internal kern_return_t __MIG_check__Request__host_get_clock_service_t(__attribute__((__unused__)) __Request__host_get_clock_service_t *In0P)
{

	typedef __Request__host_get_clock_service_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__host_get_clock_service_t__defined) */
#endif /* __MIG_check__Request__mach_host_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine host_get_clock_service */
mig_internal novalue _Xhost_get_clock_service
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(8)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		clock_id_t clock_id;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__host_get_clock_service_t __Request;
	typedef __Reply__host_get_clock_service_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__host_get_clock_service_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__host_get_clock_service_t__defined */

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t clock_servTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		19,
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(206, "host_get_clock_service")
	__BeforeRcvRpc(206, "host_get_clock_service")

#if	defined(__MIG_check__Request__host_get_clock_service_t__defined)
	check_result = __MIG_check__Request__host_get_clock_service_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__host_get_clock_service_t__defined) */

#if	UseStaticTemplates
	OutP->clock_serv = clock_servTemplate;
#else	/* UseStaticTemplates */
	OutP->clock_serv.disposition = 19;
	OutP->clock_serv.type = MACH_MSG_PORT_DESCRIPTOR;
#endif	/* UseStaticTemplates */


	RetCode = host_get_clock_service(In0P->Head.msgh_request_port, In0P->clock_id, &OutP->clock_serv.name);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}

	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(206, "host_get_clock_service")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__mach_host_subsystem__
#if !defined(__MIG_check__Request__kmod_get_info_t__defined)
#define __MIG_check__Request__kmod_get_info_t__defined

mig_internal kern_return_t __MIG_check__Request__kmod_get_info_t(__attribute__((__unused__)) __Request__kmod_get_info_t *In0P)
{

	typedef __Request__kmod_get_info_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__kmod_get_info_t__defined) */
#endif /* __MIG_check__Request__mach_host_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine kmod_get_info */
mig_internal novalue _Xkmod_get_info
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(8)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__kmod_get_info_t __Request;
	typedef __Reply__kmod_get_info_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__kmod_get_info_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__kmod_get_info_t__defined */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t modulesTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		FALSE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(207, "kmod_get_info")
	__BeforeRcvRpc(207, "kmod_get_info")

#if	defined(__MIG_check__Request__kmod_get_info_t__defined)
	check_result = __MIG_check__Request__kmod_get_info_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__kmod_get_info_t__defined) */

#if	UseStaticTemplates
	OutP->modules = modulesTemplate;
#else	/* UseStaticTemplates */
	OutP->modules.deallocate =  FALSE;
	OutP->modules.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->modules.type = MACH_MSG_OOL_DESCRIPTOR;
#endif	/* UseStaticTemplates */


	RetCode = kmod_get_info(In0P->Head.msgh_request_port, (kmod_args_t *)&(OutP->modules.address), &OutP->modulesCnt);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}
	OutP->modules.size = OutP->modulesCnt;


	OutP->NDR = NDR_record;


	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(207, "kmod_get_info")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__mach_host_subsystem__
#if !defined(__MIG_check__Request__host_zone_info_t__defined)
#define __MIG_check__Request__host_zone_info_t__defined

mig_internal kern_return_t __MIG_check__Request__host_zone_info_t(__attribute__((__unused__)) __Request__host_zone_info_t *In0P)
{

	typedef __Request__host_zone_info_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__host_zone_info_t__defined) */
#endif /* __MIG_check__Request__mach_host_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine host_zone_info */
mig_internal novalue _Xhost_zone_info
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(8)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__host_zone_info_t __Request;
	typedef __Reply__host_zone_info_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__host_zone_info_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__host_zone_info_t__defined */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t namesTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		TRUE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t infoTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		TRUE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(208, "host_zone_info")
	__BeforeRcvRpc(208, "host_zone_info")

#if	defined(__MIG_check__Request__host_zone_info_t__defined)
	check_result = __MIG_check__Request__host_zone_info_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__host_zone_info_t__defined) */

#if	UseStaticTemplates
	OutP->names = namesTemplate;
#else	/* UseStaticTemplates */
	OutP->names.deallocate =  TRUE;
	OutP->names.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->names.type = MACH_MSG_OOL_DESCRIPTOR;
#endif	/* UseStaticTemplates */


#if	UseStaticTemplates
	OutP->info = infoTemplate;
#else	/* UseStaticTemplates */
	OutP->info.deallocate =  TRUE;
	OutP->info.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->info.type = MACH_MSG_OOL_DESCRIPTOR;
#endif	/* UseStaticTemplates */


	OutP->namesCnt = 0;

	OutP->infoCnt = 0;

	RetCode = host_zone_info(In0P->Head.msgh_request_port, (zone_name_array_t *)&(OutP->names.address), &OutP->namesCnt, (zone_info_array_t *)&(OutP->info.address), &OutP->infoCnt);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}
	OutP->names.size = OutP->namesCnt * 80;

	OutP->info.size = OutP->infoCnt * 36;


	OutP->NDR = NDR_record;


	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 2;
	__AfterRcvRpc(208, "host_zone_info")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__mach_host_subsystem__
#if !defined(__MIG_check__Request__host_virtual_physical_table_info_t__defined)
#define __MIG_check__Request__host_virtual_physical_table_info_t__defined

mig_internal kern_return_t __MIG_check__Request__host_virtual_physical_table_info_t(__attribute__((__unused__)) __Request__host_virtual_physical_table_info_t *In0P)
{

	typedef __Request__host_virtual_physical_table_info_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__host_virtual_physical_table_info_t__defined) */
#endif /* __MIG_check__Request__mach_host_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine host_virtual_physical_table_info */
mig_internal novalue _Xhost_virtual_physical_table_info
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(8)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__host_virtual_physical_table_info_t __Request;
	typedef __Reply__host_virtual_physical_table_info_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__host_virtual_physical_table_info_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__host_virtual_physical_table_info_t__defined */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t infoTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		TRUE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(209, "host_virtual_physical_table_info")
	__BeforeRcvRpc(209, "host_virtual_physical_table_info")

#if	defined(__MIG_check__Request__host_virtual_physical_table_info_t__defined)
	check_result = __MIG_check__Request__host_virtual_physical_table_info_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__host_virtual_physical_table_info_t__defined) */

#if	UseStaticTemplates
	OutP->info = infoTemplate;
#else	/* UseStaticTemplates */
	OutP->info.deallocate =  TRUE;
	OutP->info.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->info.type = MACH_MSG_OOL_DESCRIPTOR;
#endif	/* UseStaticTemplates */


	OutP->infoCnt = 0;

	RetCode = host_virtual_physical_table_info(In0P->Head.msgh_request_port, (hash_info_bucket_array_t *)&(OutP->info.address), &OutP->infoCnt);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}
	OutP->info.size = OutP->infoCnt * 4;


	OutP->NDR = NDR_record;


	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(209, "host_virtual_physical_table_info")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__mach_host_subsystem__
#if !defined(__MIG_check__Request__processor_set_default_t__defined)
#define __MIG_check__Request__processor_set_default_t__defined

mig_internal kern_return_t __MIG_check__Request__processor_set_default_t(__attribute__((__unused__)) __Request__processor_set_default_t *In0P)
{

	typedef __Request__processor_set_default_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__processor_set_default_t__defined) */
#endif /* __MIG_check__Request__mach_host_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine processor_set_default */
mig_internal novalue _Xprocessor_set_default
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(8)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__processor_set_default_t __Request;
	typedef __Reply__processor_set_default_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__processor_set_default_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__processor_set_default_t__defined */

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t default_setTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		19,
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(213, "processor_set_default")
	__BeforeRcvRpc(213, "processor_set_default")

#if	defined(__MIG_check__Request__processor_set_default_t__defined)
	check_result = __MIG_check__Request__processor_set_default_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__processor_set_default_t__defined) */

#if	UseStaticTemplates
	OutP->default_set = default_setTemplate;
#else	/* UseStaticTemplates */
	OutP->default_set.disposition = 19;
	OutP->default_set.type = MACH_MSG_PORT_DESCRIPTOR;
#endif	/* UseStaticTemplates */


	RetCode = processor_set_default(In0P->Head.msgh_request_port, &OutP->default_set.name);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}

	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(213, "processor_set_default")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__mach_host_subsystem__
#if !defined(__MIG_check__Request__processor_set_create_t__defined)
#define __MIG_check__Request__processor_set_create_t__defined

mig_internal kern_return_t __MIG_check__Request__processor_set_create_t(__attribute__((__unused__)) __Request__processor_set_create_t *In0P)
{

	typedef __Request__processor_set_create_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__processor_set_create_t__defined) */
#endif /* __MIG_check__Request__mach_host_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine processor_set_create */
mig_internal novalue _Xprocessor_set_create
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(8)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__processor_set_create_t __Request;
	typedef __Reply__processor_set_create_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__processor_set_create_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__processor_set_create_t__defined */

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t new_setTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		19,
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t new_nameTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		19,
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(214, "processor_set_create")
	__BeforeRcvRpc(214, "processor_set_create")

#if	defined(__MIG_check__Request__processor_set_create_t__defined)
	check_result = __MIG_check__Request__processor_set_create_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__processor_set_create_t__defined) */

#if	UseStaticTemplates
	OutP->new_set = new_setTemplate;
#else	/* UseStaticTemplates */
	OutP->new_set.disposition = 19;
	OutP->new_set.type = MACH_MSG_PORT_DESCRIPTOR;
#endif	/* UseStaticTemplates */


#if	UseStaticTemplates
	OutP->new_name = new_nameTemplate;
#else	/* UseStaticTemplates */
	OutP->new_name.disposition = 19;
	OutP->new_name.type = MACH_MSG_PORT_DESCRIPTOR;
#endif	/* UseStaticTemplates */


	RetCode = processor_set_create(In0P->Head.msgh_request_port, &OutP->new_set.name, &OutP->new_name.name);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}

	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 2;
	__AfterRcvRpc(214, "processor_set_create")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__mach_host_subsystem__
#if !defined(__MIG_check__Request__mach_memory_object_memory_entry_64_t__defined)
#define __MIG_check__Request__mach_memory_object_memory_entry_64_t__defined

mig_internal kern_return_t __MIG_check__Request__mach_memory_object_memory_entry_64_t(__attribute__((__unused__)) __Request__mach_memory_object_memory_entry_64_t *In0P)
{

	typedef __Request__mach_memory_object_memory_entry_64_t __Request;
#if	__MigTypeCheck
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 1) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->pager.type != MACH_MSG_PORT_DESCRIPTOR ||
	    In0P->pager.disposition != 17)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__mach_memory_object_memory_entry_64_t__defined) */
#endif /* __MIG_check__Request__mach_host_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine mach_memory_object_memory_entry_64 */
mig_internal novalue _Xmach_memory_object_memory_entry_64
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(8)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t pager;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		boolean_t internal;
		memory_object_size_t size;
		vm_prot_t permission;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__mach_memory_object_memory_entry_64_t __Request;
	typedef __Reply__mach_memory_object_memory_entry_64_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__mach_memory_object_memory_entry_64_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__mach_memory_object_memory_entry_64_t__defined */

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t entry_handleTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		17,
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(215, "mach_memory_object_memory_entry_64")
	__BeforeRcvRpc(215, "mach_memory_object_memory_entry_64")

#if	defined(__MIG_check__Request__mach_memory_object_memory_entry_64_t__defined)
	check_result = __MIG_check__Request__mach_memory_object_memory_entry_64_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__mach_memory_object_memory_entry_64_t__defined) */

#if	UseStaticTemplates
	OutP->entry_handle = entry_handleTemplate;
#else	/* UseStaticTemplates */
	OutP->entry_handle.disposition = 17;
	OutP->entry_handle.type = MACH_MSG_PORT_DESCRIPTOR;
#endif	/* UseStaticTemplates */


	RetCode = mach_memory_object_memory_entry_64(In0P->Head.msgh_request_port, In0P->internal, In0P->size, In0P->permission, In0P->pager.name, &OutP->entry_handle.name);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}

	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(215, "mach_memory_object_memory_entry_64")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__mach_host_subsystem__
#if !defined(__MIG_check__Request__host_statistics_t__defined)
#define __MIG_check__Request__host_statistics_t__defined

mig_internal kern_return_t __MIG_check__Request__host_statistics_t(__attribute__((__unused__)) __Request__host_statistics_t *In0P)
{

	typedef __Request__host_statistics_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__host_statistics_t__defined) */
#endif /* __MIG_check__Request__mach_host_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine host_statistics */
mig_internal novalue _Xhost_statistics
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(8)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		host_flavor_t flavor;
		mach_msg_type_number_t host_info_outCnt;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__host_statistics_t __Request;
	typedef __Reply__host_statistics_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__host_statistics_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__host_statistics_t__defined */

	__DeclareRcvRpc(216, "host_statistics")
	__BeforeRcvRpc(216, "host_statistics")

#if	defined(__MIG_check__Request__host_statistics_t__defined)
	check_result = __MIG_check__Request__host_statistics_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__host_statistics_t__defined) */

	OutP->host_info_outCnt = 68;
	if (In0P->host_info_outCnt < OutP->host_info_outCnt)
		OutP->host_info_outCnt = In0P->host_info_outCnt;

	OutP->RetCode = host_statistics(In0P->Head.msgh_request_port, In0P->flavor, OutP->host_info_out, &OutP->host_info_outCnt);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}

	OutP->NDR = NDR_record;

	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply) - 272) + (_WALIGN_((4 * OutP->host_info_outCnt + 7) & ~7));

	__AfterRcvRpc(216, "host_statistics")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__mach_host_subsystem__
#if !defined(__MIG_check__Request__host_request_notification_t__defined)
#define __MIG_check__Request__host_request_notification_t__defined

mig_internal kern_return_t __MIG_check__Request__host_request_notification_t(__attribute__((__unused__)) __Request__host_request_notification_t *In0P)
{

	typedef __Request__host_request_notification_t __Request;
#if	__MigTypeCheck
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 1) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->notify_port.type != MACH_MSG_PORT_DESCRIPTOR ||
	    In0P->notify_port.disposition != 18)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__host_request_notification_t__defined) */
#endif /* __MIG_check__Request__mach_host_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine host_request_notification */
mig_internal novalue _Xhost_request_notification
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(8)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t notify_port;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		host_flavor_t notify_type;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__host_request_notification_t __Request;
	typedef __Reply__host_request_notification_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__host_request_notification_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__host_request_notification_t__defined */

	__DeclareRcvRpc(217, "host_request_notification")
	__BeforeRcvRpc(217, "host_request_notification")

#if	defined(__MIG_check__Request__host_request_notification_t__defined)
	check_result = __MIG_check__Request__host_request_notification_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__host_request_notification_t__defined) */

	OutP->RetCode = host_request_notification(In0P->Head.msgh_request_port, In0P->notify_type, In0P->notify_port.name);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(217, "host_request_notification")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__mach_host_subsystem__
#if !defined(__MIG_check__Request__host_lockgroup_info_t__defined)
#define __MIG_check__Request__host_lockgroup_info_t__defined

mig_internal kern_return_t __MIG_check__Request__host_lockgroup_info_t(__attribute__((__unused__)) __Request__host_lockgroup_info_t *In0P)
{

	typedef __Request__host_lockgroup_info_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__host_lockgroup_info_t__defined) */
#endif /* __MIG_check__Request__mach_host_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine host_lockgroup_info */
mig_internal novalue _Xhost_lockgroup_info
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(8)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__host_lockgroup_info_t __Request;
	typedef __Reply__host_lockgroup_info_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__host_lockgroup_info_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__host_lockgroup_info_t__defined */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t lockgroup_infoTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		TRUE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(218, "host_lockgroup_info")
	__BeforeRcvRpc(218, "host_lockgroup_info")

#if	defined(__MIG_check__Request__host_lockgroup_info_t__defined)
	check_result = __MIG_check__Request__host_lockgroup_info_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__host_lockgroup_info_t__defined) */

#if	UseStaticTemplates
	OutP->lockgroup_info = lockgroup_infoTemplate;
#else	/* UseStaticTemplates */
	OutP->lockgroup_info.deallocate =  TRUE;
	OutP->lockgroup_info.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->lockgroup_info.type = MACH_MSG_OOL_DESCRIPTOR;
#endif	/* UseStaticTemplates */


	OutP->lockgroup_infoCnt = 0;

	RetCode = host_lockgroup_info(In0P->Head.msgh_request_port, (lockgroup_info_array_t *)&(OutP->lockgroup_info.address), &OutP->lockgroup_infoCnt);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}
	OutP->lockgroup_info.size = OutP->lockgroup_infoCnt * 252;


	OutP->NDR = NDR_record;


	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(218, "host_lockgroup_info")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__mach_host_subsystem__
#if !defined(__MIG_check__Request__host_statistics64_t__defined)
#define __MIG_check__Request__host_statistics64_t__defined

mig_internal kern_return_t __MIG_check__Request__host_statistics64_t(__attribute__((__unused__)) __Request__host_statistics64_t *In0P)
{

	typedef __Request__host_statistics64_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__host_statistics64_t__defined) */
#endif /* __MIG_check__Request__mach_host_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine host_statistics64 */
mig_internal novalue _Xhost_statistics64
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(8)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		host_flavor_t flavor;
		mach_msg_type_number_t host_info64_outCnt;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__host_statistics64_t __Request;
	typedef __Reply__host_statistics64_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__host_statistics64_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__host_statistics64_t__defined */

	__DeclareRcvRpc(219, "host_statistics64")
	__BeforeRcvRpc(219, "host_statistics64")

#if	defined(__MIG_check__Request__host_statistics64_t__defined)
	check_result = __MIG_check__Request__host_statistics64_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__host_statistics64_t__defined) */

	OutP->host_info64_outCnt = 256;
	if (In0P->host_info64_outCnt < OutP->host_info64_outCnt)
		OutP->host_info64_outCnt = In0P->host_info64_outCnt;

	OutP->RetCode = host_statistics64(In0P->Head.msgh_request_port, In0P->flavor, OutP->host_info64_out, &OutP->host_info64_outCnt);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}

	OutP->NDR = NDR_record;

	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply) - 1024) + (_WALIGN_((4 * OutP->host_info64_outCnt + 7) & ~7));

	__AfterRcvRpc(219, "host_statistics64")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__mach_host_subsystem__
#if !defined(__MIG_check__Request__mach_zone_info_t__defined)
#define __MIG_check__Request__mach_zone_info_t__defined

mig_internal kern_return_t __MIG_check__Request__mach_zone_info_t(__attribute__((__unused__)) __Request__mach_zone_info_t *In0P)
{

	typedef __Request__mach_zone_info_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__mach_zone_info_t__defined) */
#endif /* __MIG_check__Request__mach_host_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine mach_zone_info */
mig_internal novalue _Xmach_zone_info
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(8)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__mach_zone_info_t __Request;
	typedef __Reply__mach_zone_info_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__mach_zone_info_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__mach_zone_info_t__defined */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t namesTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		TRUE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t infoTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		TRUE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(220, "mach_zone_info")
	__BeforeRcvRpc(220, "mach_zone_info")

#if	defined(__MIG_check__Request__mach_zone_info_t__defined)
	check_result = __MIG_check__Request__mach_zone_info_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__mach_zone_info_t__defined) */

#if	UseStaticTemplates
	OutP->names = namesTemplate;
#else	/* UseStaticTemplates */
	OutP->names.deallocate =  TRUE;
	OutP->names.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->names.type = MACH_MSG_OOL_DESCRIPTOR;
#endif	/* UseStaticTemplates */


#if	UseStaticTemplates
	OutP->info = infoTemplate;
#else	/* UseStaticTemplates */
	OutP->info.deallocate =  TRUE;
	OutP->info.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->info.type = MACH_MSG_OOL_DESCRIPTOR;
#endif	/* UseStaticTemplates */


	OutP->namesCnt = 0;

	OutP->infoCnt = 0;

	RetCode = mach_zone_info(In0P->Head.msgh_request_port, (mach_zone_name_array_t *)&(OutP->names.address), &OutP->namesCnt, (mach_zone_info_array_t *)&(OutP->info.address), &OutP->infoCnt);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}
	OutP->names.size = OutP->namesCnt * 80;

	OutP->info.size = OutP->infoCnt * 64;


	OutP->NDR = NDR_record;


	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 2;
	__AfterRcvRpc(220, "mach_zone_info")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__mach_host_subsystem__
#if !defined(__MIG_check__Request__mach_zone_force_gc_t__defined)
#define __MIG_check__Request__mach_zone_force_gc_t__defined

mig_internal kern_return_t __MIG_check__Request__mach_zone_force_gc_t(__attribute__((__unused__)) __Request__mach_zone_force_gc_t *In0P)
{

	typedef __Request__mach_zone_force_gc_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__mach_zone_force_gc_t__defined) */
#endif /* __MIG_check__Request__mach_host_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine mach_zone_force_gc */
mig_internal novalue _Xmach_zone_force_gc
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(8)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__mach_zone_force_gc_t __Request;
	typedef __Reply__mach_zone_force_gc_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__mach_zone_force_gc_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__mach_zone_force_gc_t__defined */

	__DeclareRcvRpc(221, "mach_zone_force_gc")
	__BeforeRcvRpc(221, "mach_zone_force_gc")

#if	defined(__MIG_check__Request__mach_zone_force_gc_t__defined)
	check_result = __MIG_check__Request__mach_zone_force_gc_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__mach_zone_force_gc_t__defined) */

	OutP->RetCode = mach_zone_force_gc(In0P->Head.msgh_request_port);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(221, "mach_zone_force_gc")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__mach_host_subsystem__
#if !defined(__MIG_check__Request__host_create_mach_voucher_t__defined)
#define __MIG_check__Request__host_create_mach_voucher_t__defined

mig_internal kern_return_t __MIG_check__Request__host_create_mach_voucher_t(__attribute__((__unused__)) __Request__host_create_mach_voucher_t *In0P)
{

	typedef __Request__host_create_mach_voucher_t __Request;
#if	__MigTypeCheck
	unsigned int msgh_size;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	msgh_size = In0P->Head.msgh_size;
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 5120)) ||  (msgh_size > (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if defined(__NDR_convert__int_rep__Request__host_create_mach_voucher_t__recipesCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__host_create_mach_voucher_t__recipesCnt(&In0P->recipesCnt, In0P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__host_create_mach_voucher_t__recipesCnt__defined */
#if	__MigTypeCheck
	if ( In0P->recipesCnt > 5120 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 5120)) < In0P->recipesCnt) ||
	    (msgh_size != (mach_msg_size_t)(sizeof(__Request) - 5120) + _WALIGN_(In0P->recipesCnt)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__host_create_mach_voucher_t__defined) */
#endif /* __MIG_check__Request__mach_host_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine host_create_mach_voucher */
mig_internal novalue _Xhost_create_mach_voucher
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(8)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		mach_msg_type_number_t recipesCnt;
		uint8_t recipes[5120];
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__host_create_mach_voucher_t __Request;
	typedef __Reply__host_create_mach_voucher_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__host_create_mach_voucher_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__host_create_mach_voucher_t__defined */

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t voucherTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		19,
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(222, "host_create_mach_voucher")
	__BeforeRcvRpc(222, "host_create_mach_voucher")

#if	defined(__MIG_check__Request__host_create_mach_voucher_t__defined)
	check_result = __MIG_check__Request__host_create_mach_voucher_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__host_create_mach_voucher_t__defined) */

#if	UseStaticTemplates
	OutP->voucher = voucherTemplate;
#else	/* UseStaticTemplates */
	OutP->voucher.disposition = 19;
	OutP->voucher.type = MACH_MSG_PORT_DESCRIPTOR;
#endif	/* UseStaticTemplates */


	RetCode = host_create_mach_voucher(In0P->Head.msgh_request_port, In0P->recipes, In0P->recipesCnt, &OutP->voucher.name);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}

	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(222, "host_create_mach_voucher")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__mach_host_subsystem__
#if !defined(__MIG_check__Request__host_register_mach_voucher_attr_manager_t__defined)
#define __MIG_check__Request__host_register_mach_voucher_attr_manager_t__defined

mig_internal kern_return_t __MIG_check__Request__host_register_mach_voucher_attr_manager_t(__attribute__((__unused__)) __Request__host_register_mach_voucher_attr_manager_t *In0P)
{

	typedef __Request__host_register_mach_voucher_attr_manager_t __Request;
#if	__MigTypeCheck
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 1) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->attr_manager.type != MACH_MSG_PORT_DESCRIPTOR ||
	    In0P->attr_manager.disposition != 17)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__host_register_mach_voucher_attr_manager_t__defined) */
#endif /* __MIG_check__Request__mach_host_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine host_register_mach_voucher_attr_manager */
mig_internal novalue _Xhost_register_mach_voucher_attr_manager
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(8)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t attr_manager;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		mach_voucher_attr_value_handle_t default_value;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__host_register_mach_voucher_attr_manager_t __Request;
	typedef __Reply__host_register_mach_voucher_attr_manager_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__host_register_mach_voucher_attr_manager_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__host_register_mach_voucher_attr_manager_t__defined */

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t new_attr_controlTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		19,
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(223, "host_register_mach_voucher_attr_manager")
	__BeforeRcvRpc(223, "host_register_mach_voucher_attr_manager")

#if	defined(__MIG_check__Request__host_register_mach_voucher_attr_manager_t__defined)
	check_result = __MIG_check__Request__host_register_mach_voucher_attr_manager_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__host_register_mach_voucher_attr_manager_t__defined) */

#if	UseStaticTemplates
	OutP->new_attr_control = new_attr_controlTemplate;
#else	/* UseStaticTemplates */
	OutP->new_attr_control.disposition = 19;
	OutP->new_attr_control.type = MACH_MSG_PORT_DESCRIPTOR;
#endif	/* UseStaticTemplates */


	RetCode = host_register_mach_voucher_attr_manager(In0P->Head.msgh_request_port, In0P->attr_manager.name, In0P->default_value, &OutP->new_key, &OutP->new_attr_control.name);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}

	OutP->NDR = NDR_record;


	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(223, "host_register_mach_voucher_attr_manager")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__mach_host_subsystem__
#if !defined(__MIG_check__Request__host_register_well_known_mach_voucher_attr_manager_t__defined)
#define __MIG_check__Request__host_register_well_known_mach_voucher_attr_manager_t__defined

mig_internal kern_return_t __MIG_check__Request__host_register_well_known_mach_voucher_attr_manager_t(__attribute__((__unused__)) __Request__host_register_well_known_mach_voucher_attr_manager_t *In0P)
{

	typedef __Request__host_register_well_known_mach_voucher_attr_manager_t __Request;
#if	__MigTypeCheck
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 1) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->attr_manager.type != MACH_MSG_PORT_DESCRIPTOR ||
	    In0P->attr_manager.disposition != 17)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__host_register_well_known_mach_voucher_attr_manager_t__defined) */
#endif /* __MIG_check__Request__mach_host_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine host_register_well_known_mach_voucher_attr_manager */
mig_internal novalue _Xhost_register_well_known_mach_voucher_attr_manager
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(8)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t attr_manager;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		mach_voucher_attr_value_handle_t default_value;
		mach_voucher_attr_key_t key;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__host_register_well_known_mach_voucher_attr_manager_t __Request;
	typedef __Reply__host_register_well_known_mach_voucher_attr_manager_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__host_register_well_known_mach_voucher_attr_manager_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__host_register_well_known_mach_voucher_attr_manager_t__defined */

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t new_attr_controlTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		19,
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(224, "host_register_well_known_mach_voucher_attr_manager")
	__BeforeRcvRpc(224, "host_register_well_known_mach_voucher_attr_manager")

#if	defined(__MIG_check__Request__host_register_well_known_mach_voucher_attr_manager_t__defined)
	check_result = __MIG_check__Request__host_register_well_known_mach_voucher_attr_manager_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__host_register_well_known_mach_voucher_attr_manager_t__defined) */

#if	UseStaticTemplates
	OutP->new_attr_control = new_attr_controlTemplate;
#else	/* UseStaticTemplates */
	OutP->new_attr_control.disposition = 19;
	OutP->new_attr_control.type = MACH_MSG_PORT_DESCRIPTOR;
#endif	/* UseStaticTemplates */


	RetCode = host_register_well_known_mach_voucher_attr_manager(In0P->Head.msgh_request_port, In0P->attr_manager.name, In0P->default_value, In0P->key, &OutP->new_attr_control.name);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}

	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(224, "host_register_well_known_mach_voucher_attr_manager")
}



/* Description of this subsystem, for use in direct RPC */
const struct mach_host_subsystem mach_host_subsystem = {
	mach_host_server_routine,
	200,
	225,
	(mach_msg_size_t)sizeof(union __ReplyUnion__mach_host_subsystem),
	(vm_address_t)0,
	{
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xhost_info, 5, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__host_info_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xhost_kernel_version, 2, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__host_kernel_version_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _X_host_page_size, 2, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply___host_page_size_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xmach_memory_object_memory_entry, 7, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__mach_memory_object_memory_entry_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xhost_processor_info, 6, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__host_processor_info_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xhost_get_io_master, 2, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__host_get_io_master_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xhost_get_clock_service, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__host_get_clock_service_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xkmod_get_info, 4, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__kmod_get_info_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xhost_zone_info, 7, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__host_zone_info_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xhost_virtual_physical_table_info, 4, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__host_virtual_physical_table_info_t)},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xprocessor_set_default, 2, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__processor_set_default_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xprocessor_set_create, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__processor_set_create_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xmach_memory_object_memory_entry_64, 7, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__mach_memory_object_memory_entry_64_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xhost_statistics, 5, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__host_statistics_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xhost_request_notification, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__host_request_notification_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xhost_lockgroup_info, 4, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__host_lockgroup_info_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xhost_statistics64, 5, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__host_statistics64_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xmach_zone_info, 7, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__mach_zone_info_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xmach_zone_force_gc, 1, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__mach_zone_force_gc_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xhost_create_mach_voucher, 5, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__host_create_mach_voucher_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xhost_register_mach_voucher_attr_manager, 6, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__host_register_mach_voucher_attr_manager_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xhost_register_well_known_mach_voucher_attr_manager, 6, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__host_register_well_known_mach_voucher_attr_manager_t)},
	}
};

mig_external boolean_t mach_host_server
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	register mig_routine_t routine;

	OutHeadP->msgh_bits = MACH_MSGH_BITS(MACH_MSGH_BITS_REPLY(InHeadP->msgh_bits), 0);
	OutHeadP->msgh_remote_port = InHeadP->msgh_reply_port;
	/* Minimal size: routine() will update it if different */
	OutHeadP->msgh_size = (mach_msg_size_t)sizeof(mig_reply_error_t);
	OutHeadP->msgh_local_port = MACH_PORT_NULL;
	OutHeadP->msgh_id = InHeadP->msgh_id + 100;

	if ((InHeadP->msgh_id > 224) || (InHeadP->msgh_id < 200) ||
	    ((routine = mach_host_subsystem.routine[InHeadP->msgh_id - 200].stub_routine) == 0)) {
		((mig_reply_error_t *)OutHeadP)->NDR = NDR_record;
		((mig_reply_error_t *)OutHeadP)->RetCode = MIG_BAD_ID;
		return FALSE;
	}
	(*routine) (InHeadP, OutHeadP);
	return TRUE;
}

mig_external mig_routine_t mach_host_server_routine
	(mach_msg_header_t *InHeadP)
{
	register int msgh_id;

	msgh_id = InHeadP->msgh_id - 200;

	if ((msgh_id > 24) || (msgh_id < 0))
		return 0;

	return mach_host_subsystem.routine[msgh_id].stub_routine;
}
