/*
 This file is part of Darling.

 Copyright (C) 2021 Lubos Dolezel

 Darling is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Darling is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Darling.  If not, see <http://www.gnu.org/licenses/>.
*/


#ifndef _AssistantServices_H_
#define _AssistantServices_H_

#import <Foundation/Foundation.h>

#import <AssistantServices/AFAccessibilityListening.h>
#import <AssistantServices/AFAccessibilityStateMutating.h>
#import <AssistantServices/AFAceCommandDialogInfoExtracting.h>
#import <AssistantServices/AFAnalyticsContextVending.h>
#import <AssistantServices/AFAnalyticsObservationService.h>
#import <AssistantServices/AFAnalyticsObserver.h>
#import <AssistantServices/AFAnalyticsService.h>
#import <AssistantServices/AFAnalyticsServiceDelegate.h>
#import <AssistantServices/AFApplicationContextMutating.h>
#import <AssistantServices/AFAudioDeviceInfoMutating.h>
#import <AssistantServices/AFAudioPlaybackRequestMutating.h>
#import <AssistantServices/AFAudioPowerProviding.h>
#import <AssistantServices/AFAudioPowerUpdaterDelegate.h>
#import <AssistantServices/AFBluetoothDeviceInfoMutating.h>
#import <AssistantServices/AFBluetoothHeadphoneInEarDetectionStateMutating.h>
#import <AssistantServices/AFBluetoothWirelessSplitterSessionInfoMutating.h>
#import <AssistantServices/AFCallSiteInfoMutating.h>
#import <AssistantServices/AFClientConfigurationMutating.h>
#import <AssistantServices/AFClientInfoMutating.h>
#import <AssistantServices/AFClientLiteClientCommandHandling.h>
#import <AssistantServices/AFClientLiteRemoteCommandHandling.h>
#import <AssistantServices/AFClientPlugin.h>
#import <AssistantServices/AFClientService.h>
#import <AssistantServices/AFClientServiceDelegate.h>
#import <AssistantServices/AFClockAlarmMutating.h>
#import <AssistantServices/AFClockAlarmSnapshotMutating.h>
#import <AssistantServices/AFClockItem.h>
#import <AssistantServices/AFClockItemStorageDelegate.h>
#import <AssistantServices/AFClockTimerMutating.h>
#import <AssistantServices/AFClockTimerSnapshotMutating.h>
#import <AssistantServices/AFContextCollating.h>
#import <AssistantServices/AFConversationStorable.h>
#import <AssistantServices/AFDeleteSiriHistoryContextMutating.h>
#import <AssistantServices/AFDeviceRingerSwitchListening.h>
#import <AssistantServices/AFDictationService.h>
#import <AssistantServices/AFDictationServiceDelegate.h>
#import <AssistantServices/AFDisambiguationAssistancePrivate.h>
#import <AssistantServices/AFExperimentConfigurationMutating.h>
#import <AssistantServices/AFExperimentContextMutating.h>
#import <AssistantServices/AFExperimentForSiriVOXSounds.h>
#import <AssistantServices/AFExperimentForSiriVOXTapToSiriBehavior.h>
#import <AssistantServices/AFExperimentGroupMutating.h>
#import <AssistantServices/AFExperimentMutating.h>
#import <AssistantServices/AFInterstitialConfigurationMutating.h>
#import <AssistantServices/AFInterstitialProviderDelegate.h>
#import <AssistantServices/AFInvalidating.h>
#import <AssistantServices/AFInvocationFeedbackExperiment.h>
#import <AssistantServices/AFManagedStorageService.h>
#import <AssistantServices/AFManagedStore.h>
#import <AssistantServices/AFMemoryInfoMutating.h>
#import <AssistantServices/AFMultiUserService.h>
#import <AssistantServices/AFMyriadContextMutating.h>
#import <AssistantServices/AFMyriadPerceptualAudioHashMutating.h>
#import <AssistantServices/AFNetworkAvailabilityObserver.h>
#import <AssistantServices/AFNotifyObserverDelegate.h>
#import <AssistantServices/AFOpportuneSpeakable.h>
#import <AssistantServices/AFOpportuneSpeakingModel.h>
#import <AssistantServices/AFOpportuneSpeakingModelDelegate.h>
#import <AssistantServices/AFOpportuneSpeakingModelServiceProtocol.h>
#import <AssistantServices/AFPendingSpeechRequestService.h>
#import <AssistantServices/AFSecurityDigestibleChunksProviding.h>
#import <AssistantServices/AFSecurityService.h>
#import <AssistantServices/AFSettingsDelegate.h>
#import <AssistantServices/AFSettingsService.h>
#import <AssistantServices/AFSettingsServiceDelegate.h>
#import <AssistantServices/AFSiriActivationContextMutating.h>
#import <AssistantServices/AFSiriActivationHandling.h>
#import <AssistantServices/AFSiriActivationListenerDelegate.h>
#import <AssistantServices/AFSiriActivationResultMutating.h>
#import <AssistantServices/AFSiriActivationService.h>
#import <AssistantServices/AFSiriAppContextProviding.h>
#import <AssistantServices/AFSiriExternalRequest.h>
#import <AssistantServices/AFSiriRequestFailureHandling.h>
#import <AssistantServices/AFSiriRequestHandling.h>
#import <AssistantServices/AFSiriResponseHandling.h>
#import <AssistantServices/AFSiriTaskDelivering.h>
#import <AssistantServices/AFSiriUsageResultHandling.h>
#import <AssistantServices/AFSpeakableNamespaceProvider.h>
#import <AssistantServices/AFSpeechRecordingEventListening.h>
#import <AssistantServices/AFSpeechService.h>
#import <AssistantServices/AFSpeechServiceDelegate.h>
#import <AssistantServices/AFSpeechSynthesisRecordMutating.h>
#import <AssistantServices/AFTranscriptionType.h>
#import <AssistantServices/AFUserNotificationService.h>
#import <AssistantServices/AFUserNotificationServiceDelegate.h>
#import <AssistantServices/BSXPCCoding.h>
#import <AssistantServices/Endpointer.h>
#import <AssistantServices/NSXPCListenerDelegate.h>
#import <AssistantServices/SiriCoreSQLiteRecord.h>
#import <AssistantServices/WPHeySiriProtocol.h>
#import <AssistantServices/AFConnectionAvailabilityObserver.h>
#import <AssistantServices/AFConnection.h>
#import <AssistantServices/AFConnectionClientServiceDelegate.h>
#import <AssistantServices/AFInterstitialProvider.h>
#import <AssistantServices/_AFInterstitialAction.h>
#import <AssistantServices/AFUpdateAlarmRequest.h>
#import <AssistantServices/AFGetSettingsRequest.h>
#import <AssistantServices/AFSiriRingtone.h>
#import <AssistantServices/AFSiriPhoneticContactNames.h>
#import <AssistantServices/AFExperimentConfiguration.h>
#import <AssistantServices/_AFExperimentConfigurationMutation.h>
#import <AssistantServices/AFSecurityConnection.h>
#import <AssistantServices/AFQueue.h>
#import <AssistantServices/AFSetSettingsRequest.h>
#import <AssistantServices/AFBluetoothWirelessSplitterSessionInfo.h>
#import <AssistantServices/_AFBluetoothWirelessSplitterSessionInfoMutation.h>
#import <AssistantServices/STContactAddress.h>
#import <AssistantServices/AFVoiceInfo.h>
#import <AssistantServices/AFMutableConversationItem.h>
#import <AssistantServices/AFPhonemeTranscription.h>
#import <AssistantServices/AFRemoteRequest.h>
#import <AssistantServices/AFSiriTaskExecution.h>
#import <AssistantServices/AFExperimentGroup.h>
#import <AssistantServices/_AFExperimentGroupMutation.h>
#import <AssistantServices/AFSiriRequestSucceededResponse.h>
#import <AssistantServices/AFWatchdogTimer.h>
#import <AssistantServices/AFDisambiguationInfo.h>
#import <AssistantServices/AFDisambiguationEvent.h>
#import <AssistantServices/AFMyriadContext.h>
#import <AssistantServices/_AFMyriadContextMutation.h>
#import <AssistantServices/AFSiriActivationConnection.h>
#import <AssistantServices/AFPhonemeMapper.h>
#import <AssistantServices/AFGetTimerRequest.h>
#import <AssistantServices/AFXPCWrapper.h>
#import <AssistantServices/AFLanguageDetectionUserContext.h>
#import <AssistantServices/AFSetTimerRequest.h>
#import <AssistantServices/AFGetTimerResponse.h>
#import <AssistantServices/AFError.h>
#import <AssistantServices/AFAudioPowerXPCProvider.h>
#import <AssistantServices/_AFAudioPowerXPCSharedMemory.h>
#import <AssistantServices/AFContextManager.h>
#import <AssistantServices/AFNowPlayingObserver.h>
#import <AssistantServices/AFUserNotificationProvider.h>
#import <AssistantServices/AFAccessibilityState.h>
#import <AssistantServices/_AFAccessibilityStateMutation.h>
#import <AssistantServices/AFUserUtterance.h>
#import <AssistantServices/AFUserUtteranceSelectionResults.h>
#import <AssistantServices/AFClockTimer.h>
#import <AssistantServices/_AFClockTimerMutation.h>
#import <AssistantServices/AFAnalyticsConnection.h>
#import <AssistantServices/AFSyncInfo.h>
#import <AssistantServices/AFSpeechPackage.h>
#import <AssistantServices/AFMyriadPerceptualAudioHash.h>
#import <AssistantServices/_AFMyriadPerceptualAudioHashMutation.h>
#import <AssistantServices/AFDictionarySchema.h>
#import <AssistantServices/AFSpeechPhrase.h>
#import <AssistantServices/AFSpeechUtterance.h>
#import <AssistantServices/AFSpeechInterpretation.h>
#import <AssistantServices/AFSpeechToken.h>
#import <AssistantServices/AFDeleteSiriHistoryContext.h>
#import <AssistantServices/_AFDeleteSiriHistoryContextMutation.h>
#import <AssistantServices/AFPreferences.h>
#import <AssistantServices/AFObjectCreatedSiriResponse.h>
#import <AssistantServices/AFMyriadRecord.h>
#import <AssistantServices/AFConnectionUserInteractionAssertion.h>
#import <AssistantServices/AFOpportuneSpeakingModuleDataCollectionSanitizedSpeakable.h>
#import <AssistantServices/AFOpportuneSpeakingModuleDataCollection.h>
#import <AssistantServices/AFSpeechRecognition.h>
#import <AssistantServices/AFAudioState.h>
#import <AssistantServices/AFTreeNode.h>
#import <AssistantServices/AFAssistedDisambiguationRules.h>
#import <AssistantServices/AFSiriTaskContextProvider.h>
#import <AssistantServices/AFConversationError.h>
#import <AssistantServices/AFCoercion.h>
#import <AssistantServices/AFConversation.h>
#import <AssistantServices/AFMyriadMonitor.h>
#import <AssistantServices/AFClientConfiguration.h>
#import <AssistantServices/_AFClientConfigurationMutation.h>
#import <AssistantServices/AFSpeakableUtteranceParser.h>
#import <AssistantServices/_AFSpeakableUtterancePassThroughProvider.h>
#import <AssistantServices/AFNotifyObserver.h>
#import <AssistantServices/AFSUPFunctionProvider.h>
#import <AssistantServices/AFDictationConnection.h>
#import <AssistantServices/AFDictationConnectionServiceDelegate.h>
#import <AssistantServices/AFSearchAlarmsResponse.h>
#import <AssistantServices/AFSiriActivationHandlerAssistantDaemon.h>
#import <AssistantServices/AFBluetoothDeviceInfo.h>
#import <AssistantServices/_AFBluetoothDeviceInfoMutation.h>
#import <AssistantServices/AFSiriTaskUsageResult.h>
#import <AssistantServices/STTimer.h>
#import <AssistantServices/AFExperiment.h>
#import <AssistantServices/_AFExperimentMutation.h>
#import <AssistantServices/AFRequestInfo.h>
#import <AssistantServices/AFUpdateAlarmResponse.h>
#import <AssistantServices/AFClockItemStorage.h>
#import <AssistantServices/AFClientLiteInternal.h>
#import <AssistantServices/AFClientLite.h>
#import <AssistantServices/AFSynchronousClientLite.h>
#import <AssistantServices/AFMediaRemoteDeviceInfo.h>
#import <AssistantServices/AFSiriDebugUIRequest.h>
#import <AssistantServices/AFLocalization.h>
#import <AssistantServices/AFDictationOptions.h>
#import <AssistantServices/AFImagePNGData.h>
#import <AssistantServices/AFDataStore.h>
#import <AssistantServices/_AFDataStoreEntry.h>
#import <AssistantServices/AFBluetoothHeadphoneInEarDetectionState.h>
#import <AssistantServices/_AFBluetoothHeadphoneInEarDetectionStateMutation.h>
#import <AssistantServices/AFAudioAnalyzer.h>
#import <AssistantServices/AFConversationStore.h>
#import <AssistantServices/AFSpeechCorrectionInfo.h>
#import <AssistantServices/AFAnalyticsEventRecord.h>
#import <AssistantServices/AFMemoryPressureObserver.h>
#import <AssistantServices/AFTriggerlessListeningOptions.h>
#import <AssistantServices/AFNetworkAvailability.h>
#import <AssistantServices/AFAccount.h>
#import <AssistantServices/AFManagedStorageConnection.h>
#import <AssistantServices/AFCreateAlarmResponse.h>
#import <AssistantServices/AFRemoteRequestWatcher.h>
#import <AssistantServices/AFFuture.h>
#import <AssistantServices/AFSafetyBlock.h>
#import <AssistantServices/AFOneArgumentSafetyBlock.h>
#import <AssistantServices/AFTwoArgumentSafetyBlock.h>
#import <AssistantServices/AFThreeArgumentSafetyBlock.h>
#import <AssistantServices/AFOpportuneSpeakingModelFeedback.h>
#import <AssistantServices/AFOpportuneSpeakingModelFeedbackManager.h>
#import <AssistantServices/AFMetrics.h>
#import <AssistantServices/AFSiriUserNotificationRequest.h>
#import <AssistantServices/AFSiriUserNotificationRequestCapabilityManager.h>
#import <AssistantServices/AFSiriNotificationRequest.h>
#import <AssistantServices/AFSettingsConnection.h>
#import <AssistantServices/AFSettingsConnectionServiceDelegate.h>
#import <AssistantServices/AFSiriActivationHandlerFrontendProcess.h>
#import <AssistantServices/STCity.h>
#import <AssistantServices/AFLinkedListItem.h>
#import <AssistantServices/STSettingChange.h>
#import <AssistantServices/AFSiriRequest.h>
#import <AssistantServices/AFSiriActivationHandlerCoreSpeechDaemon.h>
#import <AssistantServices/AFAudioDeviceInfo.h>
#import <AssistantServices/_AFAudioDeviceInfoMutation.h>
#import <AssistantServices/AFClockAlarmSnapshot.h>
#import <AssistantServices/_AFClockAlarmSnapshotMutation.h>
#import <AssistantServices/AFSpeechRequestOptions.h>
#import <AssistantServices/AFPluginBundle.h>
#import <AssistantServices/AFPluginManager.h>
#import <AssistantServices/SISchemaClientTurnBasedEvent.h>
#import <AssistantServices/AFContextResponse.h>
#import <AssistantServices/AFClockTimerSnapshot.h>
#import <AssistantServices/_AFClockTimerSnapshotMutation.h>
#import <AssistantServices/AFExperimentContext.h>
#import <AssistantServices/_AFExperimentContextMutation.h>
#import <AssistantServices/STSiriMessage.h>
#import <AssistantServices/AFSiriTaskService.h>
#import <AssistantServices/AFSiriTaskDeliveryHandler.h>
#import <AssistantServices/AFSiriTaskmaster.h>
#import <AssistantServices/STAlarm.h>
#import <AssistantServices/AFTreeNodePropertyListSerialization.h>
#import <AssistantServices/AFDeleteAlarmRequest.h>
#import <AssistantServices/AFDisambiguationStore.h>
#import <AssistantServices/AFUpdateMessageRequest.h>
#import <AssistantServices/STSiriLocation.h>
#import <AssistantServices/AFMemoryInfo.h>
#import <AssistantServices/_AFMemoryInfoMutation.h>
#import <AssistantServices/AFSiriActivationContext.h>
#import <AssistantServices/_AFSiriActivationContextMutation.h>
#import <AssistantServices/AFAnalytics.h>
#import <AssistantServices/AFSiriActivationListener.h>
#import <AssistantServices/AFDeviceRingerSwitchObserver.h>
#import <AssistantServices/AFCreateMessageRequest.h>
#import <AssistantServices/AFUtteranceSuggestions.h>
#import <AssistantServices/STCall.h>
#import <AssistantServices/AFShowSettingRequest.h>
#import <AssistantServices/STSetting.h>
#import <AssistantServices/AFGetSettingsResponse.h>
#import <AssistantServices/AFClockTimerObserver.h>
#import <AssistantServices/AFUIApplicationSiriTaskDeliverer.h>
#import <AssistantServices/AFMyriadEmergencyManager.h>
#import <AssistantServices/AFBulletin.h>
#import <AssistantServices/AFDialogPhase.h>
#import <AssistantServices/AFCallSiteInfo.h>
#import <AssistantServices/_AFCallSiteInfoMutation.h>
#import <AssistantServices/AFAnalyticsTurnBasedInstrumentationContext.h>
#import <AssistantServices/AFMachServiceSiriTaskDeliverer.h>
#import <AssistantServices/AFInstrumentationObserverConnection.h>
#import <AssistantServices/AFShowNextEventRequest.h>
#import <AssistantServices/SISchemaClientTurnContext.h>
#import <AssistantServices/AFClockAlarmObserver.h>
#import <AssistantServices/AFObjectUpdatedSiriResponse.h>
#import <AssistantServices/AFSpeechAcousticFeature.h>
#import <AssistantServices/AFSpeechAudioAnalytics.h>
#import <AssistantServices/AFAggregator.h>
#import <AssistantServices/AFShowTimerRequest.h>
#import <AssistantServices/AFSiriTether.h>
#import <AssistantServices/AFAudioPlaybackRequest.h>
#import <AssistantServices/_AFAudioPlaybackRequestMutation.h>
#import <AssistantServices/AFSiriResponse.h>
#import <AssistantServices/AFCreateAlarmRequest.h>
#import <AssistantServices/AFSearchAlarmsRequest.h>
#import <AssistantServices/AFInitiateCallRequest.h>
#import <AssistantServices/AFConversationItem.h>
#import <AssistantServices/AFApplicationContext.h>
#import <AssistantServices/_AFApplicationContextMutation.h>
#import <AssistantServices/AFMyriadCoordinator.h>
#import <AssistantServices/AFPeerInfo.h>
#import <AssistantServices/AFAudioPowerUpdater.h>
#import <AssistantServices/AFNotifyStatePublisher.h>
#import <AssistantServices/STPersonContactHandle.h>
#import <AssistantServices/STPerson.h>
#import <AssistantServices/AFBluetoothWirelessSplitterSessionStateObserver.h>
#import <AssistantServices/AFAppContextAggregator.h>
#import <AssistantServices/AFClientPluginManager.h>
#import <AssistantServices/AFAnalyticsObserverConnection.h>
#import <AssistantServices/AFContextRequest.h>
#import <AssistantServices/AFSiriClientStateManager.h>
#import <AssistantServices/_AFSiriClientState.h>
#import <AssistantServices/AFSiriAcousticIDRequest.h>
#import <AssistantServices/AFSiriMusicSubscriptionLeaseTakenRequest.h>
#import <AssistantServices/AFSiriMusicSmartPlayRequest.h>
#import <AssistantServices/AFSiriAceRequest.h>
#import <AssistantServices/AFSiriActivationRequest.h>
#import <AssistantServices/AFSpeechSynthesisRecord.h>
#import <AssistantServices/_AFSpeechSynthesisRecordMutation.h>
#import <AssistantServices/AFMyriadEmergencyCallPunchout.h>
#import <AssistantServices/AFInterstitialConfiguration.h>
#import <AssistantServices/_AFInterstitialConfigurationMutation.h>
#import <AssistantServices/AFMultiUserConnection.h>
#import <AssistantServices/STSiriContext.h>
#import <AssistantServices/AFAnalyticsEvent.h>
#import <AssistantServices/AFSetSettingsResponse.h>
#import <AssistantServices/AFSiriActivationResult.h>
#import <AssistantServices/_AFSiriActivationResultMutation.h>
#import <AssistantServices/SISchemaClientAnyEvent.h>
#import <AssistantServices/AFConnectionEntitlementCache.h>
#import <AssistantServices/AFPairedBluetoothDevicesObserver.h>
#import <AssistantServices/AFConversationInsertion.h>
#import <AssistantServices/STSiriModelObject.h>
#import <AssistantServices/AFInterstitialCommandWrapper.h>
#import <AssistantServices/AFChildConversationItemList.h>
#import <AssistantServices/AFRequestCompletionOptions.h>
#import <AssistantServices/AFApplicationInfo.h>
#import <AssistantServices/AFClockAlarm.h>
#import <AssistantServices/_AFClockAlarmMutation.h>
#import <AssistantServices/AFPowerAssertionManager.h>
#import <AssistantServices/AFSyncSnapshot.h>
#import <AssistantServices/AFShowAlarmRequest.h>
#import <AssistantServices/AFClientInfo.h>
#import <AssistantServices/_AFClientInfoMutation.h>
#import <AssistantServices/AFSiriTask.h>
#import <AssistantServices/AFAccessibilityObserver.h>

void* AFAccessibilitySupportsVibrationDisablement(void);
void* AFAceErrorCodeFromMRMediaRemoteCommandHandlerStatus(void);
void* AFActivationEventGetDescription(void);
void* AFAddInterruptingAudioSessionInfoToAnalyticsContext(void);
void* AFAnalyticsContextCreateForCurrentProcess(void);
void* AFAnalyticsContextCreateWithCommand(void);
void* AFAnalyticsContextCreateWithDictationOptions(void);
void* AFAnalyticsContextCreateWithError(void);
void* AFAnalyticsContextCreateWithExperiment(void);
void* AFAnalyticsContextCreateWithLanguageDetectorMetrics(void);
void* AFAnalyticsContextCreateWithRequestInfo(void);
void* AFAnalyticsContextCreateWithSpeechRequestOptions(void);
void* AFAnalyticsContextsMerge(void);
void* AFAnalyticsEventCreateCurrent(void);
void* AFAnalyticsEventCreateWithGenericInstrumentation(void);
void* AFAnalyticsEventTypeGetLegacyName(void);
void* AFAnalyticsEventTypeGetName(void);
void* AFAnalyticsEventTypeIsValid(void);
void* AFAnalyticsLogsDirectory(void);
void* AFAnalyticsObservationServiceGetXPCInterface(void);
void* AFAnalyticsObserverGetXPCInterface(void);
void* AFAnalyticsSafeContextForJson(void);
void* AFAnalyticsServiceDelegateGetXPCInterface(void);
void* AFAnalyticsServiceGetXPCInterface(void);
void* AFAppleAudioDeviceConnectedInLast24Hours(void);
void* AFApplicationClientIdentifierForApp(void);
void* AFApplicationClientIdentifierForWatchApp(void);
void* AFApplicationWorkspaceEnumerateInstalledApplications(void);
void* AFApplicationWorkspaceEnumerateInstalledUserVisibleApplications(void);
void* AFAssistantCapable(void);
void* AFAssistantRestricted(void);
void* AFAudioPlaybackOptionsGetNames(void);
void* AFAudioPlaybackOptionsValidate(void);
void* AFBackedUpPreferencesSynchronize(void);
void* AFBluetoothHeadphoneEarbudSideGetFromName(void);
void* AFBluetoothHeadphoneEarbudSideGetIsValid(void);
void* AFBluetoothHeadphoneEarbudSideGetName(void);
void* AFBluetoothHeadphoneInEarStatusGetFromName(void);
void* AFBluetoothHeadphoneInEarStatusGetIsValid(void);
void* AFBluetoothHeadphoneInEarStatusGetName(void);
void* AFBluetoothHeadphoneListeningModeGetFromName(void);
void* AFBluetoothHeadphoneListeningModeGetIsValid(void);
void* AFBluetoothHeadphoneListeningModeGetName(void);
void* AFBluetoothWirelessSplitterSessionStateGetFromName(void);
void* AFBluetoothWirelessSplitterSessionStateGetIsValid(void);
void* AFBluetoothWirelessSplitterSessionStateGetName(void);
void* AFBooleanGetFromName(void);
void* AFBooleanGetIsValid(void);
void* AFBooleanGetName(void);
void* AFBuildVersion(void);
void* AFBundleIDFromApplicationClientIdentifier(void);
void* AFBundleServicesCachePath(void);
void* AFCallSiteInfoGetCurrent(void);
void* AFCarouselBundleIdentifier(void);
void* AFClearInternalLogFiles(void);
void* AFClientLiteClientObjectInterface(void);
void* AFClientLiteRemoteObjectInterface(void);
void* AFClientServiceDelegateXPCInterface(void);
void* AFClientServiceXPCInterface(void);
void* AFClockAlarmCreateFromMTAlarm(void);
void* AFClockAlarmRepeatOptionsGetNames(void);
void* AFClockAlarmRepeatOptionsValidate(void);
void* AFClockTimerCreateFromMTTimer(void);
void* AFClockTimerGetTimerStateFromMTTimer(void);
void* AFClockTimerStateGetFromName(void);
void* AFClockTimerStateGetIsValid(void);
void* AFClockTimerStateGetName(void);
void* AFClockTimerTypeGetFromName(void);
void* AFClockTimerTypeGetIsValid(void);
void* AFClockTimerTypeGetName(void);
void* AFCommandOutcomeFromMediaRemoteStatuses(void);
void* AFConnectionHasEntitlement(void);
void* AFConnectionHasEntitlementCached(void);
void* AFContextProviderNameForBundleId(void);
void* AFCopyKeychainBaseQueryDictionary(void);
void* AFCurrentUserInterfaceIdiom(void);
void* AFDeleteCoreDuetEventsInStream(void);
void* AFDescriptionOfAFQuickStopActions(void);
void* AFDescriptionOfBKSApplicationState(void);
void* AFDeviceColor(void);
void* AFDeviceEnclosureColor(void);
void* AFDeviceHasAddressBook(void);
void* AFDeviceIsVictory(void);
void* AFDeviceName(void);
void* AFDeviceRegionCode(void);
void* AFDeviceRingerSwitchStateGetFromName(void);
void* AFDeviceRingerSwitchStateGetIsValid(void);
void* AFDeviceRingerSwitchStateGetName(void);
void* AFDeviceSupportsAOP(void);
void* AFDeviceSupportsBargeIn(void);
void* AFDeviceSupportsEchoCancellation(void);
void* AFDeviceSupportsNavigation(void);
void* AFDeviceSupportsSpokenMessages(void);
void* AFDeviceSupportsTTS(void);
void* AFDeviceSupportsWiFiLPASMode(void);
void* AFDeviceSupportsZLL(void);
void* AFDiagnosticsSubmissionAllowed(void);
void* AFDictationCapable(void);
void* AFDictationLanguageForKeyboardLanguage(void);
void* AFDictationRestricted(void);
void* AFDictationServiceDelegateXPCInterface(void);
void* AFDictationTaskHintTypeFromString(void);
void* AFDirectActionCreateRequestInfo(void);
void* AFDisambiguationHistoryReset(void);
void* AFDispatchAsyncLogged(void);
void* AFDispatchSyncLogged(void);
void* AFEffectiveSiriBundleForLocation(void);
void* AFErrorEnumerate(void);
void* AFExperimentConfigurationTypeGetFromName(void);
void* AFExperimentConfigurationTypeGetIsValid(void);
void* AFExperimentConfigurationTypeGetName(void);
void* AFExperimentDeploymentReasonGetFromName(void);
void* AFExperimentDeploymentReasonGetIsValid(void);
void* AFExperimentDeploymentReasonGetName(void);
void* AFFileURLForConversationWithIdentifier(void);
void* AFGetCurrentItemAdamIDFromNowPlayingInfo(void);
void* AFGetFlashlightLevel(void);
void* AFGetNowPlayingInfoDictionary(void);
void* AFGetNowPlayingQueueState(void);
void* AFHasBaseband(void);
void* AFHasCellularData(void);
void* AFHasCellularTelephony(void);
void* AFHasGPS(void);
void* AFHasHapticEngine(void);
void* AFHasPairedBTDeviceForSpokenMessages(void);
void* AFHasProxyCellularTelephony(void);
void* AFHasRingerSwitch(void);
void* AFHasUnlockedSinceBoot(void);
void* AFInternalConfigValueForKey(void);
void* AFInternalPreferencesSynchronize(void);
void* AFInterstitialCreateCommand(void);
void* AFInterstitialGetDialogIdentifierForPhase(void);
void* AFInterstitialIsCommandInterstitial(void);
void* AFInterstitialIsDialogIdentifierInterstitial(void);
void* AFInterstitialPhaseGetFromName(void);
void* AFInterstitialPhaseGetIsValid(void);
void* AFInterstitialPhaseGetName(void);
void* AFInterstitialStyleGetFromName(void);
void* AFInterstitialStyleGetIsValid(void);
void* AFInterstitialStyleGetName(void);
void* AFInterstitialSupportsRequestWithEvent(void);
void* AFInvocationFeedbackExperimentFeatureGroupsGetNames(void);
void* AFInvocationFeedbackExperimentFeatureGroupsValidate(void);
void* AFIsATV(void);
void* AFIsCustomerInstall(void);
void* AFIsCustomerInstallOrPPT(void);
void* AFIsFileNotFoundError(void);
void* AFIsHorseman(void);
void* AFIsIPod(void);
void* AFIsInternalInstall(void);
void* AFIsMac(void);
void* AFIsMultiUserCompanion(void);
void* AFIsNano(void);
void* AFIsPPT(void);
void* AFIsPad(void);
void* AFIsSyncNeeded(void);
void* AFKeyboardLMLocaleOverride(void);
void* AFKeyboardResourcesDirectoryPath(void);
void* AFKeychainRemoveValueForAccountAndKey(void);
void* AFKeychainSetValueForAccountAndKey(void);
void* AFKeychainValueForAccountAndKey(void);
void* AFLanguageOptionsForNowPlayingInfo(void);
void* AFLanguagePrefixForLanguageCode(void);
void* AFLibraryDirectoryWithSubPath(void);
void* AFLocationStatusIsAllowed(void);
void* AFLocationStatusIsDenied(void);
void* AFLogDirectory(void);
void* AFLogFlush(void);
void* AFLogInitIfNeeded(void);
void* AFLogParsedCommandObject(void);
void* AFLogWantsToLogParsedCommandObjects(void);
void* AFMachAbsoluteTimeAddTimeInterval(void);
void* AFMachAbsoluteTimeGetMicroseconds(void);
void* AFMachAbsoluteTimeGetMilliseconds(void);
void* AFMachAbsoluteTimeGetNanoseconds(void);
void* AFMachAbsoluteTimeGetTimeInterval(void);
void* AFMachAbsoluteTimeSubtractTimeInterval(void);
void* AFMainScreenScale(void);
void* AFManagedPreferencesDomainForDomain(void);
void* AFMapsNavigationStatusIsActive(void);
void* AFMediaPlaybackStateGetFromName(void);
void* AFMediaPlaybackStateGetIsValid(void);
void* AFMediaPlaybackStateGetName(void);
void* AFMediaRemoteSendCommandNoCheck(void);
void* AFMediaRemoteSendCommandWithOptions(void);
void* AFMediaRemoteSendCommandWithOptionsNoCheck(void);
void* AFMemoryInfoGetCurrent(void);
void* AFMobileUserBundleServicesCachePath(void);
void* AFMultiUserServiceXPCInterface(void);
void* AFMyraidCoordinatorAudioHashFilePath(void);
void* AFMyriadCoordinatorAudioHashFileBaseDirectory(void);
void* AFNavigationStateIsNavigating(void);
void* AFOfflineDictationCapable(void);
void* AFOfflineDictationCapableWithoutOverride(void);
void* AFOfflineDictationLanguageForKeyboardLanguage(void);
void* AFOfflineDictationStatusStringForVersion(void);
void* AFOfflineDictationStatusStringIsInstalled(void);
void* AFOfflineDictationStatusStringIsInstalling(void);
void* AFOpportuneSpeakingModelFeedbackGetDescription(void);
void* AFOpportuneSpeakingModelServiceInterface(void);
void* AFOpportuneSpeakingModelTypeGetDescription(void);
void* AFOutputVoiceLanguageForRecognitionLanguage(void);
void* AFOverrideLanguageCode(void);
void* AFPairedDeviceIsVictory(void);
void* AFPauseCommandsInterruptAudio(void);
void* AFPendingSpeechRequestServiceInterface(void);
void* AFPerformDeviceVolumeAction(void);
void* AFPlaybackRouteIsHandsFree(void);
void* AFPreferencesATVStopRecordingDelay(void);
void* AFPreferencesAlwaysEyesFreeEnabled(void);
void* AFPreferencesAssistantAllowed(void);
void* AFPreferencesAssistantEnabled(void);
void* AFPreferencesAudioDuckingAllowed(void);
void* AFPreferencesBorealisEducationHeaderDisplayCount(void);
void* AFPreferencesBufferedSpeechCapturePacketInterval(void);
void* AFPreferencesDictationAllowed(void);
void* AFPreferencesDisableDictationMode(void);
void* AFPreferencesHoldToTalkForTypeToSiriEnabled(void);
void* AFPreferencesHorsemanSupplementalLanguageDictionary(void);
void* AFPreferencesIgnoreServerManualEndpointingThreshold(void);
void* AFPreferencesLanguageCodeForUser(void);
void* AFPreferencesLanguageIsExplicitlySupportedForDictation(void);
void* AFPreferencesLanguageIsSupported(void);
void* AFPreferencesLanguageIsSupportedForDeviceSettings(void);
void* AFPreferencesLanguageIsSupportedForDictation(void);
void* AFPreferencesManualEndpointingThreshold(void);
void* AFPreferencesMobileUserSessionLanguage(void);
void* AFPreferencesProfanityFilterForced(void);
void* AFPreferencesSetAlwaysEyesFreeEnabled(void);
void* AFPreferencesSetBorealisEducationHeaderDisplayCount(void);
void* AFPreferencesSetHoldToTalkForTypeToSiriEnabled(void);
void* AFPreferencesSetHorsemanSupplementalLanguageDictionary(void);
void* AFPreferencesSetIgnoreServerManualEndpointingThreshold(void);
void* AFPreferencesSetManualEndpointingThreshold(void);
void* AFPreferencesSetShouldIgnoreInternalConfig(void);
void* AFPreferencesSetStartAlertEnabled(void);
void* AFPreferencesSetStreamingDictationEnabled(void);
void* AFPreferencesSetTypeToSiriEnabled(void);
void* AFPreferencesShouldIgnoreInternalConfig(void);
void* AFPreferencesSimulateImmediateSpeechCapture(void);
void* AFPreferencesSiriTaskBackgroundAssertionTimeout(void);
void* AFPreferencesSiriTaskResponseTimeout(void);
void* AFPreferencesStartAlertEnabled(void);
void* AFPreferencesStreamingDictationEnabled(void);
void* AFPreferencesSupplementalLanguages(void);
void* AFPreferencesSupplementalLanguagesModificationDate(void);
void* AFPreferencesSupportedDictationLanguages(void);
void* AFPreferencesSupportedDictationLanguagesSet(void);
void* AFPreferencesSupportedLanguages(void);
void* AFPreferencesSupportedLanguagesForCurrentStoreFront(void);
void* AFPreferencesSupportedLanguagesForRemote(void);
void* AFPreferencesSupportedLanguagesForStorefrontIdentifier(void);
void* AFPreferencesSupportedMultiUserLanguages(void);
void* AFPreferencesSynchronizeSupportedLanguages(void);
void* AFPreferencesTestAccessEnabled(void);
void* AFPreferencesTypeToSiriEnabled(void);
void* AFPreferencesUserGeneratedContentAllowed(void);
void* AFPresentationPluginsURL(void);
void* AFProductName(void);
void* AFProductType(void);
void* AFProductVersion(void);
void* AFRecordCoreDuetContext(void);
void* AFRecordCoreDuetEvent(void);
void* AFRecordCoreDuetEventAtTimestamps(void);
void* AFRecordCoreDuetEventWithStream(void);
void* AFRecordRouteIsHearst(void);
void* AFRequestCancellationReasonGetFromName(void);
void* AFRequestCancellationReasonGetIsValid(void);
void* AFRequestCancellationReasonGetName(void);
void* AFSecurityDecryptData(void);
void* AFSecurityDigestChunksWithProvider(void);
void* AFSecurityDigestData(void);
void* AFSecurityEncryptData(void);
void* AFSecurityGenerateRandomData(void);
void* AFSecurityServiceGetXPCInterface(void);
void* AFSerializeNSUserActivity(void);
void* AFServicePluginsURL(void);
void* AFSetSpokenNotificationDataCollectionEnabled(void);
void* AFSettingsServiceDelegateXPCInterface(void);
void* AFSettingsServiceXPCInterface(void);
void* AFSharedResourcesDirectory(void);
void* AFShouldRunDESRecording(void);
void* AFShouldUseLanguageDetector(void);
void* AFSiriActivationActionTypeGetFromName(void);
void* AFSiriActivationActionTypeGetIsValid(void);
void* AFSiriActivationActionTypeGetName(void);
void* AFSiriActivationBluetoothDeviceBoronSignal(void);
void* AFSiriActivationBluetoothDeviceDoubleTap(void);
void* AFSiriActivationBluetoothDeviceTriggerless(void);
void* AFSiriActivationBluetoothDeviceVoice(void);
void* AFSiriActivationBluetoothDeviceVoiceTrigger(void);
void* AFSiriActivationBluetoothDeviceVoiceTriggerPrewarm(void);
void* AFSiriActivationBuiltInMicVoice(void);
void* AFSiriActivationBuiltInMicVoiceTrigger(void);
void* AFSiriActivationBuiltInMicVoiceTriggerPrewarm(void);
void* AFSiriActivationCarPlayDeviceVoice(void);
void* AFSiriActivationCarPlayDeviceVoiceTrigger(void);
void* AFSiriActivationCarPlayDeviceVoiceTriggerPrewarm(void);
void* AFSiriActivationCreateContextFromNSDictionary(void);
void* AFSiriActivationCreateContextFromXPCDictionary(void);
void* AFSiriActivationCreateNSDictionaryFromContext(void);
void* AFSiriActivationCreateRequestInfoFromContext(void);
void* AFSiriActivationCreateResultFromXPCDictionary(void);
void* AFSiriActivationCreateXPCDictionaryFromContext(void);
void* AFSiriActivationCreateXPCDictionaryFromResult(void);
void* AFSiriActivationEventGetFromName(void);
void* AFSiriActivationEventGetIsValid(void);
void* AFSiriActivationEventGetName(void);
void* AFSiriActivationGetHandlerIDFromSourceAndEvent(void);
void* AFSiriActivationHearst(void);
void* AFSiriActivationHearstBoron(void);
void* AFSiriActivationHearstDoubleTap(void);
void* AFSiriActivationHearstVoice(void);
void* AFSiriActivationOptionsGetNames(void);
void* AFSiriActivationOptionsValidate(void);
void* AFSiriActivationPerform(void);
void* AFSiriActivationPerformLegacy(void);
void* AFSiriActivationRaiseToSpeak(void);
void* AFSiriActivationRaiseToSpeakPrewarm(void);
void* AFSiriActivationServiceGetMachServiceName(void);
void* AFSiriActivationServiceGetPort(void);
void* AFSiriActivationServiceGetXPCInterface(void);
void* AFSiriActivationServicePortGetFromName(void);
void* AFSiriActivationServicePortGetIsValid(void);
void* AFSiriActivationServicePortGetName(void);
void* AFSiriActivationSetOverrideHandlerMapProvider(void);
void* AFSiriActivationSourceGetFromName(void);
void* AFSiriActivationSourceGetIsValid(void);
void* AFSiriActivationSourceGetName(void);
void* AFSiriActivationTriggerless(void);
void* AFSiriActivationValidate(void);
void* AFSiriDataSharingOptInStatusGetFromName(void);
void* AFSiriDataSharingOptInStatusGetIsValid(void);
void* AFSiriDataSharingOptInStatusGetName(void);
void* AFSiriDeactivationOptionsGetNames(void);
void* AFSiriDeactivationOptionsValidate(void);
void* AFSiriDeactivationReasonGetFromName(void);
void* AFSiriDeactivationReasonGetIsValid(void);
void* AFSiriDeactivationReasonGetName(void);
void* AFSiriLocationAuthorizationStatus(void);
void* AFSiriResponseHandlingInterface(void);
void* AFSiriUsageDescriptionForAppID(void);
void* AFSiriUsageResultHandlingInterface(void);
void* AFSpeechEndpointerOperationModeGetFromName(void);
void* AFSpeechEndpointerOperationModeGetIsValid(void);
void* AFSpeechEndpointerOperationModeGetName(void);
void* AFSpeechEventGetDescription(void);
void* AFSpeechEventIsBluetooth(void);
void* AFSpeechEventIsRemotePlugin(void);
void* AFSpeechEventIsTVRemote(void);
void* AFSpeechEventIsVoiceTrigger(void);
void* AFSpeechLogsDirectory(void);
void* AFSpeechRecognitionUsageDescriptionForAppID(void);
void* AFSpeechRecordingEventListenerGetXPCInterface(void);
void* AFSpeechServiceDelegateGetXPCInterface(void);
void* AFSpeechServiceGetXPCInterface(void);
void* AFSpokenMessagesExecutionTimeout(void);
void* AFSpokenNotificationDataCollectionEnabled(void);
void* AFStringFromMRPlaybackState(void);
void* AFSupportBaseURL(void);
void* AFSupportPreferencesSynchronize(void);
void* AFSupportsAirPlayEndpointRoute(void);
void* AFSupportsMultiUser(void);
void* AFSupportsOdeon(void);
void* AFSupportsPairedDevice(void);
void* AFSupportsPlayThisOnThat(void);
void* AFSupportsPlayThisOnThatPlayback(void);
void* AFSupportsSiriSpeaks(void);
void* AFSupportsVibration(void);
void* AFSupportsWAPI(void);
void* AFSupportsWatchListKit(void);
void* AFSupportsWirelessSplitter(void);
void* AFSyncKeysThatNeedToBeSynced(void);
void* AFSystemGetBootTimeInMicroseconds(void);
void* AFSystemGetBootTimeInTimeInterval(void);
void* AFSystemRootDirectory(void);
void* AFTruncateMachTimeToTenthOfASecond(void);
void* AFTurnIdentifierCreateFromBytes(void);
void* AFTurnIdentifierGenerate(void);
void* AFTurnIdentifierGetBytes(void);
void* AFTurnIdentifierGetString(void);
void* AFUIBundlesURL(void);
void* AFUserAssignedDeviceName(void);
void* AFUserSupportDirectoryPath(void);
void* AFWatchOSVersion(void);
void* AFWatchOSVersionIsGreaterThanOrEqual(void);
void* SAMPPlayStateFromMRPlaybackState(void);
void* SAVoiceFromVoiceAsset(void);
void* SAVoiceFromVoiceResourceAsset(void);
void* SISchemaClientAnyEventReadFrom(void);
void* SISchemaClientTurnBasedEventReadFrom(void);
void* SISchemaClientTurnContextReadFrom(void);
void* StarkHasBeenActiveInLast24Hours(void);
void* _AFBackedUpPreferencesBoolValueForKey(void);
void* _AFBackedUpPreferencesBoolValueForKeyWithDefault(void);
void* _AFBackedUpPreferencesKeyList(void);
void* _AFBackedUpPreferencesSetValueForKey(void);
void* _AFBackedUpPreferencesValueForKey(void);
void* _AFBackedUpPreferencesValueForKeyForUser(void);
void* _AFDictationLanguageForKeyboardLanguageAndConfiguration(void);
void* _AFMemoryPressureConditionGetName(void);
void* _AFNanoPreferencesSetValueForKey(void);
void* _AFNanoPreferencesValueForKey(void);
void* _AFPreferencesAcousticIDAutoEndpoint(void);
void* _AFPreferencesAlwaysUseLocalScripts(void);
void* _AFPreferencesApplySASToFirstPartyDomains(void);
void* _AFPreferencesAuthenticationDisabled(void);
void* _AFPreferencesBLECompanionConnectionsEnabled(void);
void* _AFPreferencesBuiltIniOSLanguages(void);
void* _AFPreferencesClearOpportuneSpeakingEdgeDetectorSignalOverride(void);
void* _AFPreferencesClearShouldCensorSpeechInternal(void);
void* _AFPreferencesClearSpokenNotificationTemporarilyDisabledStatus(void);
void* _AFPreferencesClientFlowLocalDevelopment(void);
void* _AFPreferencesCloudSyncEnabled(void);
void* _AFPreferencesCloudSyncEnabledModificationDate(void);
void* _AFPreferencesCloudUserID(void);
void* _AFPreferencesCompanionMessagingEnabled(void);
void* _AFPreferencesCountryCode(void);
void* _AFPreferencesDatabaseSyncingEnabled(void);
void* _AFPreferencesDictationLanguageDetectorEnabled(void);
void* _AFPreferencesDictationLanguageDetectorEnabledByServer(void);
void* _AFPreferencesDictationRequestSamplingRates(void);
void* _AFPreferencesDisableTuscany(void);
void* _AFPreferencesEnableBLECompanionConnections(void);
void* _AFPreferencesEnableCloudSync(void);
void* _AFPreferencesEnableServerDebugFlags(void);
void* _AFPreferencesEnableSiriDebugUI(void);
void* _AFPreferencesEnableSiriMini(void);
void* _AFPreferencesEnableSiriMiniExperimentation(void);
void* _AFPreferencesEnableSiriMiniPreferred(void);
void* _AFPreferencesEnableSpeakerGradingDebugUI(void);
void* _AFPreferencesEnabledDragAndDrop(void);
void* _AFPreferencesEnabledNonFullScreen(void);
void* _AFPreferencesForceRTL(void);
void* _AFPreferencesForceSpeexAudioRecording(void);
void* _AFPreferencesForceUncompressedAudioRecording(void);
void* _AFPreferencesGetClientCommandDeliveryDelay(void);
void* _AFPreferencesGetEnableServerDebugFlags(void);
void* _AFPreferencesGetForcedInterstitialStyle(void);
void* _AFPreferencesGetInitialInterstitialDelay(void);
void* _AFPreferencesGetInitialInterstitialDelayForVoiceTriggerOneShotWithoutAudioDucking(void);
void* _AFPreferencesGetInterstitialDisplayDisabledBeforeSpeechRecognition(void);
void* _AFPreferencesGetNonManateeIdentity(void);
void* _AFPreferencesGetTuscanyStatus(void);
void* _AFPreferencesIgnoreEVFailures(void);
void* _AFPreferencesInProgressOutputVoice(void);
void* _AFPreferencesIsSiriServerLoggingEnabled(void);
void* _AFPreferencesLanguageCode(void);
void* _AFPreferencesLastPushedCensorSpeechSetting(void);
void* _AFPreferencesLimitedPersistentAudioLogging(void);
void* _AFPreferencesLowerWristEducationHeaderDisplayCount(void);
void* _AFPreferencesMirroredTCCInfo(void);
void* _AFPreferencesMultiSiriLanguageScenarios(void);
void* _AFPreferencesMultilingualDictationTimeoutInMilliSeconds(void);
void* _AFPreferencesMyriadConstantGoodness(void);
void* _AFPreferencesMyriadDeviceAdjust(void);
void* _AFPreferencesMyriadDeviceClass(void);
void* _AFPreferencesMyriadDeviceDelay(void);
void* _AFPreferencesMyriadDeviceGroup(void);
void* _AFPreferencesMyriadDeviceSlowdown(void);
void* _AFPreferencesMyriadDeviceTrumpDelay(void);
void* _AFPreferencesMyriadLastWin(void);
void* _AFPreferencesMyriadServerHasProvisioned(void);
void* _AFPreferencesMyriadServerProvisioning(void);
void* _AFPreferencesNetworkLoggingEnabled(void);
void* _AFPreferencesNetworkStackOverride(void);
void* _AFPreferencesNotificationPreviewRestrictedApps(void);
void* _AFPreferencesOpportuneSpeakingEdgeDetectorSignalOverride(void);
void* _AFPreferencesOpportuneSpeakingModelUsed(void);
void* _AFPreferencesOpportuneSpeakingModuleEnabled(void);
void* _AFPreferencesOpportuneSpeakingPause(void);
void* _AFPreferencesOpportuneSpeakingTimeout(void);
void* _AFPreferencesOutputVoice(void);
void* _AFPreferencesPluginTimeoutDisabled(void);
void* _AFPreferencesReplacementLanguageForLocalRecognizerLanguageCode(void);
void* _AFPreferencesSetAcousticIDAutoEndpoint(void);
void* _AFPreferencesSetAlwaysUseLocalScripts(void);
void* _AFPreferencesSetApplySASToFirstPartyDomains(void);
void* _AFPreferencesSetClientFlowLocalDevelopment(void);
void* _AFPreferencesSetCloudSyncEnabledModificationDate(void);
void* _AFPreferencesSetCloudUserID(void);
void* _AFPreferencesSetCompanionMessagingEnabled(void);
void* _AFPreferencesSetCountryCode(void);
void* _AFPreferencesSetDatabaseSyncingEnabled(void);
void* _AFPreferencesSetDictationLanguageDetectorEnabled(void);
void* _AFPreferencesSetDictationLanguageDetectorEnabledByServer(void);
void* _AFPreferencesSetEnableSiriDebugUI(void);
void* _AFPreferencesSetEnableSpeakerGradingDebugUI(void);
void* _AFPreferencesSetEnabledDragAndDrop(void);
void* _AFPreferencesSetEnabledNonFullScreen(void);
void* _AFPreferencesSetForceRTL(void);
void* _AFPreferencesSetForceSpeexAudioRecording(void);
void* _AFPreferencesSetForceUncompressedAudioRecording(void);
void* _AFPreferencesSetIgnoreEVFailures(void);
void* _AFPreferencesSetInProgressOutputVoice(void);
void* _AFPreferencesSetInitialInterstitialDelay(void);
void* _AFPreferencesSetInitialInterstitialDelayForVoiceTriggerOneShotWithoutAudioDucking(void);
void* _AFPreferencesSetLanguageCode(void);
void* _AFPreferencesSetLastPushedCensorSpeechSetting(void);
void* _AFPreferencesSetLimitedPersistentAudioLogging(void);
void* _AFPreferencesSetLowerWristEducationHeaderDisplayCount(void);
void* _AFPreferencesSetMirroredTCCInfo(void);
void* _AFPreferencesSetMultilingualDictationTimeoutInMilliSeconds(void);
void* _AFPreferencesSetMyriadConstantGoodness(void);
void* _AFPreferencesSetMyriadDeviceAdjust(void);
void* _AFPreferencesSetMyriadDeviceClass(void);
void* _AFPreferencesSetMyriadDeviceDelay(void);
void* _AFPreferencesSetMyriadDeviceGroup(void);
void* _AFPreferencesSetMyriadDeviceSlowdown(void);
void* _AFPreferencesSetMyriadDeviceTrumpDelay(void);
void* _AFPreferencesSetMyriadLastWin(void);
void* _AFPreferencesSetMyriadServerHasProvisioned(void);
void* _AFPreferencesSetMyriadServerProvisioning(void);
void* _AFPreferencesSetNetworkLoggingEnabled(void);
void* _AFPreferencesSetNonManateeIdentity(void);
void* _AFPreferencesSetNotificationPreviewRestrictedApps(void);
void* _AFPreferencesSetOpportuneSpeakingEdgeDetectorSignalOverride(void);
void* _AFPreferencesSetOpportuneSpeakingModelUsed(void);
void* _AFPreferencesSetOpportuneSpeakingModuleEnabled(void);
void* _AFPreferencesSetOpportuneSpeakingPause(void);
void* _AFPreferencesSetOpportuneSpeakingTimeout(void);
void* _AFPreferencesSetOutputVoice(void);
void* _AFPreferencesSetPluginTimeoutDisabled(void);
void* _AFPreferencesSetShouldCensorSpeechInternal(void);
void* _AFPreferencesSetShouldSyncFirstPartyAppIntentPolicy(void);
void* _AFPreferencesSetShowAllDialogVariantsEnabled(void);
void* _AFPreferencesSetSiriDataSharingOptInAlertPresented(void);
void* _AFPreferencesSetSiriDataSharingOptInStatus(void);
void* _AFPreferencesSetSiriDesignModeEnabled(void);
void* _AFPreferencesSetSpokenNotificationPlayAlertBeforeTriggerlessListening(void);
void* _AFPreferencesSetSpokenNotificationQuickIgnoreTime(void);
void* _AFPreferencesSetSpokenNotificationShouldAlwaysSpeakNotifications(void);
void* _AFPreferencesSetSpokenNotificationShouldSkipTriggerlessReplies(void);
void* _AFPreferencesSetSpokenNotificationShowUIDuringTriggerlessListening(void);
void* _AFPreferencesSetSpokenNotificationSkipTriggerlessReplyConfirmation(void);
void* _AFPreferencesSetSpokenNotificationTemporarilyDisabledEndDate(void);
void* _AFPreferencesSetSpokenNotificationTemporarilyDisabledEndDateForApp(void);
void* _AFPreferencesSetSpokenNotificationsEnabledForNano(void);
void* _AFPreferencesSetSpokenNotificationsProxCardSeen(void);
void* _AFPreferencesSetTFO(void);
void* _AFPreferencesSetUseMyriadCoordination(void);
void* _AFPreferencesSetUseMyriadDucking(void);
void* _AFPreferencesSetUseSASAutoSelectionFeature(void);
void* _AFPreferencesSetValueForKey(void);
void* _AFPreferencesSetVibrateWithAlert(void);
void* _AFPreferencesSetVibrationCount(void);
void* _AFPreferencesSetVibrationDuration(void);
void* _AFPreferencesSetVibrationGap(void);
void* _AFPreferencesSetVibrationIntensity(void);
void* _AFPreferencesSetWebInspectorEnabled(void);
void* _AFPreferencesSetiRATManagerRecommendationEnabled(void);
void* _AFPreferencesShouldCensorSpeechInternal(void);
void* _AFPreferencesShouldSuppressSiriDataSharingOptInAlert(void);
void* _AFPreferencesShouldSyncFirstPartyAppIntentPolicy(void);
void* _AFPreferencesShouldUseTFO(void);
void* _AFPreferencesShowAllDialogVariantsEnabled(void);
void* _AFPreferencesSiriDataSharingOptInStatus(void);
void* _AFPreferencesSiriDesignModeIsEnabled(void);
void* _AFPreferencesSiriMiniEnabled(void);
void* _AFPreferencesSiriMiniExperimentationEnabled(void);
void* _AFPreferencesSiriMiniPreferredEnabled(void);
void* _AFPreferencesSiriMiniResultHoldTime(void);
void* _AFPreferencesSiriMiniSupported(void);
void* _AFPreferencesSiriPersonalizedASRDisabled(void);
void* _AFPreferencesSpokenNotificationPlayAlertBeforeTriggerlessListening(void);
void* _AFPreferencesSpokenNotificationQuickIgnoreTime(void);
void* _AFPreferencesSpokenNotificationShouldAlwaysSpeakNotifications(void);
void* _AFPreferencesSpokenNotificationShouldSkipTriggerlessReplies(void);
void* _AFPreferencesSpokenNotificationShowUIDuringTriggerlessListening(void);
void* _AFPreferencesSpokenNotificationSkipTriggerlessReplyConfirmation(void);
void* _AFPreferencesSpokenNotificationTemporarilyDisabledEndDate(void);
void* _AFPreferencesSpokenNotificationTemporarilyDisabledEndDateForApp(void);
void* _AFPreferencesSpokenNotificationsEnabledForNano(void);
void* _AFPreferencesSpokenNotificationsProxCardSeen(void);
void* _AFPreferencesSyncFromWatchEnabled(void);
void* _AFPreferencesUseMyriadCoordination(void);
void* _AFPreferencesUseMyriadDucking(void);
void* _AFPreferencesUseSASAutoSelectionFeature(void);
void* _AFPreferencesValueForKey(void);
void* _AFPreferencesVibrateWithAlert(void);
void* _AFPreferencesVibrationCount(void);
void* _AFPreferencesVibrationDuration(void);
void* _AFPreferencesVibrationGap(void);
void* _AFPreferencesVibrationIntensity(void);
void* _AFPreferencesWebInspectorEnabled(void);
void* _AFPreferencesiRATManagerRecommendationEnabled(void);
void* _AFRedactedCopyPerson(void);
void* _AFRedactedFamilyNamesCopyPerson(void);
void* _AFServiceLog(void);
void* _AFSupportPreferencesSetValueForKey(void);
void* _AFSupportPreferencesValueForKey(void);
void* _ExternalRequestConnection(void);
void* carplayTriggerSeenCallback(void);
void* defaultsCallback(void);
void* emergencyCallInitiatedCallback(void);
void* emergencyCallPunchoutCallback(void);
void* emergencyCallback(void);
void* emergencyHandledCallback(void);
void* hammingDistance(void);
void* inEarTriggerSeenCallback(void);
void* myriadDecisionRequestCallback(void);
void* notificationCallback(void);
void* outputTriggerSeenCallback(void);
void* safelyGetAudioData(void);

#endif
