#!/bin/sh
set -e

DATE=$(date +%Y%m%d)
rm -f debian/changelog
EDITOR=true NAME="Darling build server" EMAIL=noreply@darlinghq.org dch -u low -v 0.1.${DATE} --create --distribution testing --package darling "Daily build"
debuild -us -uc -b
