#!/bin/sh
set -e

DATE=$(date +%Y%m%d)
rm -f debian/changelog
EDITOR=true NAME="Darling build server" EMAIL=noreply@darlinghq.org dch -u low -v 0.1.${DATE} --create --distribution testing --package darling "Daily build"

if [ "$1" = "--dsc" ]; then
    ARG='-S'
    if [ -e "../darling_0.1.${DATE}.orig.tar.xz" ]; then
        rm ../darling_0.1.${DATE}.orig.tar.xz
    fi
    tar --exclude-vcs --exclude-vcs-ignores -cJf ../darling_0.1.${DATE}.orig.tar.xz .
    tar -rJf ../darling_0.1.${DATE}.orig.tar.xz debian/changelog
else
    ARG='-b'
fi

debuild -us -uc ${ARG}
