#!/bin/sh
set +e

if [ "$(whoami)" != "root" ]
then
	echo "Uninstall must be run as root, invoking sudo"
	sudo su -c "$0"
	exit
fi

DARLING_PREFIX="$(dirname "$(dirname "$(which darling)")")"

if command -v darling
then
	darling shutdown
fi
if [ -d "${DARLING_PREFIX}/libexec" ]
then
	rm -rf "${DARLING_PREFIX}/libexec/darling"
	rmdir --ignore-fail-on-non-empty "${DARLING_PREFIX}/libexec"
fi
rm -f "${DARLING_PREFIX}/bin/darling"
find /lib/modules -name darling-mach.ko -delete
echo "Uninstall complete"
