#!/bin/sh
set +e

if [ "$(whoami)" != "root" ]
then
	echo "Uninstall must be run as root, invoking sudo"
	sudo su -c "$0"
	exit
fi

INSTALL_PREFIX="$(dirname "$(dirname "$(which darling)")")"

if command -v darling
then
	darling shutdown
fi
if [ -d "${INSTALL_PREFIX}/libexec" ]
then
	rm -rf "${INSTALL_PREFIX}/libexec/darling"
	rmdir --ignore-fail-on-non-empty "${INSTALL_PREFIX}/libexec"
fi
rm -f "${INSTALL_PREFIX}/bin/darling"
rm -f "${INSTALL_PREFIX}/bin/darlingserver"
rm -f "${INSTALL_PREFIX}/bin/darling-coredump"
find /lib/modules -name darling-mach.ko -delete
echo "Uninstall complete"
