.TH MIGCOM 1 "Nov 20, 2009" "Apple Computer, Inc."
.SH NAME
migcom \- Mach Interface Generator COMpiler
.SH SYNOPSIS
.B migcom
[ 
.I "option \&..."
] 
.I "<file"
 
.SH DESCRIPTION
.I migcom
is the actual compiler used by the
.I mig
command to generate Remote Procedure Call (RPC) source code for
client-server style Mach IPC from specification files. It is not normally
used independently. Rather, it is invoked by the
.I mig
command after pre-processing the provided specifications file with the C
preprocessor. It is only documented here for the sake of completeness.
.SH OPTIONS
.TP
.B \-q/-Q
Omit /
.I emit
warning messages.
.TP
.B \-v/-V
Verbose mode ( on /
.I off
) will summarize types and routines as they are processed.
.TP
.B \-l/-L
Controls (
.I off
/ on ) whether or not generated code logs RPC events to system logs.
.TP
.B \-k/-K
Controls (
.I on
/ off ) whether generated code complies with ANSI C standards.
.TP
.B \-s/-S
Controls ( on /
.I off
) whether generated server-side code includes a generated symbol table.
.TP
.BI \-i " prefix"
Specify User file prefix.
.TP
.BI \-user " path"
Specify name of user-side RPC generated source file.
.TP
.BI \-server " path"
Specify name of server-side RPC generated source file.
.TP
.BI \-header " path"
Specify name of user-side generated header file.
.TP
.BI \-sheader " path"
Specify name of server-side generated header file.
.TP
.BI \-iheader " path"
Specify internal header file name.
.TP
.BI \-dheader " path"
Specify defines generated header file.
.TP
.BI \-maxonstack " value"
Specify maximum size of message on stack.
.TP
.B \-split
Use split headers.
