/*
 This file is part of Darling.

 Copyright (C) 2017 Lubos Dolezel

 Darling is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Darling is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Darling.  If not, see <http://www.gnu.org/licenses/>.
*/


#ifndef _WebKit_H_
#define _WebKit_H_

#import <Foundation/Foundation.h>

#import <WebKit/CAAnimationDelegate.h>
#import <WebKit/NSCandidateListTouchBarItemDelegate.h>
#import <WebKit/NSGestureRecognizerDelegate.h>
#import <WebKit/NSImmediateActionAnimationController.h>
#import <WebKit/NSImmediateActionGestureRecognizerDelegate.h>
#import <WebKit/NSSharingServiceDelegate.h>
#import <WebKit/NSSharingServicePickerDelegate.h>
#import <WebKit/NSTextFinderAsynchronousDocumentFindMatch.h>
#import <WebKit/NSTextInputClient.h>
#import <WebKit/NSTouchBarDelegate.h>
#import <WebKit/NSTouchBarProvider.h>
#import <WebKit/NSURLAuthenticationChallengeSender.h>
#import <WebKit/NSURLConnectionDelegate.h>
#import <WebKit/NSURLSessionDataDelegate.h>
#import <WebKit/NSURLSessionDelegate.h>
#import <WebKit/NSURLSessionTaskDelegate.h>
#import <WebKit/NSUserInterfaceValidations.h>
#import <WebKit/NSWindowDelegate.h>
#import <WebKit/PDFLayerControllerDelegate.h>
#import <WebKit/PKPaymentAuthorizationViewControllerDelegate.h>
#import <WebKit/PKPaymentAuthorizationViewControllerPrivateDelegate.h>
#import <WebKit/QLPreviewMenuItemDelegate.h>
#import <WebKit/WKInspectorViewControllerDelegate.h>
#import <WebKit/WKInspectorWKWebViewDelegate.h>
#import <WebKit/WKNavigationDelegate.h>
#import <WebKit/WKObject.h>
#import <WebKit/WKUIDelegate.h>
#import <WebKit/WKURLSchemeTask.h>
#import <WebKit/WKURLSchemeTaskPrivate.h>
#import <WebKit/WKWebProcessPlugIn.h>
#import <WebKit/WebViewImplDelegate.h>
#import <WebKit/_WKErrorRecoveryAttempting.h>
#import <WebKit/_WKObservablePageState.h>
#import <WebKit/_WKActivatedElementInfo.h>
#import <WebKit/_WKApplicationManifest.h>
#import <WebKit/_WKAttachmentDisplayOptions.h>
#import <WebKit/_WKAttachment.h>
#import <WebKit/_WKAutomationSession.h>
#import <WebKit/_WKAutomationSessionConfiguration.h>
#import <WebKit/_WKContextMenuElementInfo.h>
#import <WebKit/_WKDownload.h>
#import <WebKit/_WKExperimentalFeature.h>
#import <WebKit/_WKFrameHandle.h>
#import <WebKit/_WKHitTestResult.h>
#import <WebKit/_WKLinkIconParameters.h>
#import <WebKit/_WKProcessPoolConfiguration.h>
#import <WebKit/_WKRemoteObjectInterface.h>
#import <WebKit/_WKRemoteObjectRegistry.h>
#import <WebKit/_WKRemoteWebInspectorViewController.h>
#import <WebKit/_WKSessionState.h>
#import <WebKit/_WKThumbnailView.h>
#import <WebKit/_WKUserContentExtensionStore.h>
#import <WebKit/_WKUserContentFilter.h>
#import <WebKit/_WKUserContentWorld.h>
#import <WebKit/_WKUserInitiatedAction.h>
#import <WebKit/_WKUserStyleSheet.h>
#import <WebKit/_WKVisitedLinkStore.h>
#import <WebKit/_WKWebsiteDataSize.h>
#import <WebKit/_WKWebsiteDataStore.h>
#import <WebKit/_WKWebsiteDataStoreConfiguration.h>
#import <WebKit/_WKWebsitePolicies.h>
#import <WebKit/WKCustomProtocolLoader.h>
#import <WebKit/WKCustomProtocol.h>
#import <WebKit/WKNetworkSessionDelegate.h>
#import <WebKit/WKPDFPluginAccessibilityObject.h>
#import <WebKit/WKPDFPluginScrollbarLayer.h>
#import <WebKit/WKPDFLayerControllerDelegate.h>
#import <WebKit/WKAnimationDelegate.h>
#import <WebKit/WKPlaceholderModalWindow.h>
#import <WebKit/WKRemoteWebInspectorProxyObjCAdapter.h>
#import <WebKit/WKLayerHostView.h>
#import <WebKit/WKSwipeCancellationTracker.h>
#import <WebKit/WKUserDataWrapper.h>
#import <WebKit/WKSelectionHandlerWrapper.h>
#import <WebKit/WKMenuTarget.h>
#import <WebKit/WKWebInspectorProxyObjCAdapter.h>
#import <WebKit/WKPaymentAuthorizationViewControllerDelegate.h>
#import <WebKit/WKAccessibilitySettingsObserver.h>
#import <WebKit/WKWindowVisibilityObserver.h>
#import <WebKit/WKEditCommandObjC.h>
#import <WebKit/WKEditorUndoTargetObjC.h>
#import <WebKit/WKFlippedView.h>
#import <WebKit/WKResponderChainSink.h>
#import <WebKit/WKTextListTouchBarViewController.h>
#import <WebKit/WKTextTouchBarItemController.h>
#import <WebKit/WKAccessibilityWebPageObjectBase.h>
#import <WebKit/WKAccessibilityWebPageObject.h>
#import <WebKit/WKBackForwardList.h>
#import <WebKit/WKBackForwardListItem.h>
#import <WebKit/WKBrowsingContextController.h>
#import <WebKit/WKBrowsingContextGroup.h>
#import <WebKit/WKBrowsingContextHandle.h>
#import <WebKit/WKConnection.h>
#import <WebKit/WKContentRuleList.h>
#import <WebKit/WKContentRuleListStore.h>
#import <WebKit/WKDOMDocument.h>
#import <WebKit/WKDOMElement.h>
#import <WebKit/WKDOMNode.h>
#import <WebKit/WKDOMRange.h>
#import <WebKit/WKDOMText.h>
#import <WebKit/WKDOMTextIterator.h>
#import <WebKit/WKFrameInfo.h>
#import <WebKit/WKFullKeyboardAccessWatcher.h>
#import <WebKit/WKFullScreenWindowController.h>
#import <WebKit/WKHTTPCookieStore.h>
#import <WebKit/WKAnimationController.h>
#import <WebKit/WKImmediateActionController.h>
#import <WebKit/WKInspectorViewController.h>
#import <WebKit/WKInspectorWKWebView.h>
#import <WebKit/WKNavigation.h>
#import <WebKit/WKNavigationAction.h>
#import <WebKit/WKNavigationData.h>
#import <WebKit/WKNavigationResponse.h>
#import <WebKit/WKNSArray.h>
#import <WebKit/WKNSData.h>
#import <WebKit/WKNSDictionary.h>
#import <WebKit/WKNSError.h>
#import <WebKit/WKNSNumber.h>
#import <WebKit/WKNSString.h>
#import <WebKit/WKNSURL.h>
#import <WebKit/WKNSURLAuthenticationChallenge.h>
#import <WebKit/WKNSURLAuthenticationChallengeSender.h>
#import <WebKit/WKNSURLRequest.h>
#import <WebKit/WKObject.h>
#import <WebKit/WKOpenPanelParameters.h>
#import <WebKit/WKObservablePageState.h>
#import <WebKit/WKPreferences.h>
#import <WebKit/WKPrintingView.h>
#import <WebKit/WKProcessGroup.h>
#import <WebKit/WKProcessPool.h>
#import <WebKit/WKReloadFrameErrorRecoveryAttempter.h>
#import <WebKit/WKRemoteObject.h>
#import <WebKit/WKRemoteObjectEncoder.h>
#import <WebKit/WKRemoteObjectDecoder.h>
#import <WebKit/WKScriptMessage.h>
#import <WebKit/WKSecurityOrigin.h>
#import <WebKit/WKSharingServicePickerDelegate.h>
#import <WebKit/WKSnapshotConfiguration.h>
#import <WebKit/WKTextFinderMatch.h>
#import <WebKit/WKTextFinderClient.h>
#import <WebKit/WKTextInputView.h>
#import <WebKit/WKTextInputPanel.h>
#import <WebKit/WKTextInputWindowController.h>
#import <WebKit/WKTypeRefWrapper.h>
#import <WebKit/WKURLSchemeTaskImpl.h>
#import <WebKit/WKUserContentController.h>
#import <WebKit/WKUserScript.h>
#import <WebKit/WKViewData.h>
#import <WebKit/WKView.h>
#import <WebKit/WKViewLayoutStrategy.h>
#import <WebKit/WKViewViewSizeLayoutStrategy.h>
#import <WebKit/WKViewFixedSizeLayoutStrategy.h>
#import <WebKit/WKViewDynamicSizeComputedFromViewScaleLayoutStrategy.h>
#import <WebKit/WKViewDynamicSizeComputedFromMinimumDocumentSizeLayoutStrategy.h>
#import <WebKit/WKWebProcessBundleParameters.h>
#import <WebKit/WKWebProcessPlugInController.h>
#import <WebKit/WKWebProcessPlugInBrowserContextController.h>
#import <WebKit/WKWebProcessPlugInFrame.h>
#import <WebKit/WKWebProcessPlugInHitTestResult.h>
#import <WebKit/WKWebProcessPlugInNodeHandle.h>
#import <WebKit/WKWebProcessPlugInPageGroup.h>
#import <WebKit/WKWebProcessPlugInRangeHandle.h>
#import <WebKit/WKWebProcessPlugInScriptWorld.h>
#import <WebKit/WKWebsiteDataRecord.h>
#import <WebKit/WKWebsiteDataStore.h>
#import <WebKit/WKWebView.h>
#import <WebKit/WKWebViewConfiguration.h>
#import <WebKit/WKWindowFeatures.h>

@protocol DOMEventListener
@end

@protocol DOMEventTarget
@end

@protocol DOMNodeFilter
@end

@protocol DOMXPathNSResolver
@end

@protocol WebDocumentRepresentation
@end

@protocol WebDocumentSearching
@end

@protocol WebDocumentText
@end

@protocol WebDocumentView
@end

@protocol WebOpenPanelResultListener
@end

@protocol WebPlugInViewFactory
@end

@protocol WebPolicyDecisionListener
@end

void* DatabaseServiceInitializer(void);
void* NetworkServiceInitializer(void);
void* PluginServiceInitializer(void);
void* WKAccessibilityEnableEnhancedAccessibility(void);
void* WKAccessibilityEnhancedAccessibilityEnabled(void);
void* WKAccessibilityFocusedObject(void);
void* WKAccessibilityRootObject(void);
void* WKApplicationCacheManagerDeleteAllEntries(void);
void* WKApplicationCacheManagerDeleteEntriesForOrigin(void);
void* WKApplicationCacheManagerGetApplicationCacheOrigins(void);
void* WKApplicationCacheManagerGetTypeID(void);
void* WKArrayAppendItem(void);
void* WKArrayCreate(void);
void* WKArrayCreateAdoptingValues(void);
void* WKArrayGetItemAtIndex(void);
void* WKArrayGetSize(void);
void* WKArrayGetTypeID(void);
void* WKArrayRemoveItemAtIndex(void);
void* WKAuthenticationChallengeGetDecisionListener(void);
void* WKAuthenticationChallengeGetPreviousFailureCount(void);
void* WKAuthenticationChallengeGetProposedCredential(void);
void* WKAuthenticationChallengeGetProtectionSpace(void);
void* WKAuthenticationChallengeGetTypeID(void);
void* WKAuthenticationDecisionListenerCancel(void);
void* WKAuthenticationDecisionListenerGetTypeID(void);
void* WKAuthenticationDecisionListenerRejectProtectionSpaceAndContinue(void);
void* WKAuthenticationDecisionListenerUseCredential(void);
void* WKBackForwardListClear(void);
void* WKBackForwardListCopyBackListWithLimit(void);
void* WKBackForwardListCopyForwardListWithLimit(void);
void* WKBackForwardListGetBackItem(void);
void* WKBackForwardListGetBackListCount(void);
void* WKBackForwardListGetCurrentItem(void);
void* WKBackForwardListGetForwardItem(void);
void* WKBackForwardListGetForwardListCount(void);
void* WKBackForwardListGetItemAtIndex(void);
void* WKBackForwardListGetTypeID(void);
void* WKBackForwardListItemCopyOriginalURL(void);
void* WKBackForwardListItemCopyTitle(void);
void* WKBackForwardListItemCopyURL(void);
void* WKBackForwardListItemGetTypeID(void);
void* WKBooleanCreate(void);
void* WKBooleanGetTypeID(void);
void* WKBooleanGetValue(void);
void* WKBundleAddOriginAccessWhitelistEntry(void);
void* WKBundleAddUserScript(void);
void* WKBundleAddUserStyleSheet(void);
void* WKBundleBackForwardListClear(void);
void* WKBundleBackForwardListCopyItemAtIndex(void);
void* WKBundleBackForwardListGetBackListCount(void);
void* WKBundleBackForwardListGetForwardListCount(void);
void* WKBundleBackForwardListGetTypeID(void);
void* WKBundleBackForwardListItemCopyChildren(void);
void* WKBundleBackForwardListItemCopyOriginalURL(void);
void* WKBundleBackForwardListItemCopyTarget(void);
void* WKBundleBackForwardListItemCopyTitle(void);
void* WKBundleBackForwardListItemCopyURL(void);
void* WKBundleBackForwardListItemGetTypeID(void);
void* WKBundleBackForwardListItemHasCachedPageExpired(void);
void* WKBundleBackForwardListItemIsInPageCache(void);
void* WKBundleBackForwardListItemIsSame(void);
void* WKBundleBackForwardListItemIsTargetItem(void);
void* WKBundleClearAllDatabases(void);
void* WKBundleClearResourceLoadStatistics(void);
void* WKBundleCreateWKDataFromUInt8Array(void);
void* WKBundleDOMWindowExtensionCreate(void);
void* WKBundleDOMWindowExtensionGetFrame(void);
void* WKBundleDOMWindowExtensionGetScriptWorld(void);
void* WKBundleDOMWindowExtensionGetTypeID(void);
void* WKBundleFileHandleCreateWithPath(void);
void* WKBundleFileHandleGetTypeID(void);
void* WKBundleFrameAllowsFollowingLink(void);
void* WKBundleFrameCallShouldCloseOnWebView(void);
void* WKBundleFrameClearOpener(void);
void* WKBundleFrameContainsAnyFormControls(void);
void* WKBundleFrameContainsAnyFormElements(void);
void* WKBundleFrameCopyChildFrames(void);
void* WKBundleFrameCopyCounterValue(void);
void* WKBundleFrameCopyInnerText(void);
void* WKBundleFrameCopyLayerTreeAsText(void);
void* WKBundleFrameCopyMIMETypeForResourceWithURL(void);
void* WKBundleFrameCopyName(void);
void* WKBundleFrameCopyProvisionalURL(void);
void* WKBundleFrameCopySecurityOrigin(void);
void* WKBundleFrameCopySuggestedFilenameForResourceWithURL(void);
void* WKBundleFrameCopyURL(void);
void* WKBundleFrameCopyWebArchive(void);
void* WKBundleFrameCopyWebArchiveFilteringSubframes(void);
void* WKBundleFrameCreateFrameHandle(void);
void* WKBundleFrameCreateHitTestResult(void);
void* WKBundleFrameFocus(void);
void* WKBundleFrameForJavaScriptContext(void);
void* WKBundleFrameGetContentBounds(void);
void* WKBundleFrameGetDocumentBackgroundColor(void);
void* WKBundleFrameGetFrameLoadState(void);
void* WKBundleFrameGetJavaScriptContext(void);
void* WKBundleFrameGetJavaScriptContextForWorld(void);
void* WKBundleFrameGetJavaScriptWrapperForFileForWorld(void);
void* WKBundleFrameGetJavaScriptWrapperForNodeForWorld(void);
void* WKBundleFrameGetJavaScriptWrapperForRangeForWorld(void);
void* WKBundleFrameGetPage(void);
void* WKBundleFrameGetParentFrame(void);
void* WKBundleFrameGetPendingUnloadCount(void);
void* WKBundleFrameGetScrollOffset(void);
void* WKBundleFrameGetTypeID(void);
void* WKBundleFrameGetVisibleContentBounds(void);
void* WKBundleFrameGetVisibleContentBoundsExcludingScrollbars(void);
void* WKBundleFrameHandlesPageScaleGesture(void);
void* WKBundleFrameHasHorizontalScrollbar(void);
void* WKBundleFrameHasVerticalScrollbar(void);
void* WKBundleFrameIsMainFrame(void);
void* WKBundleFrameSetAccessibleName(void);
void* WKBundleFrameSetTextDirection(void);
void* WKBundleFrameStopLoading(void);
void* WKBundleGarbageCollectJavaScriptObjects(void);
void* WKBundleGarbageCollectJavaScriptObjectsOnAlternateThreadForDebugging(void);
void* WKBundleGetApplicationConnection(void);
void* WKBundleGetJavaScriptObjectsCount(void);
void* WKBundleGetParameters(void);
void* WKBundleGetTypeID(void);
void* WKBundleGetWebNotificationID(void);
void* WKBundleHitTestResultCopyAbsoluteImageURL(void);
void* WKBundleHitTestResultCopyAbsoluteLinkURL(void);
void* WKBundleHitTestResultCopyAbsoluteMediaURL(void);
void* WKBundleHitTestResultCopyAbsolutePDFURL(void);
void* WKBundleHitTestResultCopyImage(void);
void* WKBundleHitTestResultCopyLinkLabel(void);
void* WKBundleHitTestResultCopyLinkSuggestedFilename(void);
void* WKBundleHitTestResultCopyLinkTitle(void);
void* WKBundleHitTestResultCopyNodeHandle(void);
void* WKBundleHitTestResultCopyURLElementHandle(void);
void* WKBundleHitTestResultGetFrame(void);
void* WKBundleHitTestResultGetImageRect(void);
void* WKBundleHitTestResultGetIsSelected(void);
void* WKBundleHitTestResultGetMediaType(void);
void* WKBundleHitTestResultGetTargetFrame(void);
void* WKBundleHitTestResultGetTypeID(void);
void* WKBundleHitTestResultIsDownloadableMedia(void);
void* WKBundleHitTestResultMediaHasAudio(void);
void* WKBundleHitTestResultMediaIsInFullscreen(void);
void* WKBundleInspectorClose(void);
void* WKBundleInspectorEvaluateScriptForTest(void);
void* WKBundleInspectorGetTypeID(void);
void* WKBundleInspectorSetPageProfilingEnabled(void);
void* WKBundleInspectorShow(void);
void* WKBundleIsPageBoxVisible(void);
void* WKBundleIsProcessingUserGesture(void);
void* WKBundleNavigationActionCopyDownloadAttribute(void);
void* WKBundleNavigationActionCopyFormElement(void);
void* WKBundleNavigationActionCopyHitTestResult(void);
void* WKBundleNavigationActionGetEventModifiers(void);
void* WKBundleNavigationActionGetEventMouseButton(void);
void* WKBundleNavigationActionGetNavigationType(void);
void* WKBundleNavigationActionGetShouldOpenExternalURLs(void);
void* WKBundleNavigationActionGetShouldTryAppLinks(void);
void* WKBundleNavigationActionGetTypeID(void);
void* WKBundleNodeHandleCopyDocument(void);
void* WKBundleNodeHandleCopyDocumentFrame(void);
void* WKBundleNodeHandleCopyHTMLFrameElementContentFrame(void);
void* WKBundleNodeHandleCopyHTMLIFrameElementContentFrame(void);
void* WKBundleNodeHandleCopyHTMLTableCellElementCellAbove(void);
void* WKBundleNodeHandleCopySnapshotWithOptions(void);
void* WKBundleNodeHandleCopyVisibleRange(void);
void* WKBundleNodeHandleCreate(void);
void* WKBundleNodeHandleGetElementBounds(void);
void* WKBundleNodeHandleGetHTMLInputElementAutoFillAvailable(void);
void* WKBundleNodeHandleGetHTMLInputElementAutoFillButtonBounds(void);
void* WKBundleNodeHandleGetHTMLInputElementAutoFillButtonEnabled(void);
void* WKBundleNodeHandleGetHTMLInputElementAutoFillButtonType(void);
void* WKBundleNodeHandleGetHTMLInputElementAutoFilled(void);
void* WKBundleNodeHandleGetHTMLInputElementAutofilled(void);
void* WKBundleNodeHandleGetHTMLInputElementLastAutoFillButtonType(void);
void* WKBundleNodeHandleGetHTMLInputElementLastChangeWasUserEdit(void);
void* WKBundleNodeHandleGetHTMLTextAreaElementLastChangeWasUserEdit(void);
void* WKBundleNodeHandleGetRenderRect(void);
void* WKBundleNodeHandleGetTypeID(void);
void* WKBundleNodeHandleSetHTMLInputElementAutoFillAvailable(void);
void* WKBundleNodeHandleSetHTMLInputElementAutoFillButtonEnabled(void);
void* WKBundleNodeHandleSetHTMLInputElementAutoFillButtonEnabledWithButtonType(void);
void* WKBundleNodeHandleSetHTMLInputElementAutoFilled(void);
void* WKBundleNodeHandleSetHTMLInputElementAutofilled(void);
void* WKBundleNodeHandleSetHTMLInputElementSpellcheckEnabled(void);
void* WKBundleNodeHandleSetHTMLInputElementValueForUser(void);
void* WKBundleNumberOfPages(void);
void* WKBundleOverrideBoolPreferenceForTestRunner(void);
void* WKBundlePageAddUserScript(void);
void* WKBundlePageAddUserStyleSheet(void);
void* WKBundlePageBannerCreateBannerWithCALayer(void);
void* WKBundlePageBannerGetLayer(void);
void* WKBundlePageBannerGetTypeID(void);
void* WKBundlePageCanHandleRequest(void);
void* WKBundlePageCanShowMIMEType(void);
void* WKBundlePageClearApplicationCache(void);
void* WKBundlePageClearApplicationCacheForOrigin(void);
void* WKBundlePageClearMainFrameName(void);
void* WKBundlePageClickMenuItem(void);
void* WKBundlePageClose(void);
void* WKBundlePageConfirmComposition(void);
void* WKBundlePageConfirmCompositionWithText(void);
void* WKBundlePageCopyContextMenuAtPointInWindow(void);
void* WKBundlePageCopyContextMenuItems(void);
void* WKBundlePageCopyGroupIdentifier(void);
void* WKBundlePageCopyOriginsWithApplicationCache(void);
void* WKBundlePageCopyRenderLayerTree(void);
void* WKBundlePageCopyRenderTree(void);
void* WKBundlePageCopyRenderTreeExternalRepresentation(void);
void* WKBundlePageCopyRenderTreeExternalRepresentationForPrinting(void);
void* WKBundlePageCopyTrackedRepaintRects(void);
void* WKBundlePageCreateScaledSnapshotInDocumentCoordinates(void);
void* WKBundlePageCreateSnapshotInDocumentCoordinates(void);
void* WKBundlePageCreateSnapshotInViewCoordinates(void);
void* WKBundlePageCreateSnapshotWithOptions(void);
void* WKBundlePageDidEnterFullScreen(void);
void* WKBundlePageDidExitFullScreen(void);
void* WKBundlePageExecuteEditingCommand(void);
void* WKBundlePageExtendIncrementalRenderingSuppression(void);
void* WKBundlePageFindString(void);
void* WKBundlePageForceRepaint(void);
void* WKBundlePageGetAppCacheUsageForOrigin(void);
void* WKBundlePageGetBackForwardList(void);
void* WKBundlePageGetBackingScaleFactor(void);
void* WKBundlePageGetInspector(void);
void* WKBundlePageGetMainFrame(void);
void* WKBundlePageGetPageGroup(void);
void* WKBundlePageGetPageZoomFactor(void);
void* WKBundlePageGetRenderTreeSize(void);
void* WKBundlePageGetTextZoomFactor(void);
void* WKBundlePageGetTypeID(void);
void* WKBundlePageGroupCopyIdentifier(void);
void* WKBundlePageGroupGetTypeID(void);
void* WKBundlePageHasComposition(void);
void* WKBundlePageHasLocalDataForURL(void);
void* WKBundlePageInsertNewlineInQuotedContent(void);
void* WKBundlePageInstallPageOverlay(void);
void* WKBundlePageInstallPageOverlayWithAnimation(void);
void* WKBundlePageIsControlledByAutomation(void);
void* WKBundlePageIsEditingCommandEnabled(void);
void* WKBundlePageIsTrackingRepaints(void);
void* WKBundlePageIsUsingEphemeralSession(void);
void* WKBundlePageListenForLayoutMilestones(void);
void* WKBundlePageNumberForElementById(void);
void* WKBundlePageOverlayClear(void);
void* WKBundlePageOverlayCreate(void);
void* WKBundlePageOverlayFractionFadedIn(void);
void* WKBundlePageOverlayGetTypeID(void);
void* WKBundlePageOverlaySetAccessibilityClient(void);
void* WKBundlePageOverlaySetNeedsDisplay(void);
void* WKBundlePagePostMessage(void);
void* WKBundlePagePostSynchronousMessageForTesting(void);
void* WKBundlePageRegisterScrollOperationCompletionCallback(void);
void* WKBundlePageRemoveAllUserContent(void);
void* WKBundlePageResetApplicationCacheOriginQuota(void);
void* WKBundlePageResetTrackedRepaints(void);
void* WKBundlePageSetAppCacheMaximumSize(void);
void* WKBundlePageSetApplicationCacheOriginQuota(void);
void* WKBundlePageSetBottomOverhangImage(void);
void* WKBundlePageSetComposition(void);
void* WKBundlePageSetContextMenuClient(void);
void* WKBundlePageSetDefersLoading(void);
void* WKBundlePageSetEditorClient(void);
void* WKBundlePageSetEventThrottlingBehaviorOverride(void);
void* WKBundlePageSetFooterBanner(void);
void* WKBundlePageSetFormClient(void);
void* WKBundlePageSetFullScreenClient(void);
void* WKBundlePageSetHeaderBanner(void);
void* WKBundlePageSetPageLoaderClient(void);
void* WKBundlePageSetPageZoomFactor(void);
void* WKBundlePageSetPaintedObjectsCounterThreshold(void);
void* WKBundlePageSetPolicyClient(void);
void* WKBundlePageSetResourceLoadClient(void);
void* WKBundlePageSetScaleAtOrigin(void);
void* WKBundlePageSetTextZoomFactor(void);
void* WKBundlePageSetTopOverhangImage(void);
void* WKBundlePageSetTracksRepaints(void);
void* WKBundlePageSetUIClient(void);
void* WKBundlePageSimulateMouseDown(void);
void* WKBundlePageSimulateMouseMotion(void);
void* WKBundlePageSimulateMouseUp(void);
void* WKBundlePageSizeAndMarginsInPixels(void);
void* WKBundlePageStartMonitoringScrollOperations(void);
void* WKBundlePageStopExtendingIncrementalRenderingSuppression(void);
void* WKBundlePageStopLoading(void);
void* WKBundlePageUninstallPageOverlay(void);
void* WKBundlePageUninstallPageOverlayWithAnimation(void);
void* WKBundlePageWillEnterFullScreen(void);
void* WKBundlePageWillExitFullScreen(void);
void* WKBundlePostMessage(void);
void* WKBundlePostSynchronousMessage(void);
void* WKBundleRangeHandleCopySnapshotWithOptions(void);
void* WKBundleRangeHandleCreate(void);
void* WKBundleRangeHandleGetBoundingRectInWindowCoordinates(void);
void* WKBundleRangeHandleGetTypeID(void);
void* WKBundleRemoveAllUserContent(void);
void* WKBundleRemoveAllWebNotificationPermissions(void);
void* WKBundleRemoveOriginAccessWhitelistEntry(void);
void* WKBundleRemoveUserScript(void);
void* WKBundleRemoveUserScripts(void);
void* WKBundleRemoveUserStyleSheet(void);
void* WKBundleRemoveUserStyleSheets(void);
void* WKBundleReportException(void);
void* WKBundleResetOriginAccessWhitelists(void);
void* WKBundleResourceLoadStatisticsNotifyObserver(void);
void* WKBundleScriptWorldClearWrappers(void);
void* WKBundleScriptWorldCopyName(void);
void* WKBundleScriptWorldCreateWorld(void);
void* WKBundleScriptWorldGetTypeID(void);
void* WKBundleScriptWorldMakeAllShadowRootsOpen(void);
void* WKBundleScriptWorldNormalWorld(void);
void* WKBundleSetAllowFileAccessFromFileURLs(void);
void* WKBundleSetAllowStorageAccessFromFileURLS(void);
void* WKBundleSetAllowUniversalAccessFromFileURLs(void);
void* WKBundleSetAsyncFrameScrollingEnabled(void);
void* WKBundleSetAsynchronousSpellCheckingEnabled(void);
void* WKBundleSetAuthorAndUserStylesEnabled(void);
void* WKBundleSetClient(void);
void* WKBundleSetDatabaseQuota(void);
void* WKBundleSetFrameFlatteningEnabled(void);
void* WKBundleSetJavaScriptCanAccessClipboard(void);
void* WKBundleSetMinimumLogicalFontSize(void);
void* WKBundleSetPopupBlockingEnabled(void);
void* WKBundleSetPrivateBrowsingEnabled(void);
void* WKBundleSetServiceWorkerProxyCreationCallback(void);
void* WKBundleSetSpatialNavigationEnabled(void);
void* WKBundleSetTabKeyCyclesThroughElements(void);
void* WKBundleSetUseDashboardCompatibilityMode(void);
void* WKBundleSetUserStyleSheetLocation(void);
void* WKBundleSetWebNotificationPermission(void);
void* WKCertificateInfoCreateWithCertficateChain(void);
void* WKCertificateInfoCreateWithServerTrust(void);
void* WKCertificateInfoGetCertificateChain(void);
void* WKCertificateInfoGetServerTrust(void);
void* WKCertificateInfoGetTypeID(void);
void* WKConnectionGetTypeID(void);
void* WKConnectionPostMessage(void);
void* WKConnectionSetConnectionClient(void);
void* WKContextAddVisitedLink(void);
void* WKContextAllowSpecificHTTPSCertificateForHost(void);
void* WKContextClearCachedCredentials(void);
void* WKContextClearPluginClientPolicies(void);
void* WKContextClearVisitedLinks(void);
void* WKContextConfigurationCopyApplicationCacheDirectory(void);
void* WKContextConfigurationCopyDiskCacheDirectory(void);
void* WKContextConfigurationCopyIndexedDBDatabaseDirectory(void);
void* WKContextConfigurationCopyInjectedBundlePath(void);
void* WKContextConfigurationCopyLocalStorageDirectory(void);
void* WKContextConfigurationCopyMediaKeysStorageDirectory(void);
void* WKContextConfigurationCopyOverrideLanguages(void);
void* WKContextConfigurationCopyResourceLoadStatisticsDirectory(void);
void* WKContextConfigurationCopyWebSQLDatabaseDirectory(void);
void* WKContextConfigurationCreate(void);
void* WKContextConfigurationCreateWithLegacyOptions(void);
void* WKContextConfigurationFullySynchronousModeIsAllowedForTesting(void);
void* WKContextConfigurationSetApplicationCacheDirectory(void);
void* WKContextConfigurationSetDiskCacheDirectory(void);
void* WKContextConfigurationSetFullySynchronousModeIsAllowedForTesting(void);
void* WKContextConfigurationSetIndexedDBDatabaseDirectory(void);
void* WKContextConfigurationSetInjectedBundlePath(void);
void* WKContextConfigurationSetLocalStorageDirectory(void);
void* WKContextConfigurationSetMediaKeysStorageDirectory(void);
void* WKContextConfigurationSetOverrideLanguages(void);
void* WKContextConfigurationSetResourceLoadStatisticsDirectory(void);
void* WKContextConfigurationSetShouldCaptureAudioInUIProcess(void);
void* WKContextConfigurationSetWebSQLDatabaseDirectory(void);
void* WKContextConfigurationShouldCaptureAudioInUIProcess(void);
void* WKContextCopyPlugInAutoStartOriginHashes(void);
void* WKContextCopyPlugInInfoForBundleIdentifier(void);
void* WKContextCreate(void);
void* WKContextCreateWithConfiguration(void);
void* WKContextCreateWithInjectedBundlePath(void);
void* WKContextDisableProcessTermination(void);
void* WKContextDownloadURLRequest(void);
void* WKContextEnableProcessTermination(void);
void* WKContextGarbageCollectJavaScriptObjects(void);
void* WKContextGetApplicationCacheManager(void);
void* WKContextGetCacheModel(void);
void* WKContextGetCookieManager(void);
void* WKContextGetDatabaseProcessIdentifier(void);
void* WKContextGetGeolocationManager(void);
void* WKContextGetGlobalStatistics(void);
void* WKContextGetIconDatabase(void);
void* WKContextGetInfoForInstalledPlugIns(void);
void* WKContextGetKeyValueStorageManager(void);
void* WKContextGetMaximumNumberOfProcesses(void);
void* WKContextGetMediaSessionFocusManager(void);
void* WKContextGetNetworkProcessIdentifier(void);
void* WKContextGetNotificationManager(void);
void* WKContextGetResourceCacheManager(void);
void* WKContextGetStatistics(void);
void* WKContextGetStatisticsWithOptions(void);
void* WKContextGetTypeID(void);
void* WKContextGetWebsiteDataStore(void);
void* WKContextIsPlugInUpdateAvailable(void);
void* WKContextJavaScriptConfigurationFileEnabled(void);
void* WKContextMenuCopySubmenuItems(void);
void* WKContextMenuItemCopyTitle(void);
void* WKContextMenuItemCreateAsAction(void);
void* WKContextMenuItemCreateAsCheckableAction(void);
void* WKContextMenuItemCreateAsSubmenu(void);
void* WKContextMenuItemGetChecked(void);
void* WKContextMenuItemGetEnabled(void);
void* WKContextMenuItemGetTag(void);
void* WKContextMenuItemGetType(void);
void* WKContextMenuItemGetTypeID(void);
void* WKContextMenuItemGetUserData(void);
void* WKContextMenuItemSeparatorItem(void);
void* WKContextMenuItemSetUserData(void);
void* WKContextMenuListenerGetTypeID(void);
void* WKContextMenuListenerUseContextMenuItems(void);
void* WKContextPostMessageToInjectedBundle(void);
void* WKContextPreconnectToServer(void);
void* WKContextRefreshPlugIns(void);
void* WKContextRegisterSchemeForCustomProtocol(void);
void* WKContextRegisterURLSchemeAsBypassingContentSecurityPolicy(void);
void* WKContextRegisterURLSchemeAsCachePartitioned(void);
void* WKContextRegisterURLSchemeAsEmptyDocument(void);
void* WKContextRegisterURLSchemeAsSecure(void);
void* WKContextResetHSTSHosts(void);
void* WKContextResetHSTSHostsAddedAfterDate(void);
void* WKContextResumeDownload(void);
void* WKContextSetAdditionalPluginsDirectory(void);
void* WKContextSetAllowsAnySSLCertificateForServiceWorkerTesting(void);
void* WKContextSetAllowsAnySSLCertificateForWebSocketTesting(void);
void* WKContextSetAlwaysUsesComplexTextCodePath(void);
void* WKContextSetCacheModel(void);
void* WKContextSetCanHandleHTTPSServerTrustEvaluation(void);
void* WKContextSetClient(void);
void* WKContextSetConnectionClient(void);
void* WKContextSetCookieStorageDirectory(void);
void* WKContextSetDiskCacheSpeculativeValidationEnabled(void);
void* WKContextSetDomainRelaxationForbiddenForURLScheme(void);
void* WKContextSetDownloadClient(void);
void* WKContextSetFontWhitelist(void);
void* WKContextSetHTTPPipeliningEnabled(void);
void* WKContextSetHistoryClient(void);
void* WKContextSetIconDatabasePath(void);
void* WKContextSetInitializationUserDataForInjectedBundle(void);
void* WKContextSetInjectedBundleClient(void);
void* WKContextSetInvalidMessageFunction(void);
void* WKContextSetJavaScriptConfigurationFileEnabled(void);
void* WKContextSetJavaScriptGarbageCollectorTimerEnabled(void);
void* WKContextSetMaximumNumberOfProcesses(void);
void* WKContextSetMemoryCacheDisabled(void);
void* WKContextSetPlugInAutoStartOriginHashes(void);
void* WKContextSetPlugInAutoStartOrigins(void);
void* WKContextSetPlugInAutoStartOriginsFilteringOutEntriesAddedAfterTime(void);
void* WKContextSetPluginLoadClientPolicy(void);
void* WKContextSetProcessModel(void);
void* WKContextSetShouldUseFontSmoothing(void);
void* WKContextSetUsesNetworkProcess(void);
void* WKContextShouldBlockWebGL(void);
void* WKContextShouldSuggestBlockWebGL(void);
void* WKContextStartMemorySampler(void);
void* WKContextStopMemorySampler(void);
void* WKContextTerminateNetworkProcess(void);
void* WKContextTerminateServiceWorkerProcess(void);
void* WKContextUnregisterSchemeForCustomProtocol(void);
void* WKContextUseTestingNetworkSession(void);
void* WKContextWarmInitialProcess(void);
void* WKCookieManagerDeleteAllCookies(void);
void* WKCookieManagerDeleteAllCookiesModifiedAfterDate(void);
void* WKCookieManagerDeleteCookiesForHostname(void);
void* WKCookieManagerGetHTTPCookieAcceptPolicy(void);
void* WKCookieManagerGetHostnamesWithCookies(void);
void* WKCookieManagerGetTypeID(void);
void* WKCookieManagerSetClient(void);
void* WKCookieManagerSetCookieStoragePartitioningEnabled(void);
void* WKCookieManagerSetHTTPCookieAcceptPolicy(void);
void* WKCookieManagerSetStorageAccessAPIEnabled(void);
void* WKCookieManagerStartObservingCookieChanges(void);
void* WKCookieManagerStopObservingCookieChanges(void);
void* WKCredentialCopyUser(void);
void* WKCredentialCreate(void);
void* WKCredentialCreateWithCertificateInfo(void);
void* WKCredentialGetTypeID(void);
void* WKDataCreate(void);
void* WKDataGetBytes(void);
void* WKDataGetSize(void);
void* WKDataGetTypeID(void);
void* WKDictionaryCopyKeys(void);
void* WKDictionaryCreate(void);
void* WKDictionaryGetItemForKey(void);
void* WKDictionaryGetSize(void);
void* WKDictionaryGetTypeID(void);
void* WKDictionarySetItem(void);
void* WKDoubleCreate(void);
void* WKDoubleGetTypeID(void);
void* WKDoubleGetValue(void);
void* WKDownloadCancel(void);
void* WKDownloadCopyRedirectChain(void);
void* WKDownloadCopyRequest(void);
void* WKDownloadGetID(void);
void* WKDownloadGetOriginatingPage(void);
void* WKDownloadGetResumeData(void);
void* WKDownloadGetTypeID(void);
void* WKDownloadGetWasUserInitiated(void);
void* WKErrorCopyCFError(void);
void* WKErrorCopyDomain(void);
void* WKErrorCopyFailingURL(void);
void* WKErrorCopyLocalizedDescription(void);
void* WKErrorCopyWKErrorDomain(void);
void* WKErrorCreateWithCFError(void);
void* WKErrorGetErrorCode(void);
void* WKErrorGetTypeID(void);
void* WKFormSubmissionListenerContinue(void);
void* WKFormSubmissionListenerGetTypeID(void);
void* WKFrameCanProvideSource(void);
void* WKFrameCanShowMIMEType(void);
void* WKFrameCopyMIMEType(void);
void* WKFrameCopyProvisionalURL(void);
void* WKFrameCopyTitle(void);
void* WKFrameCopyURL(void);
void* WKFrameCopyUnreachableURL(void);
void* WKFrameCreateFrameHandle(void);
void* WKFrameCreateFrameInfo(void);
void* WKFrameGetCertificateInfo(void);
void* WKFrameGetFrameLoadState(void);
void* WKFrameGetMainResourceData(void);
void* WKFrameGetPage(void);
void* WKFrameGetResourceData(void);
void* WKFrameGetTypeID(void);
void* WKFrameGetWebArchive(void);
void* WKFrameHandleGetFrameID(void);
void* WKFrameHandleGetTypeID(void);
void* WKFrameInfoGetFrameHandleRef(void);
void* WKFrameInfoGetTypeID(void);
void* WKFrameIsDisplayingMarkupDocument(void);
void* WKFrameIsDisplayingStandaloneImageDocument(void);
void* WKFrameIsFrameSet(void);
void* WKFrameIsMainFrame(void);
void* WKFramePolicyListenerDownload(void);
void* WKFramePolicyListenerGetTypeID(void);
void* WKFramePolicyListenerIgnore(void);
void* WKFramePolicyListenerUse(void);
void* WKFramePolicyListenerUseWithPolicies(void);
void* WKFrameStopLoading(void);
void* WKGeolocationManagerGetTypeID(void);
void* WKGeolocationManagerProviderDidChangePosition(void);
void* WKGeolocationManagerProviderDidFailToDeterminePosition(void);
void* WKGeolocationManagerProviderDidFailToDeterminePositionWithErrorMessage(void);
void* WKGeolocationManagerSetProvider(void);
void* WKGeolocationPermissionRequestAllow(void);
void* WKGeolocationPermissionRequestDeny(void);
void* WKGeolocationPermissionRequestGetTypeID(void);
void* WKGeolocationPositionCreate(void);
void* WKGeolocationPositionCreate_b(void);
void* WKGeolocationPositionCreate_c(void);
void* WKGeolocationPositionGetTypeID(void);
void* WKGetAPIURLSchemeTaskInstanceCount(void);
void* WKGetTypeID(void);
void* WKGetWebURLSchemeTaskInstanceCount(void);
void* WKHitTestResultCopyAbsoluteImageURL(void);
void* WKHitTestResultCopyAbsoluteLinkURL(void);
void* WKHitTestResultCopyAbsoluteMediaURL(void);
void* WKHitTestResultCopyAbsolutePDFURL(void);
void* WKHitTestResultCopyLinkLabel(void);
void* WKHitTestResultCopyLinkTitle(void);
void* WKHitTestResultCopyLookupText(void);
void* WKHitTestResultGetElementBoundingBox(void);
void* WKHitTestResultGetTypeID(void);
void* WKHitTestResultIsContentEditable(void);
void* WKIconDatabaseCheckIntegrityBeforeOpening(void);
void* WKIconDatabaseClose(void);
void* WKIconDatabaseCopyIconDataForPageURL(void);
void* WKIconDatabaseCopyIconURLForPageURL(void);
void* WKIconDatabaseEnableDatabaseCleanup(void);
void* WKIconDatabaseGetTypeID(void);
void* WKIconDatabaseReleaseIconForURL(void);
void* WKIconDatabaseRemoveAllIcons(void);
void* WKIconDatabaseRetainIconForURL(void);
void* WKIconDatabaseSetIconDataForIconURL(void);
void* WKIconDatabaseSetIconDatabaseClient(void);
void* WKIconDatabaseSetIconURLForPageURL(void);
void* WKIconDatabaseTryCopyCGImageArrayForURL(void);
void* WKIconDatabaseTryGetCGImageForURL(void);
void* WKImageCreate(void);
void* WKImageCreateCGImage(void);
void* WKImageCreateFromCGImage(void);
void* WKImageGetSize(void);
void* WKImageGetTypeID(void);
void* WKInspectorAttach(void);
void* WKInspectorClose(void);
void* WKInspectorConnect(void);
void* WKInspectorDetach(void);
void* WKInspectorGetPage(void);
void* WKInspectorGetTypeID(void);
void* WKInspectorHide(void);
void* WKInspectorIsAttached(void);
void* WKInspectorIsConnected(void);
void* WKInspectorIsElementSelectionActive(void);
void* WKInspectorIsFront(void);
void* WKInspectorIsProfilingPage(void);
void* WKInspectorIsVisible(void);
void* WKInspectorShow(void);
void* WKInspectorShowConsole(void);
void* WKInspectorShowMainResourceForFrame(void);
void* WKInspectorShowResources(void);
void* WKInspectorToggleElementSelection(void);
void* WKInspectorTogglePageProfiling(void);
void* WKKeyValueStorageManagerDeleteAllEntries(void);
void* WKKeyValueStorageManagerDeleteEntriesForOrigin(void);
void* WKKeyValueStorageManagerGetCreationTimeKey(void);
void* WKKeyValueStorageManagerGetKeyValueStorageOrigins(void);
void* WKKeyValueStorageManagerGetModificationTimeKey(void);
void* WKKeyValueStorageManagerGetOriginKey(void);
void* WKKeyValueStorageManagerGetStorageDetailsByOrigin(void);
void* WKKeyValueStorageManagerGetTypeID(void);
void* WKMediaSessionFocusManagerGetTypeID(void);
void* WKMediaSessionFocusManagerSetClient(void);
void* WKMediaSessionFocusManagerSetVolumeOfFocusedMediaElement(void);
void* WKMediaSessionFocusManagerValueForPlaybackAttribute(void);
void* WKMediaSessionMetadataCopyAlbum(void);
void* WKMediaSessionMetadataCopyArtist(void);
void* WKMediaSessionMetadataCopyArtworkURL(void);
void* WKMediaSessionMetadataCopyTitle(void);
void* WKMediaSessionMetadataGetTypeID(void);
void* WKMutableArrayCreate(void);
void* WKMutableDictionaryCreate(void);
void* WKNavigationActionGetTypeID(void);
void* WKNavigationDataCopyNavigationDestinationURL(void);
void* WKNavigationDataCopyOriginalRequest(void);
void* WKNavigationDataCopyTitle(void);
void* WKNavigationDataCopyURL(void);
void* WKNavigationDataGetTypeID(void);
void* WKNavigationGetTypeID(void);
void* WKNavigationResponseCanShowMIMEType(void);
void* WKNavigationResponseGetTypeID(void);
void* WKNotificationCopyBody(void);
void* WKNotificationCopyDir(void);
void* WKNotificationCopyIconURL(void);
void* WKNotificationCopyLang(void);
void* WKNotificationCopyTag(void);
void* WKNotificationCopyTitle(void);
void* WKNotificationGetID(void);
void* WKNotificationGetSecurityOrigin(void);
void* WKNotificationGetTypeID(void);
void* WKNotificationManagerGetLocalIDForTesting(void);
void* WKNotificationManagerGetTypeID(void);
void* WKNotificationManagerProviderDidClickNotification(void);
void* WKNotificationManagerProviderDidCloseNotifications(void);
void* WKNotificationManagerProviderDidRemoveNotificationPolicies(void);
void* WKNotificationManagerProviderDidShowNotification(void);
void* WKNotificationManagerProviderDidUpdateNotificationPolicy(void);
void* WKNotificationManagerSetProvider(void);
void* WKNotificationPermissionRequestAllow(void);
void* WKNotificationPermissionRequestDeny(void);
void* WKNotificationPermissionRequestGetTypeID(void);
void* WKObjCTypeWrapperCreate(void);
void* WKObjCTypeWrapperGetObject(void);
void* WKObjCTypeWrapperGetTypeID(void);
void* WKOpenPanelParametersCopyAcceptedFileExtensions(void);
void* WKOpenPanelParametersCopyAcceptedMIMETypes(void);
void* WKOpenPanelParametersCopyCapture(void);
void* WKOpenPanelParametersCopySelectedFileNames(void);
void* WKOpenPanelParametersGetAllowsDirectories(void);
void* WKOpenPanelParametersGetAllowsMultipleFiles(void);
void* WKOpenPanelParametersGetMediaCaptureType(void);
void* WKOpenPanelParametersGetTypeID(void);
void* WKOpenPanelResultListenerCancel(void);
void* WKOpenPanelResultListenerChooseFiles(void);
void* WKOpenPanelResultListenerGetTypeID(void);
void* WKPageAreScrollbarAnimationsSuppressed(void);
void* WKPageBackgroundExtendsBeyondPage(void);
void* WKPageBeginPrinting(void);
void* WKPageCallAfterNextPresentationUpdate(void);
void* WKPageCanDelete(void);
void* WKPageCanGoBack(void);
void* WKPageCanGoForward(void);
void* WKPageCenterSelectionInVisibleArea(void);
void* WKPageClearUserMediaState(void);
void* WKPageClearWheelEventTestTrigger(void);
void* WKPageClose(void);
void* WKPageComputePagesForPrinting(void);
void* WKPageConfigurationCreate(void);
void* WKPageConfigurationGetContext(void);
void* WKPageConfigurationGetPageGroup(void);
void* WKPageConfigurationGetPreferences(void);
void* WKPageConfigurationGetRelatedPage(void);
void* WKPageConfigurationGetTypeID(void);
void* WKPageConfigurationGetUserContentController(void);
void* WKPageConfigurationGetWebsiteDataStore(void);
void* WKPageConfigurationSetBackgroundCPULimit(void);
void* WKPageConfigurationSetContext(void);
void* WKPageConfigurationSetInitialCapitalizationEnabled(void);
void* WKPageConfigurationSetPageGroup(void);
void* WKPageConfigurationSetPreferences(void);
void* WKPageConfigurationSetRelatedPage(void);
void* WKPageConfigurationSetUserContentController(void);
void* WKPageConfigurationSetWebsiteDataStore(void);
void* WKPageCopyActiveURL(void);
void* WKPageCopyApplicationNameForUserAgent(void);
void* WKPageCopyCommittedURL(void);
void* WKPageCopyCustomTextEncodingName(void);
void* WKPageCopyCustomUserAgent(void);
void* WKPageCopyPageConfiguration(void);
void* WKPageCopyPendingAPIRequestURL(void);
void* WKPageCopyProvisionalURL(void);
void* WKPageCopyRelatedPages(void);
void* WKPageCopySessionState(void);
void* WKPageCopyStandardUserAgentWithApplicationName(void);
void* WKPageCopyTitle(void);
void* WKPageCopyUserAgent(void);
void* WKPageCountStringMatches(void);
void* WKPageCreateObservableState(void);
void* WKPageDidAllowPointerLock(void);
void* WKPageDidDenyPointerLock(void);
void* WKPageDrawPagesToPDF(void);
void* WKPageEndPrinting(void);
void* WKPageExecuteCommand(void);
void* WKPageFindString(void);
void* WKPageFindStringMatches(void);
void* WKPageFixedLayoutSize(void);
void* WKPageForceRepaint(void);
void* WKPageGetAddsVisitedLinks(void);
void* WKPageGetAllowsRemoteInspection(void);
void* WKPageGetApplicationManifest_b(void);
void* WKPageGetBackForwardList(void);
void* WKPageGetBackingScaleFactor(void);
void* WKPageGetBytecodeProfile(void);
void* WKPageGetContentsAsMHTMLData(void);
void* WKPageGetContentsAsString(void);
void* WKPageGetContext(void);
void* WKPageGetEstimatedProgress(void);
void* WKPageGetFocusedFrame(void);
void* WKPageGetFrameSetLargestFrame(void);
void* WKPageGetFullscreenDelegate(void);
void* WKPageGetGapBetweenPages(void);
void* WKPageGetImageForFindMatch(void);
void* WKPageGetInspector(void);
void* WKPageGetIsControlledByAutomation(void);
void* WKPageGetMainFrame(void);
void* WKPageGetMediaCaptureEnabled(void);
void* WKPageGetMediaState(void);
void* WKPageGetObjectRegistry(void);
void* WKPageGetPageCount(void);
void* WKPageGetPageGroup(void);
void* WKPageGetPageLength(void);
void* WKPageGetPageZoomFactor(void);
void* WKPageGetPaginationBehavesLikeColumns(void);
void* WKPageGetPaginationLineGridEnabled(void);
void* WKPageGetPaginationMode(void);
void* WKPageGetProcessIdentifier(void);
void* WKPageGetRenderTreeSize(void);
void* WKPageGetResourceCachingDisabled(void);
void* WKPageGetSamplingProfilerOutput(void);
void* WKPageGetScaleFactor(void);
void* WKPageGetScrollPinningBehavior(void);
void* WKPageGetSelectionAsWebArchiveData(void);
void* WKPageGetSessionBackForwardListItemValueType(void);
void* WKPageGetSessionHistoryURLValueType(void);
void* WKPageGetSourceForFrame(void);
void* WKPageGetTextZoomFactor(void);
void* WKPageGetTypeID(void);
void* WKPageGoBack(void);
void* WKPageGoForward(void);
void* WKPageGoToBackForwardListItem(void);
void* WKPageGroupAddUserScript(void);
void* WKPageGroupAddUserStyleSheet(void);
void* WKPageGroupCreateWithIdentifier(void);
void* WKPageGroupGetPreferences(void);
void* WKPageGroupGetTypeID(void);
void* WKPageGroupGetUserContentController(void);
void* WKPageGroupRemoveAllUserScripts(void);
void* WKPageGroupRemoveAllUserStyleSheets(void);
void* WKPageGroupSetPreferences(void);
void* WKPageHandleMediaEvent(void);
void* WKPageHasHorizontalScrollbar(void);
void* WKPageHasMediaSessionWithActiveMediaElements(void);
void* WKPageHasSelectedRange(void);
void* WKPageHasVerticalScrollbar(void);
void* WKPageHideFindUI(void);
void* WKPageHorizontalRubberBandingIsEnabled(void);
void* WKPageIsClosed(void);
void* WKPageIsContentEditable(void);
void* WKPageIsPinnedToBottomSide(void);
void* WKPageIsPinnedToLeftSide(void);
void* WKPageIsPinnedToRightSide(void);
void* WKPageIsPinnedToTopSide(void);
void* WKPageIsPlayingAudio(void);
void* WKPageIsPlayingVideoInEnhancedFullscreen(void);
void* WKPageIsURLKnownHSTSHost(void);
void* WKPageIsWebProcessResponsive(void);
void* WKPageListenForLayoutMilestones(void);
void* WKPageLoadAlternateHTMLString(void);
void* WKPageLoadAlternateHTMLStringWithUserData(void);
void* WKPageLoadData(void);
void* WKPageLoadDataWithUserData(void);
void* WKPageLoadFile(void);
void* WKPageLoadFileWithUserData(void);
void* WKPageLoadHTMLString(void);
void* WKPageLoadHTMLStringWithUserData(void);
void* WKPageLoadPlainTextString(void);
void* WKPageLoadPlainTextStringWithUserData(void);
void* WKPageLoadURL(void);
void* WKPageLoadURLRequest(void);
void* WKPageLoadURLRequestWithUserData(void);
void* WKPageLoadURLWithShouldOpenExternalURLsPolicy(void);
void* WKPageLoadURLWithUserData(void);
void* WKPageLoadWebArchiveData(void);
void* WKPageLoadWebArchiveDataWithUserData(void);
void* WKPageLookUpFrameFromHandle(void);
void* WKPagePostMessageToInjectedBundle(void);
void* WKPageReload(void);
void* WKPageReloadExpiredOnly(void);
void* WKPageReloadFromOrigin(void);
void* WKPageReloadWithoutContentBlockers(void);
void* WKPageRenderTreeExternalRepresentation(void);
void* WKPageRestoreFromSessionState(void);
void* WKPageRestoreFromSessionStateWithoutNavigation(void);
void* WKPageRubberBandsAtBottom(void);
void* WKPageRubberBandsAtLeft(void);
void* WKPageRubberBandsAtRight(void);
void* WKPageRubberBandsAtTop(void);
void* WKPageRunBeforeUnloadConfirmPanelResultListenerCall(void);
void* WKPageRunBeforeUnloadConfirmPanelResultListenerGetTypeID(void);
void* WKPageRunJavaScriptAlertResultListenerCall(void);
void* WKPageRunJavaScriptAlertResultListenerGetTypeID(void);
void* WKPageRunJavaScriptConfirmResultListenerCall(void);
void* WKPageRunJavaScriptConfirmResultListenerGetTypeID(void);
void* WKPageRunJavaScriptInMainFrame(void);
void* WKPageRunJavaScriptInMainFrame_b(void);
void* WKPageRunJavaScriptPromptResultListenerCall(void);
void* WKPageRunJavaScriptPromptResultListenerGetTypeID(void);
void* WKPageSelectContextMenuItem(void);
void* WKPageSelectFindMatch(void);
void* WKPageSetAddsVisitedLinks(void);
void* WKPageSetAllowsRemoteInspection(void);
void* WKPageSetApplicationNameForUserAgent(void);
void* WKPageSetBackgroundExtendsBeyondPage(void);
void* WKPageSetControlledByAutomation(void);
void* WKPageSetCustomBackingScaleFactor(void);
void* WKPageSetCustomTextEncodingName(void);
void* WKPageSetCustomUserAgent(void);
void* WKPageSetEnableHorizontalRubberBanding(void);
void* WKPageSetEnableVerticalRubberBanding(void);
void* WKPageSetFixedLayoutSize(void);
void* WKPageSetFullscreenDelegate(void);
void* WKPageSetGapBetweenPages(void);
void* WKPageSetIgnoresViewportScaleLimits(void);
void* WKPageSetMaintainsInactiveSelection(void);
void* WKPageSetMayStartMediaWhenInWindow(void);
void* WKPageSetMediaCaptureEnabled(void);
void* WKPageSetMediaVolume(void);
void* WKPageSetMuted(void);
void* WKPageSetPageAndTextZoomFactors(void);
void* WKPageSetPageContextMenuClient(void);
void* WKPageSetPageDiagnosticLoggingClient(void);
void* WKPageSetPageFindClient(void);
void* WKPageSetPageFindMatchesClient(void);
void* WKPageSetPageFormClient(void);
void* WKPageSetPageInjectedBundleClient(void);
void* WKPageSetPageLength(void);
void* WKPageSetPageLoaderClient(void);
void* WKPageSetPageNavigationClient(void);
void* WKPageSetPagePolicyClient(void);
void* WKPageSetPageUIClient(void);
void* WKPageSetPageZoomFactor(void);
void* WKPageSetPaginationBehavesLikeColumns(void);
void* WKPageSetPaginationLineGridEnabled(void);
void* WKPageSetPaginationMode(void);
void* WKPageSetResourceCachingDisabled(void);
void* WKPageSetRubberBandsAtBottom(void);
void* WKPageSetRubberBandsAtLeft(void);
void* WKPageSetRubberBandsAtRight(void);
void* WKPageSetRubberBandsAtTop(void);
void* WKPageSetScaleFactor(void);
void* WKPageSetScrollPinningBehavior(void);
void* WKPageSetSuppressScrollbarAnimations(void);
void* WKPageSetTextZoomFactor(void);
void* WKPageSetUseFixedLayout(void);
void* WKPageSetUserContentExtensionsEnabled(void);
void* WKPageStopLoading(void);
void* WKPageSupportsTextEncoding(void);
void* WKPageSupportsTextZoom(void);
void* WKPageTerminate(void);
void* WKPageTryClose(void);
void* WKPageTryRestoreScrollPosition(void);
void* WKPageUpdateWebsitePolicies(void);
void* WKPageUseFixedLayout(void);
void* WKPageValidateCommand(void);
void* WKPageVerticalRubberBandingIsEnabled(void);
void* WKPageWillHandleHorizontalScrollEvents(void);
void* WKPlugInInfoBundleIdentifierKey(void);
void* WKPlugInInfoIsSandboxedKey(void);
void* WKPlugInInfoLoadPolicyKey(void);
void* WKPlugInInfoPathKey(void);
void* WKPlugInInfoUpdatePastLastBlockedVersionIsKnownAvailableKey(void);
void* WKPlugInInfoVersionKey(void);
void* WKPlugInInformationReplacementObscuredKey(void);
void* WKPluginInformationBundleIdentifierKey(void);
void* WKPluginInformationBundleShortVersionKey(void);
void* WKPluginInformationBundleVersionKey(void);
void* WKPluginInformationDefaultLoadPolicyKey(void);
void* WKPluginInformationDisplayNameKey(void);
void* WKPluginInformationFrameURLKey(void);
void* WKPluginInformationHasSandboxProfileKey(void);
void* WKPluginInformationMIMETypeKey(void);
void* WKPluginInformationPageURLKey(void);
void* WKPluginInformationPathKey(void);
void* WKPluginInformationPluginURLKey(void);
void* WKPluginInformationPluginspageAttributeURLKey(void);
void* WKPluginInformationUpdatePastLastBlockedVersionIsKnownAvailableKey(void);
void* WKPointCreate(void);
void* WKPointGetTypeID(void);
void* WKPointGetValue(void);
void* WKPreferencesCopyCursiveFontFamily(void);
void* WKPreferencesCopyDefaultTextEncodingName(void);
void* WKPreferencesCopyFTPDirectoryTemplatePath(void);
void* WKPreferencesCopyFantasyFontFamily(void);
void* WKPreferencesCopyFixedFontFamily(void);
void* WKPreferencesCopyMediaContentTypesRequiringHardwareSupport(void);
void* WKPreferencesCopyPictographFontFamily(void);
void* WKPreferencesCopySansSerifFontFamily(void);
void* WKPreferencesCopySerifFontFamily(void);
void* WKPreferencesCopyStandardFontFamily(void);
void* WKPreferencesCreate(void);
void* WKPreferencesCreateCopy(void);
void* WKPreferencesCreateWithIdentifier(void);
void* WKPreferencesEnableAllExperimentalFeatures(void);
void* WKPreferencesGetAVFoundationEnabled(void);
void* WKPreferencesGetAVFoundationNSURLSessionEnabled(void);
void* WKPreferencesGetAccelerated2DCanvasEnabled(void);
void* WKPreferencesGetAcceleratedCompositingEnabled(void);
void* WKPreferencesGetAcceleratedCompositingForOverflowScrollEnabled(void);
void* WKPreferencesGetAcceleratedDrawingEnabled(void);
void* WKPreferencesGetAccessibilityObjectModelEnabled(void);
void* WKPreferencesGetAggressiveTileRetentionEnabled(void);
void* WKPreferencesGetAllowMediaContentTypesRequiringHardwareSupportAsFallback(void);
void* WKPreferencesGetAllowsAirPlayForMediaPlayback(void);
void* WKPreferencesGetAllowsPictureInPictureMediaPlayback(void);
void* WKPreferencesGetAnimatedImageAsyncDecodingEnabled(void);
void* WKPreferencesGetAntialiasedFontDilationEnabled(void);
void* WKPreferencesGetApplePayCapabilityDisclosureAllowed(void);
void* WKPreferencesGetApplePayEnabled(void);
void* WKPreferencesGetApplicationChromeModeEnabled(void);
void* WKPreferencesGetArtificialPluginInitializationDelayEnabled(void);
void* WKPreferencesGetAsynchronousPluginInitializationEnabled(void);
void* WKPreferencesGetAsynchronousPluginInitializationEnabledForAllPlugins(void);
void* WKPreferencesGetAsynchronousSpellCheckingEnabled(void);
void* WKPreferencesGetAttachmentElementEnabled(void);
void* WKPreferencesGetAudioPlaybackRequiresUserGesture(void);
void* WKPreferencesGetAuthorAndUserStylesEnabled(void);
void* WKPreferencesGetAutostartOriginPlugInSnapshottingEnabled(void);
void* WKPreferencesGetBackspaceKeyNavigationEnabled(void);
void* WKPreferencesGetBeaconAPIEnabled(void);
void* WKPreferencesGetCSSAnimationTriggersEnabled(void);
void* WKPreferencesGetCanvasUsesAcceleratedDrawing(void);
void* WKPreferencesGetCaretBrowsingEnabled(void);
void* WKPreferencesGetCompositingBordersVisible(void);
void* WKPreferencesGetCompositingRepaintCountersVisible(void);
void* WKPreferencesGetCookieEnabled(void);
void* WKPreferencesGetCustomPasteboardDataEnabled(void);
void* WKPreferencesGetDNSPrefetchingEnabled(void);
void* WKPreferencesGetDOMPasteAllowed(void);
void* WKPreferencesGetDOMTimersThrottlingEnabled(void);
void* WKPreferencesGetDataTransferItemsEnabled(void);
void* WKPreferencesGetDatabasesEnabled(void);
void* WKPreferencesGetDefaultFixedFontSize(void);
void* WKPreferencesGetDefaultFontSize(void);
void* WKPreferencesGetDeferredCSSParserEnabled(void);
void* WKPreferencesGetDeveloperExtrasEnabled(void);
void* WKPreferencesGetDiagnosticLoggingEnabled(void);
void* WKPreferencesGetDirectoryUploadEnabled(void);
void* WKPreferencesGetDisplayContentsEnabled(void);
void* WKPreferencesGetDownloadAttributeEnabled(void);
void* WKPreferencesGetEditableLinkBehavior(void);
void* WKPreferencesGetEnableInheritURIQueryComponent(void);
void* WKPreferencesGetEncodingDetectorEnabled(void);
void* WKPreferencesGetEnumeratingAllNetworkInterfacesEnabled(void);
void* WKPreferencesGetFetchAPIEnabled(void);
void* WKPreferencesGetFetchAPIKeepAliveEnabled(void);
void* WKPreferencesGetFileAccessFromFileURLsAllowed(void);
void* WKPreferencesGetFontSmoothingLevel(void);
void* WKPreferencesGetForceFTPDirectoryListings(void);
void* WKPreferencesGetForceSoftwareWebGLRendering(void);
void* WKPreferencesGetFrameFlatteningEnabled(void);
void* WKPreferencesGetFullScreenEnabled(void);
void* WKPreferencesGetGamepadsEnabled(void);
void* WKPreferencesGetHTTPEquivEnabled(void);
void* WKPreferencesGetHiddenPageCSSAnimationSuspensionEnabled(void);
void* WKPreferencesGetHiddenPageDOMTimerThrottlingAutoIncreases(void);
void* WKPreferencesGetHiddenPageDOMTimerThrottlingEnabled(void);
void* WKPreferencesGetHixie76WebSocketProtocolEnabled(void);
void* WKPreferencesGetHyperlinkAuditingEnabled(void);
void* WKPreferencesGetICECandidateFilteringEnabled(void);
void* WKPreferencesGetIgnoreViewportScalingConstraints(void);
void* WKPreferencesGetImageControlsEnabled(void);
void* WKPreferencesGetInactiveMediaCaptureSteamRepromptIntervalInMinutes(void);
void* WKPreferencesGetIncrementalRenderingSuppressionTimeout(void);
void* WKPreferencesGetInlineMediaPlaybackRequiresPlaysInlineAttribute(void);
void* WKPreferencesGetInspectorAdditionsEnabled(void);
void* WKPreferencesGetInspectorUsesWebKitUserInterface(void);
void* WKPreferencesGetInteractiveFormValidationEnabled(void);
void* WKPreferencesGetIntersectionObserverEnabled(void);
void* WKPreferencesGetInvisibleMediaAutoplayPermitted(void);
void* WKPreferencesGetIsSecureContextAttributeEnabled(void);
void* WKPreferencesGetJavaEnabled(void);
void* WKPreferencesGetJavaEnabledForLocalFiles(void);
void* WKPreferencesGetJavaScriptCanAccessClipboard(void);
void* WKPreferencesGetJavaScriptCanOpenWindowsAutomatically(void);
void* WKPreferencesGetJavaScriptEnabled(void);
void* WKPreferencesGetJavaScriptMarkupEnabled(void);
void* WKPreferencesGetJavaScriptRuntimeFlags(void);
void* WKPreferencesGetLargeImageAsyncDecodingEnabled(void);
void* WKPreferencesGetLegacyEncryptedMediaAPIEnabled(void);
void* WKPreferencesGetLinkPreloadEnabled(void);
void* WKPreferencesGetLoadsImagesAutomatically(void);
void* WKPreferencesGetLoadsSiteIconsIgnoringImageLoadingPreference(void);
void* WKPreferencesGetLocalFileContentSniffingEnabled(void);
void* WKPreferencesGetLocalStorageEnabled(void);
void* WKPreferencesGetLogsPageMessagesToSystemConsoleEnabled(void);
void* WKPreferencesGetLongMousePressEnabled(void);
void* WKPreferencesGetMainContentUserGestureOverrideEnabled(void);
void* WKPreferencesGetMediaCapabilitiesEnabled(void);
void* WKPreferencesGetMediaCaptureRequiresSecureConnection(void);
void* WKPreferencesGetMediaControlsScaleWithPageZoom(void);
void* WKPreferencesGetMediaDevicesEnabled(void);
void* WKPreferencesGetMediaPlaybackAllowsInline(void);
void* WKPreferencesGetMediaPlaybackRequiresUserGesture(void);
void* WKPreferencesGetMediaPreloadingEnabled(void);
void* WKPreferencesGetMediaSourceEnabled(void);
void* WKPreferencesGetMediaStreamEnabled(void);
void* WKPreferencesGetMediaUserGestureInheritsFromDocument(void);
void* WKPreferencesGetMenuItemElementEnabled(void);
void* WKPreferencesGetMetaRefreshEnabled(void);
void* WKPreferencesGetMinimumFontSize(void);
void* WKPreferencesGetMinimumZoomFontSize(void);
void* WKPreferencesGetMockCaptureDevicesEnabled(void);
void* WKPreferencesGetMockScrollbarsEnabled(void);
void* WKPreferencesGetModernMediaControlsEnabled(void);
void* WKPreferencesGetNeedsSiteSpecificQuirks(void);
void* WKPreferencesGetNeedsStorageAccessFromFileURLsQuirk(void);
void* WKPreferencesGetNewBlockInsideInlineModelEnabled(void);
void* WKPreferencesGetNotificationsEnabled(void);
void* WKPreferencesGetOfflineWebApplicationCacheEnabled(void);
void* WKPreferencesGetPDFPluginEnabled(void);
void* WKPreferencesGetPageCacheEnabled(void);
void* WKPreferencesGetPageCacheSupportsPlugins(void);
void* WKPreferencesGetPageVisibilityBasedProcessSuppressionEnabled(void);
void* WKPreferencesGetPaginateDuringLayoutEnabled(void);
void* WKPreferencesGetPeerConnectionEnabled(void);
void* WKPreferencesGetPlugInSnapshottingEnabled(void);
void* WKPreferencesGetPluginsEnabled(void);
void* WKPreferencesGetPrimaryPlugInSnapshotDetectionEnabled(void);
void* WKPreferencesGetPrivateBrowsingEnabled(void);
void* WKPreferencesGetQTKitEnabled(void);
void* WKPreferencesGetRequestAnimationFrameEnabled(void);
void* WKPreferencesGetResourceTimingEnabled(void);
void* WKPreferencesGetResourceUsageOverlayVisible(void);
void* WKPreferencesGetScrollingPerformanceLoggingEnabled(void);
void* WKPreferencesGetSelectTrailingWhitespaceEnabled(void);
void* WKPreferencesGetSelectionPaintingWithoutSelectionGapsEnabled(void);
void* WKPreferencesGetServiceControlsEnabled(void);
void* WKPreferencesGetShouldAllowUserInstalledFonts(void);
void* WKPreferencesGetShouldConvertPositionStyleOnCopy(void);
void* WKPreferencesGetShouldDisplayCaptions(void);
void* WKPreferencesGetShouldDisplaySubtitles(void);
void* WKPreferencesGetShouldDisplayTextDescriptions(void);
void* WKPreferencesGetShouldPrintBackgrounds(void);
void* WKPreferencesGetShouldRespectImageOrientation(void);
void* WKPreferencesGetShouldSuppressKeyboardInputDuringProvisionalNavigation(void);
void* WKPreferencesGetShowsToolTipOverTruncatedText(void);
void* WKPreferencesGetShowsURLsInToolTipsEnabled(void);
void* WKPreferencesGetSimpleLineLayoutDebugBordersEnabled(void);
void* WKPreferencesGetSimpleLineLayoutEnabled(void);
void* WKPreferencesGetSmartInsertDeleteEnabled(void);
void* WKPreferencesGetSnapshotAllPlugIns(void);
void* WKPreferencesGetSpatialNavigationEnabled(void);
void* WKPreferencesGetStorageAccessAPIEnabled(void);
void* WKPreferencesGetStorageBlockingPolicy(void);
void* WKPreferencesGetSubpixelAntialiasedLayerTextEnabled(void);
void* WKPreferencesGetSubpixelCSSOMElementMetricsEnabled(void);
void* WKPreferencesGetSuppressesIncrementalRendering(void);
void* WKPreferencesGetTabToLinksEnabled(void);
void* WKPreferencesGetTabsToLinks(void);
void* WKPreferencesGetTelephoneNumberParsingEnabled(void);
void* WKPreferencesGetTextAreasAreResizable(void);
void* WKPreferencesGetTextAutosizingEnabled(void);
void* WKPreferencesGetThreadedScrollingEnabled(void);
void* WKPreferencesGetTiledScrollingIndicatorVisible(void);
void* WKPreferencesGetTypeID(void);
void* WKPreferencesGetUniversalAccessFromFileURLsAllowed(void);
void* WKPreferencesGetUseGiantTiles(void);
void* WKPreferencesGetUserInterfaceDirectionPolicy(void);
void* WKPreferencesGetUserTimingEnabled(void);
void* WKPreferencesGetVideoPlaybackRequiresUserGesture(void);
void* WKPreferencesGetViewGestureDebuggingEnabled(void);
void* WKPreferencesGetVisibleDebugOverlayRegions(void);
void* WKPreferencesGetWebAnimationsEnabled(void);
void* WKPreferencesGetWebArchiveDebugModeEnabled(void);
void* WKPreferencesGetWebAudioEnabled(void);
void* WKPreferencesGetWebAuthenticationEnabled(void);
void* WKPreferencesGetWebGLEnabled(void);
void* WKPreferencesGetWebRTCLegacyAPIEnabled(void);
void* WKPreferencesGetWebSecurityEnabled(void);
void* WKPreferencesGetXSSAuditorEnabled(void);
void* WKPreferencesResetTestRunnerOverrides(void);
void* WKPreferencesSetAVFoundationEnabled(void);
void* WKPreferencesSetAVFoundationNSURLSessionEnabled(void);
void* WKPreferencesSetAccelerated2DCanvasEnabled(void);
void* WKPreferencesSetAcceleratedCompositingEnabled(void);
void* WKPreferencesSetAcceleratedCompositingForOverflowScrollEnabled(void);
void* WKPreferencesSetAcceleratedDrawingEnabled(void);
void* WKPreferencesSetAccessibilityObjectModelEnabled(void);
void* WKPreferencesSetAggressiveTileRetentionEnabled(void);
void* WKPreferencesSetAllowMediaContentTypesRequiringHardwareSupportAsFallback(void);
void* WKPreferencesSetAllowsAirPlayForMediaPlayback(void);
void* WKPreferencesSetAllowsPictureInPictureMediaPlayback(void);
void* WKPreferencesSetAnimatedImageAsyncDecodingEnabled(void);
void* WKPreferencesSetAntialiasedFontDilationEnabled(void);
void* WKPreferencesSetApplePayCapabilityDisclosureAllowed(void);
void* WKPreferencesSetApplePayEnabled(void);
void* WKPreferencesSetApplicationChromeModeEnabled(void);
void* WKPreferencesSetArtificialPluginInitializationDelayEnabled(void);
void* WKPreferencesSetAsynchronousPluginInitializationEnabled(void);
void* WKPreferencesSetAsynchronousPluginInitializationEnabledForAllPlugins(void);
void* WKPreferencesSetAsynchronousSpellCheckingEnabled(void);
void* WKPreferencesSetAttachmentElementEnabled(void);
void* WKPreferencesSetAudioPlaybackRequiresUserGesture(void);
void* WKPreferencesSetAuthorAndUserStylesEnabled(void);
void* WKPreferencesSetAutostartOriginPlugInSnapshottingEnabled(void);
void* WKPreferencesSetBackspaceKeyNavigationEnabled(void);
void* WKPreferencesSetBeaconAPIEnabled(void);
void* WKPreferencesSetCSSAnimationTriggersEnabled(void);
void* WKPreferencesSetCanvasUsesAcceleratedDrawing(void);
void* WKPreferencesSetCaretBrowsingEnabled(void);
void* WKPreferencesSetCompositingBordersVisible(void);
void* WKPreferencesSetCompositingRepaintCountersVisible(void);
void* WKPreferencesSetCookieEnabled(void);
void* WKPreferencesSetCursiveFontFamily(void);
void* WKPreferencesSetCustomPasteboardDataEnabled(void);
void* WKPreferencesSetDNSPrefetchingEnabled(void);
void* WKPreferencesSetDOMPasteAllowed(void);
void* WKPreferencesSetDOMTimersThrottlingEnabled(void);
void* WKPreferencesSetDataTransferItemsEnabled(void);
void* WKPreferencesSetDatabasesEnabled(void);
void* WKPreferencesSetDefaultFixedFontSize(void);
void* WKPreferencesSetDefaultFontSize(void);
void* WKPreferencesSetDefaultTextEncodingName(void);
void* WKPreferencesSetDeferredCSSParserEnabled(void);
void* WKPreferencesSetDeveloperExtrasEnabled(void);
void* WKPreferencesSetDiagnosticLoggingEnabled(void);
void* WKPreferencesSetDirectoryUploadEnabled(void);
void* WKPreferencesSetDisplayContentsEnabled(void);
void* WKPreferencesSetDownloadAttributeEnabled(void);
void* WKPreferencesSetEditableLinkBehavior(void);
void* WKPreferencesSetEnableInheritURIQueryComponent(void);
void* WKPreferencesSetEncodingDetectorEnabled(void);
void* WKPreferencesSetEnumeratingAllNetworkInterfacesEnabled(void);
void* WKPreferencesSetFTPDirectoryTemplatePath(void);
void* WKPreferencesSetFantasyFontFamily(void);
void* WKPreferencesSetFetchAPIEnabled(void);
void* WKPreferencesSetFetchAPIKeepAliveEnabled(void);
void* WKPreferencesSetFileAccessFromFileURLsAllowed(void);
void* WKPreferencesSetFixedFontFamily(void);
void* WKPreferencesSetFontSmoothingLevel(void);
void* WKPreferencesSetForceFTPDirectoryListings(void);
void* WKPreferencesSetForceSoftwareWebGLRendering(void);
void* WKPreferencesSetFrameFlatteningEnabled(void);
void* WKPreferencesSetFullScreenEnabled(void);
void* WKPreferencesSetGamepadsEnabled(void);
void* WKPreferencesSetHTTPEquivEnabled(void);
void* WKPreferencesSetHiddenPageCSSAnimationSuspensionEnabled(void);
void* WKPreferencesSetHiddenPageDOMTimerThrottlingAutoIncreases(void);
void* WKPreferencesSetHiddenPageDOMTimerThrottlingEnabled(void);
void* WKPreferencesSetHixie76WebSocketProtocolEnabled(void);
void* WKPreferencesSetHyperlinkAuditingEnabled(void);
void* WKPreferencesSetICECandidateFilteringEnabled(void);
void* WKPreferencesSetIgnoreViewportScalingConstraints(void);
void* WKPreferencesSetImageControlsEnabled(void);
void* WKPreferencesSetInactiveMediaCaptureSteamRepromptIntervalInMinutes(void);
void* WKPreferencesSetIncrementalRenderingSuppressionTimeout(void);
void* WKPreferencesSetInlineMediaPlaybackRequiresPlaysInlineAttribute(void);
void* WKPreferencesSetInspectorAdditionsEnabled(void);
void* WKPreferencesSetInspectorUsesWebKitUserInterface(void);
void* WKPreferencesSetInteractiveFormValidationEnabled(void);
void* WKPreferencesSetIntersectionObserverEnabled(void);
void* WKPreferencesSetInvisibleMediaAutoplayPermitted(void);
void* WKPreferencesSetIsSecureContextAttributeEnabled(void);
void* WKPreferencesSetJavaEnabled(void);
void* WKPreferencesSetJavaEnabledForLocalFiles(void);
void* WKPreferencesSetJavaScriptCanAccessClipboard(void);
void* WKPreferencesSetJavaScriptCanOpenWindowsAutomatically(void);
void* WKPreferencesSetJavaScriptEnabled(void);
void* WKPreferencesSetJavaScriptMarkupEnabled(void);
void* WKPreferencesSetJavaScriptRuntimeFlags(void);
void* WKPreferencesSetLargeImageAsyncDecodingEnabled(void);
void* WKPreferencesSetLegacyEncryptedMediaAPIEnabled(void);
void* WKPreferencesSetLinkPreloadEnabled(void);
void* WKPreferencesSetLoadsImagesAutomatically(void);
void* WKPreferencesSetLoadsSiteIconsIgnoringImageLoadingPreference(void);
void* WKPreferencesSetLocalFileContentSniffingEnabled(void);
void* WKPreferencesSetLocalStorageEnabled(void);
void* WKPreferencesSetLogsPageMessagesToSystemConsoleEnabled(void);
void* WKPreferencesSetLongMousePressEnabled(void);
void* WKPreferencesSetMainContentUserGestureOverrideEnabled(void);
void* WKPreferencesSetMediaCapabilitiesEnabled(void);
void* WKPreferencesSetMediaCaptureRequiresSecureConnection(void);
void* WKPreferencesSetMediaContentTypesRequiringHardwareSupport(void);
void* WKPreferencesSetMediaControlsScaleWithPageZoom(void);
void* WKPreferencesSetMediaDevicesEnabled(void);
void* WKPreferencesSetMediaPlaybackAllowsInline(void);
void* WKPreferencesSetMediaPlaybackRequiresUserGesture(void);
void* WKPreferencesSetMediaPreloadingEnabled(void);
void* WKPreferencesSetMediaSourceEnabled(void);
void* WKPreferencesSetMediaStreamEnabled(void);
void* WKPreferencesSetMediaUserGestureInheritsFromDocument(void);
void* WKPreferencesSetMenuItemElementEnabled(void);
void* WKPreferencesSetMetaRefreshEnabled(void);
void* WKPreferencesSetMinimumFontSize(void);
void* WKPreferencesSetMinimumZoomFontSize(void);
void* WKPreferencesSetMockCaptureDevicesEnabled(void);
void* WKPreferencesSetMockScrollbarsEnabled(void);
void* WKPreferencesSetModernMediaControlsEnabled(void);
void* WKPreferencesSetNeedsSiteSpecificQuirks(void);
void* WKPreferencesSetNeedsStorageAccessFromFileURLsQuirk(void);
void* WKPreferencesSetNewBlockInsideInlineModelEnabled(void);
void* WKPreferencesSetNotificationsEnabled(void);
void* WKPreferencesSetOfflineWebApplicationCacheEnabled(void);
void* WKPreferencesSetPDFPluginEnabled(void);
void* WKPreferencesSetPageCacheEnabled(void);
void* WKPreferencesSetPageCacheSupportsPlugins(void);
void* WKPreferencesSetPageVisibilityBasedProcessSuppressionEnabled(void);
void* WKPreferencesSetPaginateDuringLayoutEnabled(void);
void* WKPreferencesSetPeerConnectionEnabled(void);
void* WKPreferencesSetPictographFontFamily(void);
void* WKPreferencesSetPlugInSnapshottingEnabled(void);
void* WKPreferencesSetPluginsEnabled(void);
void* WKPreferencesSetPrimaryPlugInSnapshotDetectionEnabled(void);
void* WKPreferencesSetPrivateBrowsingEnabled(void);
void* WKPreferencesSetQTKitEnabled(void);
void* WKPreferencesSetRequestAnimationFrameEnabled(void);
void* WKPreferencesSetResourceTimingEnabled(void);
void* WKPreferencesSetResourceUsageOverlayVisible(void);
void* WKPreferencesSetSansSerifFontFamily(void);
void* WKPreferencesSetScrollingPerformanceLoggingEnabled(void);
void* WKPreferencesSetSelectTrailingWhitespaceEnabled(void);
void* WKPreferencesSetSelectionPaintingWithoutSelectionGapsEnabled(void);
void* WKPreferencesSetSerifFontFamily(void);
void* WKPreferencesSetServiceControlsEnabled(void);
void* WKPreferencesSetShouldAllowUserInstalledFonts(void);
void* WKPreferencesSetShouldConvertPositionStyleOnCopy(void);
void* WKPreferencesSetShouldDisplayCaptions(void);
void* WKPreferencesSetShouldDisplaySubtitles(void);
void* WKPreferencesSetShouldDisplayTextDescriptions(void);
void* WKPreferencesSetShouldPrintBackgrounds(void);
void* WKPreferencesSetShouldRespectImageOrientation(void);
void* WKPreferencesSetShouldSuppressKeyboardInputDuringProvisionalNavigation(void);
void* WKPreferencesSetShowsToolTipOverTruncatedText(void);
void* WKPreferencesSetShowsURLsInToolTipsEnabled(void);
void* WKPreferencesSetSimpleLineLayoutDebugBordersEnabled(void);
void* WKPreferencesSetSimpleLineLayoutEnabled(void);
void* WKPreferencesSetSmartInsertDeleteEnabled(void);
void* WKPreferencesSetSnapshotAllPlugIns(void);
void* WKPreferencesSetSpatialNavigationEnabled(void);
void* WKPreferencesSetStandardFontFamily(void);
void* WKPreferencesSetStorageAccessAPIEnabled(void);
void* WKPreferencesSetStorageBlockingPolicy(void);
void* WKPreferencesSetSubpixelAntialiasedLayerTextEnabled(void);
void* WKPreferencesSetSubpixelCSSOMElementMetricsEnabled(void);
void* WKPreferencesSetSuppressesIncrementalRendering(void);
void* WKPreferencesSetTabToLinksEnabled(void);
void* WKPreferencesSetTabsToLinks(void);
void* WKPreferencesSetTelephoneNumberParsingEnabled(void);
void* WKPreferencesSetTextAreasAreResizable(void);
void* WKPreferencesSetTextAutosizingEnabled(void);
void* WKPreferencesSetThreadedScrollingEnabled(void);
void* WKPreferencesSetTiledScrollingIndicatorVisible(void);
void* WKPreferencesSetUniversalAccessFromFileURLsAllowed(void);
void* WKPreferencesSetUseGiantTiles(void);
void* WKPreferencesSetUseLegacyTextAlignPositionedElementBehavior(void);
void* WKPreferencesSetUserInterfaceDirectionPolicy(void);
void* WKPreferencesSetUserTimingEnabled(void);
void* WKPreferencesSetVideoPlaybackRequiresUserGesture(void);
void* WKPreferencesSetViewGestureDebuggingEnabled(void);
void* WKPreferencesSetVisibleDebugOverlayRegions(void);
void* WKPreferencesSetWebAnimationsEnabled(void);
void* WKPreferencesSetWebArchiveDebugModeEnabled(void);
void* WKPreferencesSetWebAudioEnabled(void);
void* WKPreferencesSetWebAuthenticationEnabled(void);
void* WKPreferencesSetWebGLEnabled(void);
void* WKPreferencesSetWebRTCLegacyAPIEnabled(void);
void* WKPreferencesSetWebSecurityEnabled(void);
void* WKPreferencesSetXSSAuditorEnabled(void);
void* WKPreferencesUseLegacyTextAlignPositionedElementBehavior(void);
void* WKProtectionSpaceCopyHost(void);
void* WKProtectionSpaceCopyNSURLProtectionSpace(void);
void* WKProtectionSpaceCopyRealm(void);
void* WKProtectionSpaceGetAuthenticationScheme(void);
void* WKProtectionSpaceGetIsProxy(void);
void* WKProtectionSpaceGetPort(void);
void* WKProtectionSpaceGetReceivesCredentialSecurely(void);
void* WKProtectionSpaceGetServerType(void);
void* WKProtectionSpaceGetTypeID(void);
void* WKRectCreate(void);
void* WKRectGetTypeID(void);
void* WKRectGetValue(void);
void* WKRelease(void);
void* WKRenderLayerCopyElementID(void);
void* WKRenderLayerCopyElementTagName(void);
void* WKRenderLayerCopyRendererName(void);
void* WKRenderLayerGetAbsoluteBounds(void);
void* WKRenderLayerGetBackingStoreMemoryEstimate(void);
void* WKRenderLayerGetCompositingLayerType(void);
void* WKRenderLayerGetElementClassNames(void);
void* WKRenderLayerGetFrameContentsLayer(void);
void* WKRenderLayerGetNegativeZOrderList(void);
void* WKRenderLayerGetNormalFlowList(void);
void* WKRenderLayerGetPositiveZOrderList(void);
void* WKRenderLayerGetRenderer(void);
void* WKRenderLayerGetTypeID(void);
void* WKRenderLayerIsClipped(void);
void* WKRenderLayerIsClipping(void);
void* WKRenderLayerIsReflection(void);
void* WKRenderObjectCopyElementID(void);
void* WKRenderObjectCopyElementTagName(void);
void* WKRenderObjectCopyName(void);
void* WKRenderObjectCopyTextSnippet(void);
void* WKRenderObjectGetAbsolutePosition(void);
void* WKRenderObjectGetChildren(void);
void* WKRenderObjectGetElementClassNames(void);
void* WKRenderObjectGetFrameRect(void);
void* WKRenderObjectGetTextLength(void);
void* WKRenderObjectGetTypeID(void);
void* WKResourceCacheManagerClearCacheForAllOrigins(void);
void* WKResourceCacheManagerClearCacheForOrigin(void);
void* WKResourceCacheManagerGetCacheOrigins(void);
void* WKResourceCacheManagerGetTypeID(void);
void* WKRetain(void);
void* WKSecurityOriginCopyDatabaseIdentifier(void);
void* WKSecurityOriginCopyHost(void);
void* WKSecurityOriginCopyProtocol(void);
void* WKSecurityOriginCopyToString(void);
void* WKSecurityOriginCreate(void);
void* WKSecurityOriginCreateFromDatabaseIdentifier(void);
void* WKSecurityOriginCreateFromString(void);
void* WKSecurityOriginGetPort(void);
void* WKSecurityOriginGetTypeID(void);
void* WKSerializedScriptValueCreate(void);
void* WKSerializedScriptValueDeserialize(void);
void* WKSerializedScriptValueGetTypeID(void);
void* WKSessionStateCopyData(void);
void* WKSessionStateCreateFromData(void);
void* WKSessionStateGetTypeID(void);
void* WKSizeCreate(void);
void* WKSizeGetTypeID(void);
void* WKSizeGetValue(void);
void* WKStringCopyCFString(void);
void* WKStringCopyJSString(void);
void* WKStringCreateWithCFString(void);
void* WKStringCreateWithJSString(void);
void* WKStringCreateWithUTF8CString(void);
void* WKStringGetCharacters(void);
void* WKStringGetLength(void);
void* WKStringGetMaximumUTF8CStringSize(void);
void* WKStringGetTypeID(void);
void* WKStringGetUTF8CString(void);
void* WKStringGetUTF8CStringNonStrict(void);
void* WKStringIsEmpty(void);
void* WKStringIsEqual(void);
void* WKStringIsEqualToUTF8CString(void);
void* WKStringIsEqualToUTF8CStringIgnoringCase(void);
void* WKTextCheckerSetTestingMode(void);
void* WKUInt64Create(void);
void* WKUInt64GetTypeID(void);
void* WKUInt64GetValue(void);
void* WKURLCopyCFURL(void);
void* WKURLCopyHostName(void);
void* WKURLCopyLastPathComponent(void);
void* WKURLCopyPath(void);
void* WKURLCopyScheme(void);
void* WKURLCopyString(void);
void* WKURLCreateWithBaseURL(void);
void* WKURLCreateWithCFURL(void);
void* WKURLCreateWithUTF8CString(void);
void* WKURLGetTypeID(void);
void* WKURLIsEqual(void);
void* WKURLRequestCopyFirstPartyForCookies(void);
void* WKURLRequestCopyHTTPMethod(void);
void* WKURLRequestCopyNSURLRequest(void);
void* WKURLRequestCopySettingHTTPBody(void);
void* WKURLRequestCopyURL(void);
void* WKURLRequestCreateWithNSURLRequest(void);
void* WKURLRequestCreateWithWKURL(void);
void* WKURLRequestGetTypeID(void);
void* WKURLRequestSetDefaultTimeoutInterval(void);
void* WKURLResponseCopyMIMEType(void);
void* WKURLResponseCopyNSURLResponse(void);
void* WKURLResponseCopySuggestedFilename(void);
void* WKURLResponseCopyURL(void);
void* WKURLResponseCreateWithNSURLResponse(void);
void* WKURLResponseGetExpectedContentLength(void);
void* WKURLResponseGetTypeID(void);
void* WKURLResponseHTTPStatusCode(void);
void* WKURLResponseIsAttachment(void);
void* WKUserContentControllerAddUserContentFilter(void);
void* WKUserContentControllerAddUserScript(void);
void* WKUserContentControllerCopyUserScripts(void);
void* WKUserContentControllerCreate(void);
void* WKUserContentControllerGetTypeID(void);
void* WKUserContentControllerRemoveAllUserContentFilters(void);
void* WKUserContentControllerRemoveAllUserScripts(void);
void* WKUserContentExtensionStoreGetTypeID(void);
void* WKUserContentURLPatternCopyHost(void);
void* WKUserContentURLPatternCopyScheme(void);
void* WKUserContentURLPatternCreate(void);
void* WKUserContentURLPatternGetTypeID(void);
void* WKUserContentURLPatternIsValid(void);
void* WKUserContentURLPatternMatchesSubdomains(void);
void* WKUserContentURLPatternMatchesURL(void);
void* WKUserMediaPermissionCheckGetTypeID(void);
void* WKUserMediaPermissionCheckSetUserMediaAccessInfo(void);
void* WKUserMediaPermissionRequestAllow(void);
void* WKUserMediaPermissionRequestAudioDeviceUIDs(void);
void* WKUserMediaPermissionRequestDeny(void);
void* WKUserMediaPermissionRequestGetTypeID(void);
void* WKUserMediaPermissionRequestVideoDeviceUIDs(void);
void* WKUserScriptCopySource(void);
void* WKUserScriptCreateWithSource(void);
void* WKUserScriptGetInjectionTime(void);
void* WKUserScriptGetMainFrameOnly(void);
void* WKUserScriptGetTypeID(void);
void* WKWebArchiveCopyData(void);
void* WKWebArchiveCopyMainResource(void);
void* WKWebArchiveCopySubframeArchives(void);
void* WKWebArchiveCopySubresources(void);
void* WKWebArchiveCreate(void);
void* WKWebArchiveCreateFromRange(void);
void* WKWebArchiveCreateWithData(void);
void* WKWebArchiveGetTypeID(void);
void* WKWebArchiveResourceCopyData(void);
void* WKWebArchiveResourceCopyMIMEType(void);
void* WKWebArchiveResourceCopyTextEncoding(void);
void* WKWebArchiveResourceCopyURL(void);
void* WKWebArchiveResourceCreate(void);
void* WKWebArchiveResourceGetTypeID(void);
void* WKWebsiteDataStoreCreateNonPersistentDataStore(void);
void* WKWebsiteDataStoreGetDefaultDataStore(void);
void* WKWebsiteDataStoreGetFetchCacheOrigins(void);
void* WKWebsiteDataStoreGetFetchCacheSizeForOrigin(void);
void* WKWebsiteDataStoreGetResourceLoadStatisticsEnabled(void);
void* WKWebsiteDataStoreGetTypeID(void);
void* WKWebsiteDataStoreIsStatisticsGrandfathered(void);
void* WKWebsiteDataStoreIsStatisticsHasHadUserInteraction(void);
void* WKWebsiteDataStoreIsStatisticsPrevalentResource(void);
void* WKWebsiteDataStoreIsStatisticsRegisteredAsRedirectingTo(void);
void* WKWebsiteDataStoreIsStatisticsRegisteredAsSubFrameUnder(void);
void* WKWebsiteDataStoreRemoveAllFetchCaches(void);
void* WKWebsiteDataStoreRemoveAllIndexedDatabases(void);
void* WKWebsiteDataStoreRemoveAllServiceWorkerRegistrations(void);
void* WKWebsiteDataStoreRemoveFetchCacheForOrigin(void);
void* WKWebsiteDataStoreSetResourceLoadStatisticsEnabled(void);
void* WKWebsiteDataStoreSetStatisticsGrandfathered(void);
void* WKWebsiteDataStoreSetStatisticsGrandfatheringTime(void);
void* WKWebsiteDataStoreSetStatisticsHasHadNonRecentUserInteraction(void);
void* WKWebsiteDataStoreSetStatisticsHasHadUserInteraction(void);
void* WKWebsiteDataStoreSetStatisticsLastSeen(void);
void* WKWebsiteDataStoreSetStatisticsMaxStatisticsEntries(void);
void* WKWebsiteDataStoreSetStatisticsMinimumTimeBetweenDataRecordsRemoval(void);
void* WKWebsiteDataStoreSetStatisticsNotifyPagesWhenDataRecordsWereScanned(void);
void* WKWebsiteDataStoreSetStatisticsNotifyPagesWhenTelemetryWasCaptured(void);
void* WKWebsiteDataStoreSetStatisticsPrevalentResource(void);
void* WKWebsiteDataStoreSetStatisticsPruneEntriesDownTo(void);
void* WKWebsiteDataStoreSetStatisticsShouldClassifyResourcesBeforeDataRecordsRemoval(void);
void* WKWebsiteDataStoreSetStatisticsShouldPartitionCookiesForHost(void);
void* WKWebsiteDataStoreSetStatisticsSubframeUnderTopFrameOrigin(void);
void* WKWebsiteDataStoreSetStatisticsSubresourceUnderTopFrameOrigin(void);
void* WKWebsiteDataStoreSetStatisticsSubresourceUniqueRedirectTo(void);
void* WKWebsiteDataStoreSetStatisticsTimeToLiveCookiePartitionFree(void);
void* WKWebsiteDataStoreSetStatisticsTimeToLiveUserInteraction(void);
void* WKWebsiteDataStoreStatisticsClearInMemoryAndPersistentStore(void);
void* WKWebsiteDataStoreStatisticsClearInMemoryAndPersistentStoreModifiedSinceHours(void);
void* WKWebsiteDataStoreStatisticsClearThroughWebsiteDataRemoval(void);
void* WKWebsiteDataStoreStatisticsProcessStatisticsAndDataRecords(void);
void* WKWebsiteDataStoreStatisticsResetToConsistentState(void);
void* WKWebsiteDataStoreStatisticsSubmitTelemetry(void);
void* WKWebsiteDataStoreStatisticsUpdateCookiePartitioning(void);
void* WKWebsitePoliciesCopyCustomHeaderFields(void);
void* WKWebsitePoliciesCreate(void);
void* WKWebsitePoliciesGetAllowedAutoplayQuirks(void);
void* WKWebsitePoliciesGetAutoplayPolicy(void);
void* WKWebsitePoliciesGetContentBlockersEnabled(void);
void* WKWebsitePoliciesGetDataStore(void);
void* WKWebsitePoliciesGetTypeID(void);
void* WKWebsitePoliciesSetAllowedAutoplayQuirks(void);
void* WKWebsitePoliciesSetAutoplayPolicy(void);
void* WKWebsitePoliciesSetContentBlockersEnabled(void);
void* WKWebsitePoliciesSetCustomHeaderFields(void);
void* WKWebsitePoliciesSetDataStore(void);
void* WKWindowFeaturesGetTypeID(void);
void* WebContentServiceInitializer(void);
void* _WKSetCrashReportApplicationSpecificInformation(void);
void* _ZN6WebKit20EnvironmentUtilities27stripValuesEndingWithStringEPKcS2_(void);
void* _ZN6WebKit44setCrashReportApplicationSpecificInformationEPK10__CFString(void);

#endif
