#import <Foundation/NSObject.h>
#import <Foundation/NSGeometry.h>
#import <AppKit/NSView.h>

@class NSColor, NSTabView, NSView;

enum {
    NSSelectedTab = 0,
    NSBackgroundTab = 1,
    NSPressedTab = 2
};
typedef NSUInteger NSTabState;

@interface NSTabViewItem : NSObject <NSCoding>
{
    @private



    id _identifier;
    NSString *_label;
    NSView *_view;
    NSView *_initialFirstResponder;
    NSColor *_color;
    NSTabView *_tabView;



    NSTabState _tabState;
    NSView *_lastKeyView;

    struct __tviFlags {
 unsigned int hasCustomColor:1;
 unsigned int labelSizeIsValid:1;
 unsigned int autoGeneratedIFR:1;
 unsigned int isTabDisabled:1;
 unsigned int RESERVED:28;
    } _tviFlags;

    NSSize _labelSize;
    NSRect _tabRect;
    NSToolTipTag _tabToolTipTag;
    id _auxiliaryStorage;
}



- (id)initWithIdentifier:(id)identifier;



- (id)identifier;
- (id)view;
- (id)initialFirstResponder;
- (NSString *)label;
- (NSColor *)color;
- (NSTabState)tabState;
- (NSTabView *)tabView;



- (void)setIdentifier:(id)identifier;
- (void)setLabel:(NSString *)label;
- (void)setColor:(NSColor *)color;
- (void)setView:(NSView *)view;
- (void)setInitialFirstResponder:(NSView *)view;



- (NSString *)toolTip;
- (void)setToolTip:(NSString *)toolTip;





- (void)drawLabel:(BOOL)shouldTruncateLabel inRect:(NSRect)labelRect;



- (NSSize)sizeOfLabel:(BOOL)computeMin;

@end
