#ifndef DUCT_ERRNO_H
#define DUCT_ERRNO_H

#include <errno.h>
#
#define LINUX_EPERM EPERM
#undef EPERM
#define LINUX_ENOENT ENOENT
#undef ENOENT
#define LINUX_ESRCH ESRCH
#undef ESRCH
#define LINUX_EINTR EINTR
#undef EINTR
#define LINUX_EIO EIO
#undef EIO
#define LINUX_ENXIO ENXIO
#undef ENXIO
#define LINUX_ENOEXEC ENOEXEC
#undef ENOEXEC
#define LINUX_EBADF EBADF
#undef EBADF
#define LINUX_ECHILD ECHILD
#undef ECHILD
#define LINUX_EAGAIN EAGAIN
#undef EAGAIN
#define LINUX_ENOMEM ENOMEM
#undef ENOMEM
#define LINUX_EACCES EACCES
#undef EACCES
#define LINUX_EFAULT EFAULT
#undef EFAULT
#define LINUX_ENOTBLK ENOTBLK
#undef ENOTBLK
#define LINUX_EBUSY EBUSY
#undef EBUSY
#define LINUX_EEXIST EEXIST
#undef EEXIST
#define LINUX_EXDEV EXDEV
#undef EXDEV
#define LINUX_ENODEV ENODEV
#undef ENODEV
#define LINUX_ENOTDIR ENOTDIR
#undef ENOTDIR
#define LINUX_EISDIR EISDIR
#undef EISDIR
#define LINUX_EINVAL EINVAL
#undef EINVAL
#define LINUX_ENFILE ENFILE
#undef ENFILE
#define LINUX_EMFILE EMFILE
#undef EMFILE
#define LINUX_ENOTTY ENOTTY
#undef ENOTTY
#define LINUX_ETXTBSY ETXTBSY
#undef ETXTBSY
#define LINUX_EFBIG EFBIG
#undef EFBIG
#define LINUX_ENOSPC ENOSPC
#undef ENOSPC
#define LINUX_ESPIPE ESPIPE
#undef ESPIPE
#define LINUX_EROFS EROFS
#undef EROFS
#define LINUX_EMLINK EMLINK
#undef EMLINK
#define LINUX_EPIPE EPIPE
#undef EPIPE
#define LINUX_EDOM EDOM
#undef EDOM
#define LINUX_ERANGE ERANGE
#undef ERANGE
#define LINUX_EDEADLK EDEADLK
#undef EDEADLK
#define LINUX_ENAMETOOLONG ENAMETOOLONG
#undef ENAMETOOLONG
#define LINUX_ENOLCK ENOLCK
#undef ENOLCK
#define LINUX_ENOSYS ENOSYS
#undef ENOSYS
#define LINUX_ENOTEMPTY ENOTEMPTY
#undef ENOTEMPTY
#define LINUX_ELOOP ELOOP
#undef ELOOP
#define LINUX_ENOMSG ENOMSG
#undef ENOMSG
#define LINUX_EIDRM EIDRM
#undef EIDRM
#define LINUX_ECHRNG ECHRNG
#undef ECHRNG
#define LINUX_ELNRNG ELNRNG
#undef ELNRNG
#define LINUX_EUNATCH EUNATCH
#undef EUNATCH
#define LINUX_ENOCSI ENOCSI
#undef ENOCSI
#define LINUX_EBADE EBADE
#undef EBADE
#define LINUX_EBADR EBADR
#undef EBADR
#define LINUX_EXFULL EXFULL
#undef EXFULL
#define LINUX_ENOANO ENOANO
#undef ENOANO
#define LINUX_EBADRQC EBADRQC
#undef EBADRQC
#define LINUX_EBADSLT EBADSLT
#undef EBADSLT
#define LINUX_EBFONT EBFONT
#undef EBFONT
#define LINUX_ENOSTR ENOSTR
#undef ENOSTR
#define LINUX_ENODATA ENODATA
#undef ENODATA
#define LINUX_ETIME ETIME
#undef ETIME
#define LINUX_ENOSR ENOSR
#undef ENOSR
#define LINUX_ENONET ENONET
#undef ENONET
#define LINUX_ENOPKG ENOPKG
#undef ENOPKG
#define LINUX_EREMOTE EREMOTE
#undef EREMOTE
#define LINUX_ENOLINK ENOLINK
#undef ENOLINK
#define LINUX_EADV EADV
#undef EADV
#define LINUX_ESRMNT ESRMNT
#undef ESRMNT
#define LINUX_ECOMM ECOMM
#undef ECOMM
#define LINUX_EPROTO EPROTO
#undef EPROTO
#define LINUX_EMULTIHOP EMULTIHOP
#undef EMULTIHOP
#define LINUX_EDOTDOT EDOTDOT
#undef EDOTDOT
#define LINUX_EBADMSG EBADMSG
#undef EBADMSG
#define LINUX_EOVERFLOW EOVERFLOW
#undef EOVERFLOW
#define LINUX_ENOTUNIQ ENOTUNIQ
#undef ENOTUNIQ
#define LINUX_EBADFD EBADFD
#undef EBADFD
#define LINUX_EREMCHG EREMCHG
#undef EREMCHG
#define LINUX_ELIBACC ELIBACC
#undef ELIBACC
#define LINUX_ELIBBAD ELIBBAD
#undef ELIBBAD
#define LINUX_ELIBSCN ELIBSCN
#undef ELIBSCN
#define LINUX_ELIBMAX ELIBMAX
#undef ELIBMAX
#define LINUX_ELIBEXEC ELIBEXEC
#undef ELIBEXEC
#define LINUX_EILSEQ EILSEQ
#undef EILSEQ
#define LINUX_ERESTART ERESTART
#undef ERESTART
#define LINUX_ESTRPIPE ESTRPIPE
#undef ESTRPIPE
#define LINUX_EUSERS EUSERS
#undef EUSERS
#define LINUX_ENOTSOCK ENOTSOCK
#undef ENOTSOCK
#define LINUX_EDESTADDRREQ EDESTADDRREQ
#undef EDESTADDRREQ
#define LINUX_EMSGSIZE EMSGSIZE
#undef EMSGSIZE
#define LINUX_EPROTOTYPE EPROTOTYPE
#undef EPROTOTYPE
#define LINUX_ENOPROTOOPT ENOPROTOOPT
#undef ENOPROTOOPT
#define LINUX_EPROTONOSUPPORT EPROTONOSUPPORT
#undef EPROTONOSUPPORT
#define LINUX_ESOCKTNOSUPPORT ESOCKTNOSUPPORT
#undef ESOCKTNOSUPPORT
#define LINUX_EOPNOTSUPP EOPNOTSUPP
#undef EOPNOTSUPP
#define LINUX_EPFNOSUPPORT EPFNOSUPPORT
#undef EPFNOSUPPORT
#define LINUX_EAFNOSUPPORT EAFNOSUPPORT
#undef EAFNOSUPPORT
#define LINUX_EADDRINUSE EADDRINUSE
#undef EADDRINUSE
#define LINUX_EADDRNOTAVAIL EADDRNOTAVAIL
#undef EADDRNOTAVAIL
#define LINUX_ENETDOWN ENETDOWN
#undef ENETDOWN
#define LINUX_ENETUNREACH ENETUNREACH
#undef ENETUNREACH
#define LINUX_ENETRESET ENETRESET
#undef ENETRESET
#define LINUX_ECONNABORTED ECONNABORTED
#undef ECONNABORTED
#define LINUX_ECONNRESET ECONNRESET
#undef ECONNRESET
#define LINUX_ENOBUFS ENOBUFS
#undef ENOBUFS
#define LINUX_EISCONN EISCONN
#undef EISCONN
#define LINUX_ENOTCONN ENOTCONN
#undef ENOTCONN
#define LINUX_ESHUTDOWN ESHUTDOWN
#undef ESHUTDOWN
#define LINUX_ETOOMANYREFS ETOOMANYREFS
#undef ETOOMANYREFS
#define LINUX_ETIMEDOUT ETIMEDOUT
#undef ETIMEDOUT
#define LINUX_ECONNREFUSED ECONNREFUSED
#undef ECONNREFUSED
#define LINUX_EHOSTDOWN EHOSTDOWN
#undef EHOSTDOWN
#define LINUX_EHOSTUNREACH EHOSTUNREACH
#undef EHOSTUNREACH
#define LINUX_EALREADY EALREADY
#undef EALREADY
#define LINUX_EINPROGRESS EINPROGRESS
#undef EINPROGRESS
#define LINUX_ESTALE ESTALE
#undef ESTALE
#define LINUX_EUCLEAN EUCLEAN
#undef EUCLEAN
#define LINUX_ENOTNAM ENOTNAM
#undef ENOTNAM
#define LINUX_ENAVAIL ENAVAIL
#undef ENAVAIL
#define LINUX_EISNAM EISNAM
#undef EISNAM
#define LINUX_EREMOTEIO EREMOTEIO
#undef EREMOTEIO
#define LINUX_EDQUOT EDQUOT
#undef EDQUOT
#define LINUX_ENOMEDIUM ENOMEDIUM
#undef ENOMEDIUM
#define LINUX_EMEDIUMTYPE EMEDIUMTYPE
#undef EMEDIUMTYPE
#define LINUX_ECANCELED ECANCELED
#undef ECANCELED
#define LINUX_ENOKEY ENOKEY
#undef ENOKEY
#define LINUX_EKEYEXPIRED EKEYEXPIRED
#undef EKEYEXPIRED
#define LINUX_EKEYREVOKED EKEYREVOKED
#undef EKEYREVOKED
#define LINUX_EKEYREJECTED EKEYREJECTED
#undef EKEYREJECTED
#define LINUX_EOWNERDEAD EOWNERDEAD
#undef EOWNERDEAD
#define LINUX_ENOTRECOVERABLE ENOTRECOVERABLE
#undef ENOTRECOVERABLE
#define LINUX_ERFKILL ERFKILL
#undef ERFKILL
#define LINUX_EHWPOISON EHWPOISON
#undef EHWPOISON
#define LINUX_ENOTSUP ENOTSUP
#undef ENOTSUP

#undef errno

#include "../../../kernel-include/sys/errno.h"

#endif
