.\" Copyright (c) 1985, 1991 Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     from: @(#)j0.3	6.7 (Berkeley) 4/19/91
.\"	$Id: j0.3,v 1.3 2003/08/17 20:36:47 scp Exp $
.\"
.Dd December 11, 2006
.Dt J0 3
.Os BSD 4
.Sh NAME
.Nm j0 ,
.Nm j1 ,
.Nm jn ,
.Nm y0 ,
.Nm y1 ,
.Nm yn
.Nd bessel functions of first and second kind
.Sh SYNOPSIS
.Fd #include <math.h>
.Ft double
.Fn j0 "double x"
.\.Ft float
.\.Fn j0f "float x"
.Ft double
.Fn j1 "double x"
.\.Ft float
.\.Fn j1f "float x"
.Ft double
.Fn jn "int n" "double x"
.\.Ft float
.\.Fn jnf "int n" "float x"
.Ft double
.Fn y0 "double x"
.\.Ft float
.\.Fn y0f "float x"
.Ft double
.Fn y1 "double x"
.\.Ft float
.\.Fn y1f "float x"
.Ft double
.Fn yn "int n" "double x"
.\.Ft float
.\.Fn ynf "int n" "float x"
.Sh DESCRIPTION
The functions
.Fn j0 "x"
and 
.Fn j1 "x"
compute the Bessel function of the first kind of the order
0 and the order 1, respectively; the function
.Fn jn "n" "x"
computes the Bessel function of the first kind of the integer order n.
.Pp
The functions
.Fn y0 "x"
and
.Fn y1 "x"
compute the linearly independent Bessel function of the second kind of the order
0 and the order 1, respectively, for the positive integer value x (expressed as a double);
the function
.Fn yn "n" "x"
computes the Bessel function of the second kind for the integer order n
for the positive integer value x (expressed as a double).
.Sh SPECIAL VALUES
.Fn j0 "0"
returns 1.
.Pp
.Fn j0 "±infinity"
returns 0.
.Pp
.Fn j0 "NaN"
returns a NaN.
.Pp
.Fn j1 "0"
returns 0.
.Pp
.Fn j1 "+infinity"
returns 0.
.Pp
.Fn j1 "NaN"
returns a NaN.
.Pp
.Fn y0 "0"
,
.Fn y1 "0"
, and
.Fn yn "n" "0"
all return -infinity and raise the "division-by-zero" floating-point flag.
