#!/bin/sh
# 
# This file is part of Darling.
# 
# Copyright (C) 2015 Lubos Dolezel
# 
# Darling is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Darling is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Darling.  If not, see <http://www.gnu.org/licenses/>.
# 

if [ $# -lt 1 ]; then
    >&2 echo "This is Darling fake sudo."
    >&2 echo "Processes will think they run as UID 0, but Linux kernel will still see your original UID."
    >&2 echo "The purpose is to convince some tools that they can write into /."

    exit 1
fi

export __FAKE_SETUID_ROOT=1
export __FAKE_SETGID_ROOT=1

if [ $1 == "-k" ]; then
    shift
fi

exec "${@:1}"
